//! Engraver: lower covenant models to silverscript (BUILD_SPEC §6).

use portrait_ir::{CovenantModel, Mode, SilFile};
use portrait_syntax::{Expr, ReturnExpr, Type};
use std::collections::HashSet;

/// Emit one .sil file per covenant model.
///
/// Returns `Err` (fail-loud) if any covenant transition body carries a
/// `Stmt::Raw` guard — an unrecognised/unlowerable guard form (e.g. the `@`
/// age syntax) that parsed to `Stmt::Raw`. Such a statement would otherwise be
/// silently dropped at emit, producing a covenant that LOOKS gated but enforces
/// nothing — a soundness/honesty defect. Naming the offending statement makes
/// the gap impossible to ship unnoticed.
pub fn emit(models: &[CovenantModel]) -> Result<Vec<SilFile>, String> {
    models.iter().map(emit_model).collect()
}

fn emit_model(model: &CovenantModel) -> Result<SilFile, String> {
    let mut src = String::new();

    src.push_str("pragma silverscript ^0.1.0;\n");
    src.push_str("\n// Generated by portrait build\n");

    // Contract declaration.  We always prepend `max_ins` and `max_outs` params
    // for the covenant binding attribute, followed by the user-declared params.
    src.push_str(&format!(
        "contract {}(int max_ins, int max_outs",
        model.name
    ));
    for (name, ty) in &model.params {
        src.push_str(&format!(", {} {}", emit_type(ty), name));
    }
    src.push_str(") {\n");

    // State fields: direct field declarations initialised from user constructor params.
    for (i, (name, ty)) in model.state.iter().enumerate() {
        // If there's no matching constructor param for this state field, default to 0.
        let init_owned;
        let init = match model.params.get(i) {
            Some((pname, _)) => pname.as_str(),
            None => {
                init_owned = "0".to_string();
                &init_owned
            }
        };
        src.push_str(&format!("    {} {} = {};\n", emit_type(ty), name, init));
    }

    // Entrypoints — skip NonCovenant (VProg) transitions; they are handled by Atelier.
    for tr in model
        .transitions
        .iter()
        .filter(|t| !matches!(t.mode, Mode::NonCovenant))
    {
        src.push('\n');
        let mode_str = match tr.mode {
            Mode::Transition => "transition",
            Mode::Verification => "verification",
            Mode::NonCovenant => "non_covenant",
        };
        // Transition functions with the return-type declaration require `to = 1` (literal)
        // per silverscript c46e0e2+. Non-transition functions keep `to = max_outs`.
        let is_transition = matches!(tr.mode, Mode::Transition) && tr.to.is_some();
        let to_str = if is_transition { "1" } else { "max_outs" };
        src.push_str(&format!(
            "    #[covenant(binding = cov, from = max_ins, to = {}, mode = {})]\n",
            to_str, mode_str
        ));
        // Build extra arg string from M1 args.
        // When the role has a CSCI VProg binding, append `proof_cov_id: byte[32]` so
        // the caller can pass the covenant_id from the STARK journal for on-chain binding.
        let mut extra_args: String = tr
            .args
            .iter()
            .map(|(name, ty)| format!(", {} {}", emit_type(ty), name))
            .collect();
        if model.has_vprog && matches!(tr.mode, Mode::Transition) {
            extra_args.push_str(", byte[32] proof_cov_id");
        }
        // Transition mode uses the return-type declaration syntax (silverscript c46e0e2+):
        //   function f(State[] prev_states, ...) : (State) { return({ ... }); }
        let return_type_str = if is_transition { " : (State)" } else { "" };
        src.push_str(&format!(
            "    function {}(State[] prev_states{}){} {{\n",
            tr.entry, extra_args, return_type_str
        ));
        // Emit body.
        // Phase B4: walk the typed `ReturnExpr`/`Expr` tree directly via
        // `emit_expr` — no more re-stringify-then-substitute round-trip. Bare
        // state-field `Var`s are lowered to `prev_states[0].field` structurally.
        let return_expr: Option<&ReturnExpr> = tr.body.iter().find_map(|s| match s {
            portrait_syntax::Stmt::Return(expr) => Some(expr),
            _ => None,
        });
        if is_transition {
            // CSCI cross-layer binding check: verify that the STARK journal's
            // covenant_id matches the on-chain covenant's own ID.
            // proof_cov_id is bytes 0..32 of the RISC Zero STARK journal
            // (the covenant_id field; matches the COV_ID const embedded in the vProg guest).
            // OpInputCovenantId(0) returns the covenant ID of the spending input at index 0.
            // NOTE: index 0 assumes the covenant UTXO is the first input in the transaction.
            // For multi-input transactions where the covenant appears at a different index,
            // adjust the index accordingly.
            // [PENDING: add OpZkPrecompile(0x21, journal) call when engine support lands]
            if model.has_vprog {
                src.push_str("        require(proof_cov_id == OpInputCovenantId(0));\n");
            }
            // Emit the entrypoint's `require(...)` guards. Each Require statement's
            // expression is lowered by walking the typed `Expr`: bare state field
            // `Var`s are rewritten to `prev_states[0].field`, while constructor
            // params (e.g. issuer, window) and entrypoint args pass through unchanged.
            // Without this the emitted covenant would carry state forward but enforce
            // none of its invariants — the guards are what make the transition reject.
            let field_set: HashSet<&str> = model.state.iter().map(|(n, _)| n.as_str()).collect();
            for stmt in &tr.body {
                match stmt {
                    portrait_syntax::Stmt::Require(expr) => {
                        src.push_str(&format!(
                            "        require({});\n",
                            emit_expr(expr, &field_set)
                        ));
                    }
                    // Fail-loud: an unrecognised guard form parsed to `Stmt::Raw`
                    // (e.g. the `@` age syntax `requires v @ 1;`). Emitting the
                    // covenant while dropping it would yield a contract that LOOKS
                    // gated but enforces nothing. Abort instead, naming the
                    // offending guard so the gap cannot ship silently.
                    portrait_syntax::Stmt::Raw(text) => {
                        return Err(format!(
                            "covenant `{}` entrypoint `{}`: unlowerable guard statement \
                             `{}` would be silently dropped — refusing to emit an \
                             unguarded covenant. Rewrite it as a `requires <expr>;` \
                             clause the emitter can lower, or route the construct to \
                             the vProgs layer.",
                            model.name,
                            tr.entry,
                            text.trim()
                        ));
                    }
                    portrait_syntax::Stmt::Return(_) => {}
                }
            }
            match return_expr {
                Some(ReturnExpr::Object { fields, .. }) => {
                    // Multi-field state object literal: `Name { f1: v1, f2: v2, ... }`.
                    // Keep each field key bare; lower only the value side (state field
                    // references → prev_states[0].field; args/params pass through).
                    let rendered: Vec<String> = fields
                        .iter()
                        .map(|(key, value)| format!("{}: {}", key, emit_expr(value, &field_set)))
                        .collect();
                    src.push_str(&format!("        return({{ {} }});\n", rendered.join(", ")));
                }
                Some(ReturnExpr::Scalar(expr)) => {
                    // Scalar return: build the full state object, substituting the lowered
                    // expression for the single referenced field and carrying the rest.
                    let rendered: Vec<String> = model
                        .state
                        .iter()
                        .map(|(name, _)| {
                            if expr_references_var(expr, name) {
                                format!("{}: {}", name, emit_expr(expr, &field_set))
                            } else {
                                format!("{}: prev_states[0].{}", name, name)
                            }
                        })
                        .collect();
                    src.push_str(&format!("        return({{ {} }});\n", rendered.join(", ")));
                }
                None => {
                    src.push_str("        return(prev_states[0]);\n");
                }
            }
        }
        src.push_str("    }\n");
    }

    src.push_str("}\n");

    Ok(SilFile {
        name: format!("{}.sil", model.name),
        source: src,
    })
}

/// Emit a default CTOR JSON for `silverc --ctor` compilation.
/// Returns (filename, json_content).  Expr format: {"kind":"int","data":N}.
pub fn emit_ctor(model: &CovenantModel) -> (String, String) {
    // Always prepend max_ins=1 and max_outs=1.
    let mut exprs: Vec<String> = vec![
        r#"{"kind":"int","data":1}"#.to_string(),
        r#"{"kind":"int","data":1}"#.to_string(),
    ];
    for (_, ty) in &model.params {
        exprs.push(default_expr(ty));
    }
    (
        format!("{}_ctor.json", model.name),
        format!("[{}]", exprs.join(",")),
    )
}

fn default_expr(ty: &Type) -> String {
    match ty {
        Type::Int | Type::Coin => r#"{"kind":"int","data":0}"#.to_string(),
        Type::Bool => r#"{"kind":"bool","data":false}"#.to_string(),
        // silverc expects fixed-width byte arrays as {"kind":"array","data":[{"kind":"byte",...}]}.
        // It rejects {"kind":"hex",...} ("unknown variant `hex`"), so emit zero-filled byte arrays:
        // 32 bytes for pubkey/byte[32], 64 bytes for a signature.
        Type::PubKey | Type::Bytes32 => zero_byte_array(32),
        Type::Sig => zero_byte_array(64),
        Type::Set(_) | Type::Map(_, _) => r#"{"kind":"array","data":[]}"#.to_string(),
        Type::Named(_) => r#"{"kind":"int","data":0}"#.to_string(),
    }
}

/// Emit a silverc Expr for a zero-filled fixed-width byte array of length `n`,
/// i.e. {"kind":"array","data":[{"kind":"byte","data":0}, ... n times]}.
fn zero_byte_array(n: usize) -> String {
    let bytes = vec![r#"{"kind":"byte","data":0}"#; n].join(",");
    format!(r#"{{"kind":"array","data":[{}]}}"#, bytes)
}

/// Lower a typed `Expr` to its silverscript surface form, rewriting each bare
/// state-field `Var` to `prev_states[0].field`. This is the AST-walking
/// replacement for the Phase B transitional string substitution
/// (`lower_return_expr`) — field detection is now structural (only a `Var` whose
/// name is a state field is rewritten), so prefix collisions are impossible by
/// construction and there is no re-stringify/re-tokenize round-trip.
///
/// Operator spelling and whitespace match `Expr::to_silverscript` exactly so the
/// emitted .sil stays byte-identical to the pre-B4 output.
fn emit_expr(expr: &Expr, state_fields: &HashSet<&str>) -> String {
    match expr {
        Expr::Int(n) => n.to_string(),
        Expr::Bool(b) => b.to_string(),
        Expr::Bytes(bytes) => {
            let hex: String = bytes.iter().map(|b| format!("{b:02x}")).collect();
            format!("0x{hex}")
        }
        Expr::Var(name) => {
            if state_fields.contains(name.as_str()) {
                format!("prev_states[0].{}", name)
            } else {
                name.clone()
            }
        }
        Expr::Field { base, field } => format!("{}.{}", emit_expr(base, state_fields), field),
        Expr::Index { base, index } => format!(
            "{}[{}]",
            emit_expr(base, state_fields),
            emit_expr(index, state_fields)
        ),
        Expr::Unary { op, rhs } => {
            // Unary operators bind tighter than every binary operator, so a
            // `Binary` operand is only reachable via authored parentheses and
            // must be re-parenthesized — otherwise `-(a + b)` would emit as
            // `-a + b` and silently regroup to `(-a) + b`. Non-Binary operands
            // (literals/idents/fields/calls/nested unary) never need parens.
            let inner = emit_expr(rhs, state_fields);
            if matches!(rhs.as_ref(), Expr::Binary { .. }) {
                format!("{}({})", op.as_str(), inner)
            } else {
                format!("{}{}", op.as_str(), inner)
            }
        }
        Expr::Binary { op, lhs, rhs } => {
            // Precedence-aware emission: parenthesize a Binary *child* whenever
            // re-parsing the flat string would regroup it differently from the
            // authored tree. Non-Binary children never need parens. All Portrait
            // binary operators are left-associative (parser sets right_bp = left_bp + 1),
            // so: a LEFT child needs parens iff its precedence is strictly lower
            // than the parent's; a RIGHT child needs parens iff its precedence is
            // lower than OR equal to the parent's. Without this, e.g.
            // `(a + b) * c` would emit as `a + b * c` and silently weaken the guard.
            let pp = binop_prec(*op);
            format!(
                "{} {} {}",
                emit_child(lhs, state_fields, pp, false),
                op.as_str(),
                emit_child(rhs, state_fields, pp, true),
            )
        }
        Expr::Call { name, args } => {
            let rendered: Vec<String> = args.iter().map(|a| emit_expr(a, state_fields)).collect();
            format!("{}({})", name, rendered.join(", "))
        }
    }
}

/// Surface precedence of a binary operator, mirroring the Pratt parser's binding
/// powers in `portrait-syntax` (Mul=9, Add/Sub=7, comparisons=5, And=3, Or=1).
/// Higher binds tighter. Kept in sync with `Parser::peek_binop`.
fn binop_prec(op: portrait_syntax::BinOp) -> u8 {
    use portrait_syntax::BinOp;
    match op {
        BinOp::Or => 1,
        BinOp::And => 3,
        BinOp::Eq | BinOp::Ne | BinOp::Ge | BinOp::Le | BinOp::Gt | BinOp::Lt => 5,
        BinOp::Add | BinOp::Sub => 7,
        BinOp::Mul => 9,
    }
}

/// Emit a binary operand, wrapping it in parens only when re-parsing would
/// regroup it. `parent_prec` is the precedence of the enclosing operator;
/// `is_right` is true for the right-hand operand. All operators are
/// left-associative, so a right operand of equal precedence must be parenthesized
/// (e.g. `a - (b - c)`), while a left operand of equal precedence need not be
/// (e.g. `a - b - c`). Only `Binary` children can ever need parens.
fn emit_child(
    expr: &Expr,
    state_fields: &HashSet<&str>,
    parent_prec: u8,
    is_right: bool,
) -> String {
    let inner = emit_expr(expr, state_fields);
    if let Expr::Binary { op, .. } = expr {
        let cp = binop_prec(*op);
        let needs = if is_right {
            cp <= parent_prec
        } else {
            cp < parent_prec
        };
        if needs {
            return format!("({})", inner);
        }
    }
    inner
}

/// Whether `expr` references the variable `name` anywhere as a bare `Var`.
/// Replaces the old `expr.contains(name)` substring heuristic with a structural
/// walk, so e.g. a field `bal` is not considered referenced by `balance`.
fn expr_references_var(expr: &Expr, name: &str) -> bool {
    match expr {
        Expr::Var(v) => v == name,
        Expr::Int(_) | Expr::Bool(_) | Expr::Bytes(_) => false,
        Expr::Field { base, .. } => expr_references_var(base, name),
        Expr::Index { base, index } => {
            expr_references_var(base, name) || expr_references_var(index, name)
        }
        Expr::Unary { rhs, .. } => expr_references_var(rhs, name),
        Expr::Binary { lhs, rhs, .. } => {
            expr_references_var(lhs, name) || expr_references_var(rhs, name)
        }
        Expr::Call { args, .. } => args.iter().any(|a| expr_references_var(a, name)),
    }
}

fn emit_type(ty: &Type) -> String {
    match ty {
        Type::Int => "int".to_string(),
        Type::Bool => "bool".to_string(),
        Type::PubKey => "pubkey".to_string(),
        Type::Sig => "sig".to_string(),
        Type::Bytes32 => "byte[32]".to_string(),
        // silverscript has no `coin` type — `coin` is a Portrait-level concept
        // (a strictly-conserved value, distinct from an adjustable `int`). It is
        // lowered to silverscript's `int` representation here. silverc rejects a
        // bare `coin` struct field ("unknown type 'coin' in struct field"); the
        // Portrait type checker still treats `coin` as non-arithmetic and
        // non-int-comparable, so the conservation guarantees are enforced at the
        // Portrait layer, not lost by this lowering. See emit_type tests.
        Type::Coin => "int".to_string(),
        Type::Set(inner) => format!("{}[]", emit_type(inner)),
        Type::Map(k, v) => format!("map<{},{}>", emit_type(k), emit_type(v)),
        Type::Named(n) => n.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use portrait_ir::{CovenantModel, Mode, Transition};
    use portrait_syntax::{Stmt, Type};

    fn counter_model(body: Vec<Stmt>) -> CovenantModel {
        CovenantModel {
            name: "Counter".into(),
            params: vec![("start".into(), Type::Int)],
            state: vec![("value".into(), Type::Int)],
            transitions: vec![Transition {
                entry: "bump".into(),
                from: "live".into(),
                to: Some("live".into()),
                mode: Mode::Transition,
                guards: vec![],
                capability: None,
                args: vec![("delta".into(), Type::Int)],
                body,
            }],
            has_vprog: false,
        }
    }

    fn counter_model_with_vprog(body: Vec<Stmt>) -> CovenantModel {
        CovenantModel {
            has_vprog: true,
            ..counter_model(body)
        }
    }

    #[test]
    fn counter_m1_args_in_signature() {
        let model = counter_model(vec![Stmt::Return(
            portrait_syntax::parse_return_expr("value + delta").unwrap(),
        )]);
        let files = emit(&[model]).expect("emit");
        assert_eq!(files.len(), 1);
        let src = &files[0].source;
        assert!(
            src.contains("int delta"),
            "should include delta arg: {}",
            src
        );
        assert!(
            src.contains(": (State)"),
            "should emit return-type annotation: {}",
            src
        );
        assert!(
            src.contains("return({"),
            "should emit return expression: {}",
            src
        );
        assert!(
            src.contains("prev_states[0].value + delta"),
            "should lower expression: {}",
            src
        );
    }

    #[test]
    fn counter_m1_no_return_statement() {
        let model = counter_model(vec![Stmt::Return(
            portrait_syntax::parse_return_expr("value + delta").unwrap(),
        )]);
        let files = emit(&[model]).expect("emit");
        let src = &files[0].source;
        assert!(
            !src.contains("return(prev_states)"),
            "should not have stub return: {}",
            src
        );
    }

    #[test]
    fn emit_covenant_with_vprog_adds_proof_cov_id_arg_and_require() {
        let model = counter_model_with_vprog(vec![Stmt::Return(
            portrait_syntax::parse_return_expr("value + delta").unwrap(),
        )]);
        let files = emit(&[model]).expect("emit");
        let src = &files[0].source;
        // proof_cov_id arg must appear in the function signature.
        assert!(
            src.contains("byte[32] proof_cov_id"),
            "proof_cov_id arg missing: {}",
            src
        );
        // OpInputCovenantId binding check must appear in the function body.
        assert!(
            src.contains("require(proof_cov_id == OpInputCovenantId(0))"),
            "OpInputCovenantId require missing: {}",
            src
        );
    }

    #[test]
    fn emit_covenant_without_vprog_no_proof_cov_id() {
        let model = counter_model(vec![Stmt::Return(
            portrait_syntax::parse_return_expr("value + delta").unwrap(),
        )]);
        let files = emit(&[model]).expect("emit");
        let src = &files[0].source;
        // No VProg: no proof_cov_id or binding check.
        assert!(
            !src.contains("proof_cov_id"),
            "should not have proof_cov_id without vprog: {}",
            src
        );
        assert!(
            !src.contains("OpInputCovenantId"),
            "should not have OpInputCovenantId without vprog: {}",
            src
        );
    }

    #[test]
    fn emit_expr_prefix_collision_safe() {
        // Field "val" must not be lowered when only "value" is referenced.
        // With the AST walk this is structural: a Var("value") never matches the
        // "val" field, so prefix collisions are impossible by construction.
        let fields: HashSet<&str> = ["val", "value"].into_iter().collect();
        let e = portrait_syntax::parse_expr("value + delta").unwrap();
        assert_eq!(
            emit_expr(&e, &fields),
            "prev_states[0].value + delta",
            "val should not contaminate value"
        );
        let e2 = portrait_syntax::parse_expr("val + 1").unwrap();
        assert_eq!(
            emit_expr(&e2, &fields),
            "prev_states[0].val + 1",
            "val standalone"
        );
    }

    #[test]
    fn emit_expr_lowers_only_state_field_vars() {
        // Constructor params / args (not in the field set) pass through unchanged;
        // function-call args and nested operands are walked structurally.
        let fields: HashSet<&str> = ["seq"].into_iter().collect();
        let e = portrait_syntax::parse_expr("checkSig(sig, issuer) && seq <= window").unwrap();
        assert_eq!(
            emit_expr(&e, &fields),
            "checkSig(sig, issuer) && prev_states[0].seq <= window"
        );
    }

    #[test]
    fn emit_expr_lowers_blake2b_hashlock_verbatim() {
        // blake2b(preimage) == hashlock: the call lowers verbatim to the silverc
        // `blake2b(_)` builtin (which emits OpBlake2b, 0xaa); the committed
        // `hashlock` state field is read through prev_states[0]. The caller-
        // supplied `preimage` passes through unchanged.
        let fields: HashSet<&str> = ["hashlock"].into_iter().collect();
        let e = portrait_syntax::parse_expr("blake2b(preimage) == hashlock").unwrap();
        assert_eq!(
            emit_expr(&e, &fields),
            "blake2b(preimage) == prev_states[0].hashlock"
        );
    }

    #[test]
    fn ctor_emits_byte_arrays_not_hex_for_bytes32_and_pubkey() {
        // Regression: silverc rejects {"kind":"hex",...} ("unknown variant `hex`").
        // byte[32]/pubkey constructor args must be 32-element byte arrays; sig 64.
        let model = CovenantModel {
            name: "T".into(),
            params: vec![
                ("k".into(), Type::PubKey),
                ("h".into(), Type::Bytes32),
                ("s".into(), Type::Sig),
            ],
            state: vec![],
            transitions: vec![],
            has_vprog: false,
        };
        let (_, json) = emit_ctor(&model);
        assert!(
            !json.contains("\"hex\""),
            "must not emit hex kind: {}",
            json
        );
        // 32-byte arrays for pubkey + bytes32 = 64 byte entries; sig adds 64 more = 128.
        let byte_count = json.matches(r#"{"kind":"byte","data":0}"#).count();
        assert_eq!(byte_count, 32 + 32 + 64, "byte counts: {}", json);
    }

    #[test]
    fn object_return_emits_one_field_per_pair_via_ast() {
        // Multi-field object returns are now driven by the typed ReturnExpr::Object
        // (one (field, Expr) pair per declared state field). The value side is
        // lowered structurally; the head name is dropped in the emitted return.
        let ret = portrait_syntax::parse_return_expr(
            "EvidenceLineage { seq: seq + 1, subject: subject, commit: next_commit }",
        )
        .unwrap();
        let fields: HashSet<&str> = ["seq", "subject", "commit"].into_iter().collect();
        match ret {
            ReturnExpr::Object {
                fields: pairs,
                name,
            } => {
                assert_eq!(name.as_deref(), Some("EvidenceLineage"));
                assert_eq!(pairs.len(), 3);
                assert_eq!(pairs[0].0, "seq");
                assert_eq!(emit_expr(&pairs[0].1, &fields), "prev_states[0].seq + 1");
                assert_eq!(pairs[1].0, "subject");
                assert_eq!(emit_expr(&pairs[1].1, &fields), "prev_states[0].subject");
                assert_eq!(emit_expr(&pairs[2].1, &fields), "next_commit");
            }
            other => panic!("expected object return, got {other:?}"),
        }
        // A scalar expression parses as ReturnExpr::Scalar, not Object.
        assert!(matches!(
            portrait_syntax::parse_return_expr("value + delta").unwrap(),
            ReturnExpr::Scalar(_)
        ));
    }

    #[test]
    fn emit_lowers_coin_field_to_int_not_coin() {
        // Phase D1: a `coin` state field / param must lower to silverscript `int`
        // (silverc rejects a bare `coin` struct field). The conservation
        // semantics of `coin` live in the Portrait type checker, not the .sil.
        let model = CovenantModel {
            name: "CoinHolder".into(),
            params: vec![
                ("owner".into(), Type::PubKey),
                ("amount".into(), Type::Coin),
            ],
            state: vec![
                ("owner".into(), Type::PubKey),
                ("amount".into(), Type::Coin),
            ],
            transitions: vec![Transition {
                entry: "carry".into(),
                from: "live".into(),
                to: Some("live".into()),
                mode: Mode::Transition,
                guards: vec![],
                capability: None,
                args: vec![],
                body: vec![Stmt::Return(
                    portrait_syntax::parse_return_expr(
                        "CoinHolder { owner: owner, amount: amount }",
                    )
                    .unwrap(),
                )],
            }],
            has_vprog: false,
        };
        let files = emit(&[model]).expect("emit");
        let src = &files[0].source;
        assert!(
            !src.contains("coin "),
            "coin must not appear as a silverscript type: {}",
            src
        );
        // Field/param declarations must use `int amount`.
        assert!(
            src.contains("int amount = amount;"),
            "coin field must lower to int declaration: {}",
            src
        );
        assert!(
            src.contains(", int amount)"),
            "coin param must lower to int in the constructor: {}",
            src
        );
    }

    #[test]
    fn emit_type_coin_is_int() {
        assert_eq!(emit_type(&Type::Coin), "int");
    }

    #[test]
    fn emit_expr_preserves_authored_parens_for_precedence() {
        // Regression: emit_expr previously rendered Binary as "{lhs} {op} {rhs}"
        // with no parens, silently changing precedence when re-parsed by silverc.
        let fields: HashSet<&str> = HashSet::new();

        // (a + b) * c must keep the parens — Mul binds tighter than Add.
        let e = portrait_syntax::parse_expr("(a + b) * c").unwrap();
        assert_eq!(emit_expr(&e, &fields), "(a + b) * c");

        // a + b * c must NOT gain spurious parens — already correctly grouped.
        let e = portrait_syntax::parse_expr("a + b * c").unwrap();
        assert_eq!(emit_expr(&e, &fields), "a + b * c");

        // a - (b - c): right child is same-precedence under a left-assoc op, so
        // it must be parenthesized to preserve the authored grouping.
        let e = portrait_syntax::parse_expr("a - (b - c)").unwrap();
        assert_eq!(emit_expr(&e, &fields), "a - (b - c)");

        // a - b - c: left-assoc chain, parses as (a - b) - c; the left child is
        // same precedence but on the left, so NO parens needed.
        let e = portrait_syntax::parse_expr("a - b - c").unwrap();
        assert_eq!(emit_expr(&e, &fields), "a - b - c");

        // The exact reported repro must round-trip identically.
        let e = portrait_syntax::parse_expr("collateral >= (debt + amount) * min_ratio").unwrap();
        assert_eq!(
            emit_expr(&e, &fields),
            "collateral >= (debt + amount) * min_ratio"
        );

        // A comparison of arithmetic: comparison binds looser than +, so the
        // arithmetic children never need parens.
        let e = portrait_syntax::parse_expr("a + b >= c + d").unwrap();
        assert_eq!(emit_expr(&e, &fields), "a + b >= c + d");
    }

    #[test]
    fn emit_expr_preserves_parens_around_unary_operand() {
        // Regression (same family as the Binary precedence bug): a unary operator
        // binds tighter than every binary operator, so a `Binary` operand of a
        // `Unary` was only reachable via authored parentheses. Emitting it bare
        // (`-a + b`, `!a && b`) silently regroups it to `(-a) + b` / `(!a) && b`.
        let fields: HashSet<&str> = HashSet::new();

        // -(a + b) must keep its parens — else it re-parses as (-a) + b.
        let e = portrait_syntax::parse_expr("-(a + b)").unwrap();
        assert_eq!(emit_expr(&e, &fields), "-(a + b)");

        // !(a && b) must keep its parens — else it re-parses as (!a) && b.
        let e = portrait_syntax::parse_expr("!(a && b)").unwrap();
        assert_eq!(emit_expr(&e, &fields), "!(a && b)");

        // A non-Binary unary operand must NOT gain spurious parens.
        let e = portrait_syntax::parse_expr("-a").unwrap();
        assert_eq!(emit_expr(&e, &fields), "-a");
        let e = portrait_syntax::parse_expr("!flag").unwrap();
        assert_eq!(emit_expr(&e, &fields), "!flag");
    }

    #[test]
    fn emit_lowers_body_require_checksig_guard() {
        // Working-path guarantee: a body `requires checkSig(auth, owner)` clause
        // (parsed to Stmt::Require) MUST lower to a silverscript `require(...)`.
        // This is the path SimpleEscrow/OwnableCounter use; without it the
        // emitted covenant would carry state forward but enforce no authorization.
        let model = CovenantModel {
            name: "Guarded".into(),
            params: vec![("owner".into(), Type::PubKey)],
            state: vec![("owner".into(), Type::PubKey)],
            transitions: vec![Transition {
                entry: "act".into(),
                from: "live".into(),
                to: Some("live".into()),
                mode: Mode::Transition,
                guards: vec![],
                capability: None,
                args: vec![("auth".into(), Type::Sig)],
                body: vec![
                    Stmt::Require(portrait_syntax::parse_expr("checkSig(auth, owner)").unwrap()),
                    Stmt::Return(
                        portrait_syntax::parse_return_expr("Guarded { owner: owner }").unwrap(),
                    ),
                ],
            }],
            has_vprog: false,
        };
        let files = emit(&[model]).expect("emit should succeed for a Require guard");
        let src = &files[0].source;
        assert!(
            src.contains("require(checkSig(auth, prev_states[0].owner));"),
            "body Require guard must lower to require(checkSig(...)): {}",
            src
        );
    }

    #[test]
    fn emit_fails_loud_on_raw_guard_statement() {
        // Soundness/honesty hazard: an unrecognised guard form (e.g. the `@` age
        // syntax) parses to Stmt::Raw and was previously SILENTLY DROPPED at emit,
        // producing a covenant that LOOKS gated but enforces nothing. Emit must
        // instead fail loud, naming the offending raw statement.
        let model = CovenantModel {
            name: "FakeGated".into(),
            params: vec![],
            state: vec![("v".into(), Type::Int)],
            transitions: vec![Transition {
                entry: "f".into(),
                from: "live".into(),
                to: Some("live".into()),
                mode: Mode::Transition,
                guards: vec![],
                capability: None,
                args: vec![],
                body: vec![
                    Stmt::Raw("requires v @ 1".into()),
                    Stmt::Return(portrait_syntax::parse_return_expr("v + 1").unwrap()),
                ],
            }],
            has_vprog: false,
        };
        let err = emit(&[model]).expect_err("emit must reject a Raw guard, not drop it");
        assert!(
            err.contains("v @ 1") && err.contains("FakeGated"),
            "error must name the offending raw guard and contract: {}",
            err
        );
    }

    #[test]
    fn emit_multi_field_transition_compiles_to_one_field_per_state() {
        // The emitted return must list each state field exactly once, with values
        // lowered, and must NOT nest the object literal inside a field value.
        let model = CovenantModel {
            name: "Lineage".into(),
            params: vec![("seq".into(), Type::Int), ("subject".into(), Type::Bytes32)],
            state: vec![("seq".into(), Type::Int), ("subject".into(), Type::Bytes32)],
            transitions: vec![Transition {
                entry: "attest".into(),
                from: "live".into(),
                to: Some("live".into()),
                mode: Mode::Transition,
                guards: vec![],
                capability: None,
                args: vec![("next_subject".into(), Type::Bytes32)],
                body: vec![Stmt::Return(
                    portrait_syntax::parse_return_expr(
                        "Lineage { seq: seq + 1, subject: next_subject }",
                    )
                    .unwrap(),
                )],
            }],
            has_vprog: false,
        };
        let files = emit(&[model]).expect("emit");
        let src = &files[0].source;
        assert!(
            src.contains("return({ seq: prev_states[0].seq + 1, subject: next_subject });"),
            "expected flat one-field-per-state return: {}",
            src
        );
        assert!(
            !src.contains("seq: Lineage {"),
            "must not nest the object literal in a field value: {}",
            src
        );
    }

    // =====================================================================
    // PROPERTY HARNESS (a) — PRECEDENCE / PAREN FAITHFULNESS
    //
    // The decisive automated answer to "how do you know the emitter is
    // faithful?". The three hand-fixed emitter-drift bugs (Binary precedence
    // regrouping; Unary-operand regrouping; — all in the PRIVATE `emit_expr`
    // below) belong to one class: the emitter erases a grouping the parser will
    // not re-derive. The general invariant that closes the entire class is a
    // round-trip:
    //
    //     parse_expr(emit_expr(e)) == e        for every well-typed Expr `e`.
    //
    // portrait-syntax's own parser uses the SAME Pratt precedence/associativity
    // as silverc (Mul=9, Add/Sub=7, cmp=5, And=3, Or=1, all left-assoc). The AST
    // has NO Paren node — authored parens vanish at parse — so a faithful emitter
    // must re-insert exactly the parens needed for the flat string to re-parse to
    // the SAME tree. If `emit_expr` drops a needed paren, the re-parse regroups
    // (e.g. `(a + b) * c` -> `a + b * c`) and the structural `==` FAILS.
    //
    // The generator below produces WELL-TYPED `Expr` ASTs DIRECTLY (never via a
    // string), so a parser bug cannot smuggle itself into the input. It is a
    // hand-rolled, depth-bounded, SEEDED (LCG) recursive builder — fully
    // deterministic (no proptest/quickcheck; the portrait workspace is
    // deliberately near-zero-dependency), so a failure reprints the exact seed +
    // AST and re-runs identically. It freely nests mixed-precedence Binary
    // children on BOTH sides and Binary operands under Unary — exactly the shapes
    // the three fixed bugs lived in.
    // =====================================================================

    /// Minimal deterministic LCG (Numerical Recipes constants). Seeded; no deps.
    struct Lcg(u64);
    impl Lcg {
        fn new(seed: u64) -> Self {
            // Avoid a degenerate all-zero state.
            Lcg(seed.wrapping_mul(6364136223846793005).wrapping_add(1))
        }
        fn next_u32(&mut self) -> u32 {
            self.0 = self
                .0
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            (self.0 >> 32) as u32
        }
        /// Uniform in `[0, n)` for small `n`.
        fn below(&mut self, n: u32) -> u32 {
            self.next_u32() % n
        }
        fn choice<'a, T>(&mut self, xs: &'a [T]) -> &'a T {
            &xs[self.below(xs.len() as u32) as usize]
        }
    }

    /// The two value types the generator builds over. Comparisons consume `Int`
    /// and produce `Bool`, which keeps every generated tree well-typed.
    #[derive(Clone, Copy)]
    enum GenTy {
        Int,
        Bool,
    }

    /// Identifier pool. SOME of these are state fields (so the state-field
    /// lowering branch of `emit_expr` is exercised), some are plain params/args.
    /// The property uses an EMPTY field set so the round-trip is a pure
    /// precedence check; the lowering branch is exercised separately below.
    const INT_IDENTS: &[&str] = &["value", "delta", "seq", "amount", "limit", "x", "y"];
    const BOOL_IDENTS: &[&str] = &["flag", "allowed", "ok"];

    /// Build a well-typed `Expr` of the requested type, bounded by `depth`.
    fn gen_expr(rng: &mut Lcg, ty: GenTy, depth: u32) -> Expr {
        use portrait_syntax::{BinOp, UnOp};
        if depth == 0 {
            // Leaf.
            return match ty {
                GenTy::Int => {
                    if rng.below(2) == 0 {
                        // NON-NEGATIVE literals only: a literal `Int(-1)` and a
                        // `Unary{Neg, Int(1)}` render to the SAME string `-1`, so
                        // the parser cannot recover which one was authored — that
                        // is a generator ambiguity, not an emitter defect.
                        // Negation is already covered by the `Unary{Neg, ..}` arm.
                        Expr::Int(rng.below(20) as i64)
                    } else {
                        Expr::Var((*rng.choice(INT_IDENTS)).to_string())
                    }
                }
                GenTy::Bool => {
                    if rng.below(2) == 0 {
                        Expr::Bool(rng.below(2) == 0)
                    } else {
                        Expr::Var((*rng.choice(BOOL_IDENTS)).to_string())
                    }
                }
            };
        }
        match ty {
            GenTy::Int => {
                // Int recursive forms: binary arithmetic + unary negate.
                match rng.below(4) {
                    0 => {
                        let op = *rng.choice(&[BinOp::Add, BinOp::Sub, BinOp::Mul]);
                        Expr::Binary {
                            op,
                            lhs: Box::new(gen_expr(rng, GenTy::Int, depth - 1)),
                            rhs: Box::new(gen_expr(rng, GenTy::Int, depth - 1)),
                        }
                    }
                    1 => Expr::Unary {
                        op: UnOp::Neg,
                        rhs: Box::new(gen_expr(rng, GenTy::Int, depth - 1)),
                    },
                    // Bias toward more binary nesting (the precedence-heavy shape).
                    _ => {
                        let op = *rng.choice(&[BinOp::Add, BinOp::Sub, BinOp::Mul]);
                        Expr::Binary {
                            op,
                            lhs: Box::new(gen_expr(rng, GenTy::Int, depth - 1)),
                            rhs: Box::new(gen_expr(rng, GenTy::Int, depth - 1)),
                        }
                    }
                }
            }
            GenTy::Bool => {
                // Bool recursive forms: logical binary, comparison of Ints, unary not.
                match rng.below(4) {
                    0 => {
                        let op = *rng.choice(&[BinOp::And, BinOp::Or]);
                        Expr::Binary {
                            op,
                            lhs: Box::new(gen_expr(rng, GenTy::Bool, depth - 1)),
                            rhs: Box::new(gen_expr(rng, GenTy::Bool, depth - 1)),
                        }
                    }
                    1 => Expr::Unary {
                        op: UnOp::Not,
                        rhs: Box::new(gen_expr(rng, GenTy::Bool, depth - 1)),
                    },
                    // Comparisons consume Int, produce Bool — these mix the two
                    // sub-grammars and exercise comparison precedence (=5).
                    _ => {
                        let op = *rng.choice(&[
                            BinOp::Eq,
                            BinOp::Ne,
                            BinOp::Ge,
                            BinOp::Le,
                            BinOp::Gt,
                            BinOp::Lt,
                        ]);
                        Expr::Binary {
                            op,
                            lhs: Box::new(gen_expr(rng, GenTy::Int, depth - 1)),
                            rhs: Box::new(gen_expr(rng, GenTy::Int, depth - 1)),
                        }
                    }
                }
            }
        }
    }

    /// Number of generated cases per (type, seed) — kept hermetic + fast.
    const GEN_SEEDS: u64 = 400;
    const GEN_DEPTH: u32 = 5;

    #[test]
    fn property_a_emit_expr_roundtrips_modulo_parens() {
        // THE key property. For hundreds of generated well-typed Exprs:
        //   parse_expr(emit_expr(e)) == e.
        // An EMPTY field set makes this a pure precedence/paren faithfulness
        // check (no Var is rewritten), so any failure is a grouping defect.
        let fields: HashSet<&str> = HashSet::new();
        let mut checked = 0u64;
        for seed in 0..GEN_SEEDS {
            // Alternate the top-level type so both sub-grammars are rooted.
            let ty = if seed % 2 == 0 {
                GenTy::Int
            } else {
                GenTy::Bool
            };
            let mut rng = Lcg::new(seed);
            let e = gen_expr(&mut rng, ty, GEN_DEPTH);
            let rendered = emit_expr(&e, &fields);
            let reparsed = portrait_syntax::parse_expr(&rendered).unwrap_or_else(|err| {
                panic!(
                    "seed {seed}: emitted expr did not re-parse.\n  rendered: {rendered}\n  ast: {e:?}\n  err: {err}"
                )
            });
            assert_eq!(
                reparsed, e,
                "seed {seed}: ROUND-TRIP FAIL — emit_expr dropped/added a grouping.\n  \
                 rendered: {rendered}\n  original: {e:?}\n  reparsed: {reparsed:?}"
            );
            checked += 1;
        }
        assert_eq!(checked, GEN_SEEDS, "all generated cases must be checked");
    }

    #[test]
    fn property_a_also_holds_with_state_field_lowering() {
        // Same round-trip, but now a NON-EMPTY field set so the state-field
        // lowering branch (`Var(name)` -> `prev_states[0].field`) is exercised.
        // After lowering, the field reads become `Field`/`Index`-free
        // `prev_states[0].name` accessors; re-parsing must STILL recover an
        // equivalent tree (with the lowered Var replaced by its Field form), so
        // we compare the re-parse against a separately-lowered reference tree.
        let fields: HashSet<&str> = ["value", "seq", "amount", "flag", "allowed"]
            .into_iter()
            .collect();
        for seed in 0..GEN_SEEDS {
            let ty = if seed % 2 == 0 {
                GenTy::Int
            } else {
                GenTy::Bool
            };
            let mut rng = Lcg::new(seed.wrapping_add(1_000_000));
            let e = gen_expr(&mut rng, ty, GEN_DEPTH);
            let rendered = emit_expr(&e, &fields);
            let reparsed = portrait_syntax::parse_expr(&rendered).unwrap_or_else(|err| {
                panic!("seed {seed}: lowered expr did not re-parse: {rendered}\n  err: {err}")
            });
            // The reference is `e` with each state-field Var rewritten to the
            // `prev_states[0].field` AST shape the emitter produces — i.e. the
            // round-trip must be the IDENTITY on the lowered tree.
            let expected = lower_field_vars(&e, &fields);
            assert_eq!(
                reparsed, expected,
                "seed {seed}: lowered round-trip FAIL.\n  rendered: {rendered}\n  \
                 expected: {expected:?}\n  reparsed: {reparsed:?}"
            );
        }
    }

    /// Reference lowering: rewrite each state-field `Var(name)` to the
    /// `prev_states[0].name` `Field`-over-`Index` AST the emitter renders, so the
    /// round-trip can be checked as an exact identity on the lowered tree.
    fn lower_field_vars(e: &Expr, fields: &HashSet<&str>) -> Expr {
        match e {
            Expr::Var(name) if fields.contains(name.as_str()) => Expr::Field {
                base: Box::new(Expr::Index {
                    base: Box::new(Expr::Var("prev_states".into())),
                    index: Box::new(Expr::Int(0)),
                }),
                field: name.clone(),
            },
            Expr::Var(_) | Expr::Int(_) | Expr::Bool(_) | Expr::Bytes(_) => e.clone(),
            Expr::Field { base, field } => Expr::Field {
                base: Box::new(lower_field_vars(base, fields)),
                field: field.clone(),
            },
            Expr::Index { base, index } => Expr::Index {
                base: Box::new(lower_field_vars(base, fields)),
                index: Box::new(lower_field_vars(index, fields)),
            },
            Expr::Unary { op, rhs } => Expr::Unary {
                op: *op,
                rhs: Box::new(lower_field_vars(rhs, fields)),
            },
            Expr::Binary { op, lhs, rhs } => Expr::Binary {
                op: *op,
                lhs: Box::new(lower_field_vars(lhs, fields)),
                rhs: Box::new(lower_field_vars(rhs, fields)),
            },
            Expr::Call { name, args } => Expr::Call {
                name: name.clone(),
                args: args.iter().map(|a| lower_field_vars(a, fields)).collect(),
            },
        }
    }

    // =====================================================================
    // NON-VACUITY — proof the property (a) harness has TEETH.
    //
    // If property (a) passed for a no-op or a broken emitter it would be
    // worthless. The OLD buggy emitter rendered Binary BARE (`{lhs} {op} {rhs}`,
    // no precedence parens) and Unary bare — which is EXACTLY what
    // `Expr::to_silverscript` (portrait-syntax) STILL does today. So we do not
    // need to resurrect the bug: we run property (a)'s round-trip with
    // `to_silverscript` substituted for `emit_expr`, over fixed adversarial trees
    // the generator is guaranteed to produce, and assert the property is
    // VIOLATED for at least one. This proves the harness distinguishes the FIXED
    // emitter from the buggy renderer.
    // =====================================================================

    #[test]
    fn non_vacuity_property_a_rejects_paren_dropping_renderer() {
        // Adversarial trees: each has an authored grouping a bare renderer drops.
        let adversarial = [
            "(a + b) * c", // Mul under Add — left child needs parens
            "a - (b - c)", // same-prec right child under left-assoc Sub
            "-(a + b)",    // Binary operand under Unary Neg
            "!(a && b)",   // Binary operand under Unary Not
        ];
        let mut violations = 0;
        for src in adversarial {
            let e = portrait_syntax::parse_expr(src).expect("adversarial src parses");
            // BUGGY renderer: bare, no precedence parens (== the old emitter).
            let buggy = e.to_silverscript();
            let reparsed = portrait_syntax::parse_expr(&buggy).expect("buggy render re-parses");
            if reparsed != e {
                violations += 1;
            }
            // And the FIXED emitter must PASS the very same round-trip — proving
            // the contrast is real, not an artifact of the trees.
            let fixed = emit_expr(&e, &HashSet::new());
            let fixed_reparsed =
                portrait_syntax::parse_expr(&fixed).expect("fixed render re-parses");
            assert_eq!(
                fixed_reparsed, e,
                "the FIXED emitter must round-trip `{src}` (rendered `{fixed}`)"
            );
        }
        assert!(
            violations > 0,
            "NON-VACUITY FAIL: the property did not reject the paren-dropping \
             renderer on any adversarial tree — it would have no teeth."
        );
    }

    #[test]
    fn non_vacuity_generator_emits_precedence_sensitive_shapes() {
        // Guard against a generator that only emits trivial leaves (which would
        // make property (a) vacuously true). Over the generated corpus, at least
        // one rendered tree must DIFFER from its bare `to_silverscript` form —
        // i.e. the generator actually produces shapes that NEED precedence parens.
        let fields: HashSet<&str> = HashSet::new();
        let mut needed_parens = 0;
        for seed in 0..GEN_SEEDS {
            let ty = if seed % 2 == 0 {
                GenTy::Int
            } else {
                GenTy::Bool
            };
            let mut rng = Lcg::new(seed);
            let e = gen_expr(&mut rng, ty, GEN_DEPTH);
            if emit_expr(&e, &fields) != e.to_silverscript() {
                needed_parens += 1;
            }
        }
        assert!(
            needed_parens > 0,
            "generator never produced a precedence-sensitive shape — property (a) \
             would be vacuous (needed_parens=0 of {GEN_SEEDS})"
        );
    }
}
