//! Atelier — vProg backend for Portrait (BUILD_SPEC §6).
//!
//! Two output modes:
//! - `emit_vprog()` — individual stub functions (one VProgFile per cartoon).
//! - `emit_guest_main()` — a complete, self-contained RISC Zero guest `main.rs`
//!   that implements the 104-byte CSCI journal schema and can be built directly
//!   into `kii-csci-prover/methods/csci-guest/`. M3: the emitted guest computes
//!   the REAL lowered transition — `Return` statements in the Cartoon IR drive
//!   `new_state_hash`, the entrypoint `requires(...)` are lowered into in-guest
//!   `assert!(...)`, and the journal's `new_state_hash`/`seq` are computed over
//!   the NEW state (the `new_<field>` bindings + advanced seq), not the
//!   carried-forward prev state.
//!
//!   Boundary (honest scope): the compiler lowers the STATE-MACHINE transition
//!   that is *written in the Portrait body* — the field updates from the return
//!   expression and the assertable `requires(...)` predicates. Genuinely heavy
//!   off-chain computation that is NOT expressed in the body (folding a private
//!   balance set, opening a Pedersen commitment, Merkle membership) STILL needs
//!   developer code in the guest. On-chain-only builtins (`checkSig`,
//!   `OpInputCovenantId`, `blake2b`) have no guest equivalent here and are
//!   emitted as skipped-with-comment, deferred to the covenant.

use portrait_ir::{Cartoon, RoleGraph};
use portrait_pounce::{allocate, AllocatedTransition, Layer};
use portrait_syntax::{Expr, ReturnExpr, Type};

/// A generated Rust source file for the vProg guest.
#[derive(Debug, Clone)]
pub struct VProgFile {
    pub name: String,
    pub source: String,
}

/// Emit vProg guest stub functions for all VProg-classified transitions.
/// Returns a single file containing all stub functions; empty when no VProg
/// transitions exist.
pub fn emit_vprog(cartoon: &Cartoon) -> Vec<VProgFile> {
    let pounce = allocate(cartoon);
    let vprog_transitions: Vec<&AllocatedTransition<'_>> = pounce
        .allocations
        .iter()
        .filter(|a| a.layer == Layer::VProg)
        .collect();

    if vprog_transitions.is_empty() {
        return vec![];
    }

    let mut src = String::new();
    src.push_str("//! CSCI vProg guest stub — generated by portrait-atelier.\n");
    src.push_str("//! Drop into kii-csci-prover/methods/csci-guest/src/ and wire into main.rs.\n");
    src.push_str("//! Requires: risc0-zkvm (host read_slice / commit_slice) — not standalone.\n\n");
    src.push_str("use risc0_zkvm::guest::env;\n\n");

    for alloc in &vprog_transitions {
        let tr = alloc.transition;
        src.push_str(&format!("/// vProg stub for transition `{}`\n", tr.entry));
        src.push_str(&format!("pub fn verify_{}() {{\n", tr.entry));
        src.push_str("    let prev_value: i64 = env::read();\n");

        for (arg_name, arg_ty) in &tr.args {
            let rust_ty = emit_rust_type(arg_ty);
            src.push_str(&format!(
                "    let {}: {} = env::read();\n",
                arg_name, rust_ty
            ));
        }

        src.push_str("    // TODO: add application-specific invariant checks here.\n");
        src.push_str("    let new_value: i64 = prev_value; // PLACEHOLDER\n");
        for (arg_name, _) in &tr.args {
            src.push_str(&format!("    let _ = {};\n", arg_name));
        }
        src.push_str("    env::commit(&new_value);\n");
        src.push_str("}\n\n");
    }

    vec![VProgFile {
        name: format!("{}_vprog.rs", cartoon.app.to_lowercase().replace(' ', "_")),
        source: src,
    }]
}

/// Emit a complete, self-contained RISC Zero guest `main.rs` implementing the
/// 104-byte CSCI journal schema for ALL VProg transitions in `cartoon`.
///
/// Returns `None` when there are no VProg transitions.
///
/// - Single VProg: emits one `verify_<entry>` function; `main()` calls it directly.
/// - Multiple VProg: emits one `verify_<entry>` per transition; `main()` reads a
///   `transition_id: u32` from the host and dispatches via match.
///
/// Each `verify_<entry>` reads its own args from env internally (after the
/// common protocol header is passed as params), so multi-transition dispatch
/// does not require the caller to know arg layouts in advance.
///
/// `kov_id`: when `Some`, emits `const COV_ID: [u8; 32]` and uses it directly
/// in `main()` instead of reading covenant_id from env. When `None`, covenant_id
/// is read from env at runtime (original behaviour).
///
/// Journal layout (104 bytes):
/// ```text
/// covenant_id[32] || new_state_hash[32] || rule_hash[32] || seq[8 LE]
/// ```
pub fn emit_guest_main(cartoon: &Cartoon, kov_id: Option<[u8; 32]>) -> Option<VProgFile> {
    let pounce = allocate(cartoon);
    let vprog_allocs: Vec<&AllocatedTransition<'_>> = pounce
        .allocations
        .iter()
        .filter(|a| a.layer == Layer::VProg)
        .collect();

    if vprog_allocs.is_empty() {
        return None;
    }

    // All VProg transitions share the same state (from the same role).
    let state_fields = collect_state_fields(cartoon, vprog_allocs[0].transition.from.as_str());
    let app_snake = cartoon.app.to_lowercase().replace(' ', "_");

    let mut src = String::new();

    // ── header ──────────────────────────────────────────────────────────────
    src.push_str("#![no_main]\n");
    src.push_str(&format!(
        "//! CSCI vProg guest for `{}` — generated by portrait-atelier (M3).\n",
        cartoon.app
    ));
    src.push_str(
        "//! new_state_hash is computed over the NEW state derived from the portrait body\n",
    );
    src.push_str("//! Return expression; entrypoint requires(...) are asserted in-guest.\n");
    src.push_str("//! Fields not referenced by the return expr are carried forward unchanged.\n");
    src.push_str(
        "//! Journal: covenant_id[32] || new_state_hash[32] || rule_hash[32] || seq[8 LE]\n",
    );
    src.push_str("risc0_zkvm::guest::entry!(main);\n\n");
    src.push_str("use risc0_zkvm::guest::env;\n");
    src.push_str("use sha2::{Digest, Sha256};\n\n");

    // ── COV_ID const (auto-derived KovId) ───────────────────────────────────
    if let Some(id) = &kov_id {
        src.push_str("/// Auto-derived KovId: sha256(silverc compiled script bytes).\n");
        let bytes_str = id
            .iter()
            .map(|b| format!("0x{:02x}", b))
            .collect::<Vec<_>>()
            .join(", ");
        src.push_str(&format!("const COV_ID: [u8; 32] = [{}];\n\n", bytes_str));
    }

    // ── sha256 helper ────────────────────────────────────────────────────────
    src.push_str("fn sha256_bytes(data: &[u8]) -> [u8; 32] {\n");
    src.push_str("    let mut h = Sha256::new();\n");
    src.push_str("    h.update(data);\n");
    src.push_str("    h.finalize().into()\n");
    src.push_str("}\n\n");

    // ── state encoder ────────────────────────────────────────────────────────
    src.push_str(&format!(
        "fn encode_state({}) -> Vec<u8> {{\n",
        state_fields
            .iter()
            .map(|(n, t)| format!("{}: {}", n, emit_rust_type(t)))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    src.push_str("    let mut out: Vec<u8> = Vec::new();\n");
    for (name, ty) in &state_fields {
        match ty {
            Type::Int => {
                src.push_str(&format!(
                    "    out.extend_from_slice(&{}.to_le_bytes());\n",
                    name
                ));
            }
            Type::Bool => {
                src.push_str(&format!("    out.push({} as u8);\n", name));
            }
            Type::Bytes32 | Type::PubKey => {
                src.push_str(&format!("    out.extend_from_slice(&{});\n", name));
            }
            Type::Sig => {
                src.push_str(&format!("    out.extend_from_slice(&{});\n", name));
            }
            _ => {
                src.push_str(&format!(
                    "    out.extend_from_slice(&({} as i64).to_le_bytes());\n",
                    name
                ));
            }
        }
    }
    src.push_str("    out\n");
    src.push_str("}\n\n");

    // ── verify function(s) — one per VProg transition ───────────────────────
    // Each function receives the protocol header + state as params; reads its
    // own transition-specific args from env internally.
    let common_sig_parts: Vec<String> = std::iter::once("covenant_id: [u8; 32]".to_string())
        .chain(std::iter::once("prev_seq: u64".to_string()))
        .chain(
            state_fields
                .iter()
                .map(|(n, t)| format!("{}: {}", n, emit_rust_type(t))),
        )
        .collect();

    for alloc in &vprog_allocs {
        let tr = alloc.transition;
        let fn_name = tr
            .entry
            .strip_prefix("verify_")
            .unwrap_or(tr.entry.as_str());

        src.push_str(&format!(
            "/// Verify the `{}` VProg transition and return the 104-byte CSCI journal.\n",
            tr.entry
        ));
        src.push_str(&format!(
            "fn verify_{}({}) -> [u8; 104] {{\n",
            fn_name,
            common_sig_parts.join(", ")
        ));

        // Self-documenting preamble: each typed input the guest consumes and the
        // exact journal layout it produces. Params arrive from main() (protocol
        // header + prev state); transition-specific args are read from env below.
        src.push_str(
            "    // ---------------------------------------------------------------------\n",
        );
        src.push_str("    // INPUTS (typed):\n");
        src.push_str(
            "    //   covenant_id: [u8; 32]   — KovId of the covenant this proof binds to\n",
        );
        src.push_str("    //   prev_seq:    u64        — sequence of the prev on-chain state\n");
        for (name, ty) in &state_fields {
            src.push_str(&format!(
                "    //   {}: {}   — prev state field (carried from main env::read)\n",
                name,
                emit_rust_type(ty)
            ));
        }
        for (name, ty) in &tr.args {
            src.push_str(&format!(
                "    //   {}: {}   — transition arg (env::read below)\n",
                name,
                emit_rust_type(ty)
            ));
        }
        src.push_str("    // JOURNAL (104 bytes, committed at the end):\n");
        src.push_str("    //   [0..32)   covenant_id\n");
        src.push_str("    //   [32..64)  new_state_hash = sha256(encode_state(NEW fields))\n");
        src.push_str("    //   [64..96)  rule_hash      = sha256(entry-point name)\n");
        src.push_str("    //   [96..104) seq (u64 LE)   = prev_seq + 1\n");
        src.push_str(
            "    // ---------------------------------------------------------------------\n",
        );

        // Read transition-specific args from env inside the function.
        for (name, ty) in &tr.args {
            src.push_str(&format!(
                "    let {}: {} = env::read();\n",
                name,
                emit_rust_type(ty)
            ));
        }

        // M3: lower body into new-state bindings (typed AST walk, B4).
        let new_bindings = lower_body_for_guest(&tr.body, &state_fields);
        let return_expr: Option<&ReturnExpr> = tr.body.iter().find_map(|s| match s {
            portrait_syntax::Stmt::Return(expr) => Some(expr),
            _ => None,
        });

        // M3: lower the entrypoint `requires(...)` predicates into in-guest
        // assertions. Assertable predicates (comparisons / boolean algebra over
        // args + prev state) become `assert!(...)`, attesting in the proof that
        // they held. On-chain-only builtins with no guest equivalent
        // (checkSig / OpInputCovenantId / blake2b) are emitted as a
        // skipped-with-comment line, deferred to the covenant.
        let require_exprs: Vec<&Expr> = tr
            .body
            .iter()
            .filter_map(|s| match s {
                portrait_syntax::Stmt::Require(e) => Some(e),
                _ => None,
            })
            .collect();
        for req in &require_exprs {
            if expr_is_onchain_only(req) {
                src.push_str(&format!(
                    "    // require({}) — on-chain-only builtin, asserted by the covenant, \
                     not the guest.\n",
                    emit_guest_expr(req)
                ));
            } else {
                src.push_str(&format!(
                    "    assert!({}, \"require failed: {}\");\n",
                    emit_guest_expr(req),
                    emit_guest_expr(req)
                ));
            }
        }

        // ── DEVELOPER PREDICATE HOOK ─────────────────────────────────────────
        // The lowered transition above (field updates + assertable requires) is
        // what the COMPILER can derive from the Portrait body. The genuinely
        // heavy claim — folding a private balance set, opening a Pedersen
        // commitment, Merkle membership, a policy circuit — is NOT expressible in
        // the Portrait body and MUST be authored here, by the developer, over the
        // typed transition inputs. The stub returns `true` (a TODO): until it is
        // filled in, the guest proves ONLY the lowered transition, not the heavy
        // claim. The `assert!` below wires the predicate into the proof so that
        // once authored it gates journal emission.
        let predicate_params: Vec<String> = state_fields
            .iter()
            .map(|(n, t)| format!("{}: {}", n, emit_rust_type(t)))
            .chain(
                tr.args
                    .iter()
                    .map(|(n, t)| format!("{}: {}", n, emit_rust_type(t))),
            )
            .collect();
        let predicate_args: Vec<String> = state_fields
            .iter()
            .map(|(n, _)| n.clone())
            .chain(tr.args.iter().map(|(n, _)| n.clone()))
            .collect();
        src.push_str(
            "    // ===== DEVELOPER PREDICATE HOOK \
             (author the heavy proof logic here) =====\n",
        );
        src.push_str("    #[allow(unused_variables, clippy::too_many_arguments)]\n");
        src.push_str(&format!(
            "    fn predicate({}) -> bool {{\n",
            predicate_params.join(", ")
        ));
        src.push_str(
            "        // TODO: author the heavy off-chain claim over the typed inputs above\n",
        );
        src.push_str(
            "        // (fold / Pedersen open / Merkle membership / policy circuit). \
             Returns true\n",
        );
        src.push_str("        // by default — the guest does NOT yet prove this claim.\n");
        src.push_str("        true\n");
        src.push_str("    }\n");
        src.push_str(&format!(
            "    assert!(predicate({}), \"vprog predicate failed\");\n",
            predicate_args.join(", ")
        ));
        src.push_str("    // ===== END DEVELOPER PREDICATE HOOK =====\n");

        // Suppress args referenced by NEITHER the return expression NOR an
        // asserted require. Reference detection is structural (a bare `Var` in
        // the typed tree). An arg consumed by an assert is genuinely used, so it
        // must not be re-bound as `let _`. (The predicate-hook call passes every
        // arg by value, so no arg is left dangling — the `let _` path below is a
        // belt-and-braces guard only when the hook is later hand-edited away.)
        for (n, _) in &tr.args {
            let used_in_return = return_expr
                .map(|r| return_references_var(r, n))
                .unwrap_or(false);
            let used_in_assert = require_exprs
                .iter()
                .any(|r| !expr_is_onchain_only(r) && expr_references_var(r, n));
            let used_in_predicate = predicate_args.iter().any(|a| a == n);
            if !used_in_return && !used_in_assert && !used_in_predicate {
                src.push_str(&format!("    let _ = {}; // unused arg\n", n));
            }
        }

        if state_fields.is_empty() {
            src.push_str("    let new_state_bytes: Vec<u8> = vec![];\n");
        } else {
            for (field_name, new_expr) in &new_bindings {
                if new_expr != field_name {
                    src.push_str(&format!("    let new_{} = {};\n", field_name, new_expr));
                }
            }
            let encode_args: Vec<String> = new_bindings
                .iter()
                .map(|(field, new_expr)| {
                    if new_expr == field {
                        field.clone()
                    } else {
                        format!("new_{}", field)
                    }
                })
                .collect();
            src.push_str(&format!(
                "    let new_state_bytes = encode_state({});\n",
                encode_args.join(", ")
            ));
        }

        // The journal digest is named `journal_state_hash` (not `new_state_hash`)
        // to avoid colliding with a `new_<field>` binding when a state field is
        // literally named `state_hash` (the M3 return body would emit
        // `let new_state_hash = ...` for that field). Likewise the trailing CSCI
        // sequence is `journal_seq`, not `new_seq`, for a field named `seq`.
        src.push_str("    let journal_state_hash = sha256_bytes(&new_state_bytes);\n");
        src.push_str(&format!(
            "    let rule_hash = sha256_bytes(b\"{}\"); // rule = entry point name\n",
            tr.entry
        ));
        src.push_str("    let journal_seq = prev_seq.checked_add(1).expect(\"seq overflow\");\n\n");
        src.push_str("    let mut journal = [0u8; 104];\n");
        src.push_str("    journal[..32].copy_from_slice(&covenant_id);\n");
        src.push_str("    journal[32..64].copy_from_slice(&journal_state_hash);\n");
        src.push_str("    journal[64..96].copy_from_slice(&rule_hash);\n");
        src.push_str("    journal[96..].copy_from_slice(&journal_seq.to_le_bytes());\n");
        src.push_str("    journal\n");
        src.push_str("}\n\n");
    }

    // ── main ─────────────────────────────────────────────────────────────────
    src.push_str("fn main() {\n");
    if kov_id.is_some() {
        src.push_str("    let covenant_id = COV_ID; // auto-derived KovId\n");
    } else {
        src.push_str("    let covenant_id: [u8; 32] = env::read();\n");
    }
    src.push_str("    let prev_seq: u64 = env::read();\n");
    for (name, ty) in &state_fields {
        src.push_str(&format!(
            "    let {}: {} = env::read();\n",
            name,
            emit_rust_type(ty)
        ));
    }

    let common_call_args: Vec<String> = std::iter::once("covenant_id".to_string())
        .chain(std::iter::once("prev_seq".to_string()))
        .chain(state_fields.iter().map(|(n, _)| n.clone()))
        .collect();

    if vprog_allocs.len() == 1 {
        // Single VProg: direct call — no dispatch overhead.
        let first = vprog_allocs[0].transition;
        let fn_name = first
            .entry
            .strip_prefix("verify_")
            .unwrap_or(first.entry.as_str());
        src.push_str(&format!(
            "    let journal = verify_{}({});\n",
            fn_name,
            common_call_args.join(", ")
        ));
    } else {
        // Multiple VProg transitions: dispatch table.
        // Host writes transition_id: u32 to select which entrypoint runs.
        src.push_str("    let transition_id: u32 = env::read();\n");
        src.push_str("    let journal = match transition_id {\n");
        for (i, alloc) in vprog_allocs.iter().enumerate() {
            let fn_name = alloc
                .transition
                .entry
                .strip_prefix("verify_")
                .unwrap_or(alloc.transition.entry.as_str());
            src.push_str(&format!(
                "        {} => verify_{}({}),\n",
                i,
                fn_name,
                common_call_args.join(", ")
            ));
        }
        src.push_str("        id => panic!(\"unknown transition id: {}\", id),\n");
        src.push_str("    };\n");
    }

    src.push_str("    env::commit_slice(&journal);\n");
    src.push_str("}\n");

    Some(VProgFile {
        name: format!("{}_guest_main.rs", app_snake),
        source: src,
    })
}

/// Collect state fields for the role that owns the given state label.
/// Falls back to the first role's first state if the label is not found.
fn collect_state_fields(cartoon: &Cartoon, state_label: &str) -> Vec<(String, Type)> {
    // Try to find a role whose states include `state_label`.
    let role: Option<&RoleGraph> = cartoon
        .roles
        .iter()
        .find(|r| r.states.iter().any(|s| s.label == state_label));
    let role = role.or_else(|| cartoon.roles.first());
    role.and_then(|r| r.states.first())
        .map(|s| s.fields.clone())
        .unwrap_or_default()
}

/// Lower Cartoon IR body statements into `(field_name, rust_expr)` bindings by
/// walking the typed `ReturnExpr`/`Expr` tree (B4 — no string substitution).
///
/// For each state field:
/// - Scalar return that references the field → new_expr is the return expression
///   rendered as guest Rust (state field variable names are in scope as Rust
///   locals, so `balance - amount` is valid Rust). Fields the scalar does not
///   reference carry forward unchanged.
/// - Object return → each `(field, value)` pair drives that field's new_expr
///   (rendered as guest Rust); fields with no pair carry forward unchanged.
/// - No `Return` statement → all fields carry forward (M1 behaviour).
///
/// Field detection is structural: only a bare `Var(field)` in the typed tree
/// counts as a reference, so prefix collisions (`bal` vs `balance`) are
/// impossible by construction.
fn lower_body_for_guest(
    body: &[portrait_syntax::Stmt],
    state_fields: &[(String, portrait_syntax::Type)],
) -> Vec<(String, String)> {
    let return_expr: Option<&ReturnExpr> = body.iter().find_map(|s| match s {
        portrait_syntax::Stmt::Return(expr) => Some(expr),
        _ => None,
    });
    state_fields
        .iter()
        .map(|(field_name, _)| {
            let new_expr = match return_expr {
                Some(ReturnExpr::Scalar(expr)) if expr_references_var(expr, field_name) => {
                    emit_guest_expr(expr)
                }
                Some(ReturnExpr::Object { fields, .. }) => fields
                    .iter()
                    .find(|(k, _)| k == field_name)
                    .map(|(_, v)| emit_guest_expr(v))
                    .unwrap_or_else(|| field_name.clone()),
                _ => field_name.clone(),
            };
            (field_name.clone(), new_expr)
        })
        .collect()
}

/// Render a typed `Expr` as guest Rust source. State field and arg names are bare
/// identifiers (they are in scope as Rust locals in the generated guest), so this
/// is a structural walk with the same operator spelling as the silverscript
/// surface form — no `prev_states[0]` rewriting (that is an L1-covenant concern,
/// handled by `portrait-emit`).
fn emit_guest_expr(expr: &Expr) -> String {
    match expr {
        Expr::Int(n) => n.to_string(),
        Expr::Bool(b) => b.to_string(),
        Expr::Bytes(bytes) => {
            let hex: String = bytes.iter().map(|b| format!("{b:02x}")).collect();
            format!("0x{hex}")
        }
        Expr::Var(name) => name.clone(),
        Expr::Field { base, field } => format!("{}.{}", emit_guest_expr(base), field),
        Expr::Index { base, index } => {
            format!("{}[{}]", emit_guest_expr(base), emit_guest_expr(index))
        }
        Expr::Unary { op, rhs } => format!("{}{}", op.as_str(), emit_guest_expr(rhs)),
        Expr::Binary { op, lhs, rhs } => format!(
            "{} {} {}",
            emit_guest_expr(lhs),
            op.as_str(),
            emit_guest_expr(rhs)
        ),
        Expr::Call { name, args } => {
            let rendered: Vec<String> = args.iter().map(emit_guest_expr).collect();
            format!("{}({})", name, rendered.join(", "))
        }
    }
}

/// On-chain-only builtins that have NO faithful guest equivalent in this M3
/// lowering. A `require(...)` whose expression invokes one of these is enforced
/// by the covenant (silverscript), not asserted in the guest — emitting a guest
/// `assert!` over them would be dishonest (the guest has no signature context,
/// no input-covenant-id, etc.). blake2b is on this list because the engine
/// hashing op is not the guest's sha2 — mapping it would silently change the
/// hash. Detection is structural: any `Call` to one of these names (anywhere in
/// the expression tree) marks the whole predicate on-chain-only.
fn expr_is_onchain_only(expr: &Expr) -> bool {
    const ONCHAIN_ONLY: &[&str] = &[
        "checkSig",
        "checkMultiSig",
        "OpInputCovenantId",
        "OpOutputCovenantId",
        "blake2b",
        "OpCheckLockTimeVerify",
        "OpCheckSequenceVerify",
    ];
    match expr {
        Expr::Call { name, args } => {
            ONCHAIN_ONLY.contains(&name.as_str()) || args.iter().any(expr_is_onchain_only)
        }
        Expr::Int(_) | Expr::Bool(_) | Expr::Bytes(_) | Expr::Var(_) => false,
        Expr::Field { base, .. } => expr_is_onchain_only(base),
        Expr::Index { base, index } => expr_is_onchain_only(base) || expr_is_onchain_only(index),
        Expr::Unary { rhs, .. } => expr_is_onchain_only(rhs),
        Expr::Binary { lhs, rhs, .. } => expr_is_onchain_only(lhs) || expr_is_onchain_only(rhs),
    }
}

/// Whether a `ReturnExpr` references the variable `name` anywhere (scalar body or
/// any object-field value). Structural — replaces the old `contains_whole_word`.
fn return_references_var(ret: &ReturnExpr, name: &str) -> bool {
    match ret {
        ReturnExpr::Scalar(e) => expr_references_var(e, name),
        ReturnExpr::Object { fields, .. } => {
            fields.iter().any(|(_, v)| expr_references_var(v, name))
        }
    }
}

/// Whether `expr` references variable `name` as a bare `Var` anywhere.
fn expr_references_var(expr: &Expr, name: &str) -> bool {
    match expr {
        Expr::Var(v) => v == name,
        Expr::Int(_) | Expr::Bool(_) | Expr::Bytes(_) => false,
        Expr::Field { base, .. } => expr_references_var(base, name),
        Expr::Index { base, index } => {
            expr_references_var(base, name) || expr_references_var(index, name)
        }
        Expr::Unary { rhs, .. } => expr_references_var(rhs, name),
        Expr::Binary { lhs, rhs, .. } => {
            expr_references_var(lhs, name) || expr_references_var(rhs, name)
        }
        Expr::Call { args, .. } => args.iter().any(|a| expr_references_var(a, name)),
    }
}

fn emit_rust_type(ty: &Type) -> &'static str {
    match ty {
        Type::Int => "i64",
        Type::Bool => "bool",
        Type::Bytes32 => "[u8; 32]",
        Type::PubKey => "[u8; 32]",
        Type::Sig => "[u8; 64]",
        _ => "i64",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use portrait_ir::{Cartoon, Mode, RoleGraph, StateNode, Transition};

    fn make_cartoon_with_mixed() -> Cartoon {
        Cartoon {
            app: "TestApp".into(),
            roles: vec![RoleGraph {
                role: "R".into(),
                params: vec![],
                states: vec![StateNode {
                    label: "S0".into(),
                    fields: vec![("balance".into(), Type::Int)],
                }],
                channels: vec![],
                transitions: vec![
                    Transition {
                        entry: "covenant_step".into(),
                        from: "S0".into(),
                        to: Some("S1".into()),
                        mode: Mode::Transition,
                        guards: vec![],
                        capability: None,
                        args: vec![],
                        body: vec![],
                    },
                    Transition {
                        entry: "vprog_check".into(),
                        from: "S0".into(),
                        to: None,
                        mode: Mode::NonCovenant,
                        guards: vec![],
                        capability: None,
                        args: vec![("amount".into(), Type::Int)],
                        body: vec![],
                    },
                ],
            }],
            invariants: vec![],
        }
    }

    #[test]
    fn emit_vprog_skips_covenant_transitions() {
        let cartoon = make_cartoon_with_mixed();
        let files = emit_vprog(&cartoon);
        assert_eq!(files.len(), 1);
        let src = &files[0].source;
        assert!(
            src.contains("verify_vprog_check"),
            "should emit vprog stub: {}",
            src
        );
        assert!(
            !src.contains("verify_covenant_step"),
            "should skip covenant: {}",
            src
        );
    }

    #[test]
    fn emit_vprog_args_in_stub() {
        let cartoon = make_cartoon_with_mixed();
        let files = emit_vprog(&cartoon);
        let src = &files[0].source;
        assert!(
            src.contains("let amount: i64"),
            "should emit arg read: {}",
            src
        );
    }

    #[test]
    fn emit_vprog_empty_when_no_vprog_transitions() {
        let cartoon = Cartoon {
            app: "AllCovenant".into(),
            roles: vec![RoleGraph {
                role: "R".into(),
                params: vec![],
                states: vec![StateNode {
                    label: "S0".into(),
                    fields: vec![],
                }],
                transitions: vec![Transition {
                    entry: "step".into(),
                    from: "S0".into(),
                    to: Some("S1".into()),
                    mode: Mode::Transition,
                    guards: vec![],
                    capability: None,
                    args: vec![],
                    body: vec![],
                }],
                channels: vec![],
            }],
            invariants: vec![],
        };
        let files = emit_vprog(&cartoon);
        assert!(files.is_empty(), "no vProg transitions → no output files");
    }

    #[test]
    fn emit_guest_main_produces_complete_risc_zero_main() {
        let cartoon = make_cartoon_with_mixed();
        let file = emit_guest_main(&cartoon, None).expect("should produce guest main");
        let src = &file.source;
        // Must have RISC Zero guest boilerplate.
        assert!(src.contains("#![no_main]"), "missing no_main: {}", src);
        assert!(
            src.contains("risc0_zkvm::guest::entry!(main)"),
            "missing entry: {}",
            src
        );
        // Must have sha256 helper.
        assert!(src.contains("fn sha256_bytes("), "missing sha256: {}", src);
        // Must have the verify_ function for the VProg transition.
        assert!(
            src.contains("fn verify_vprog_check("),
            "missing verify fn: {}",
            src
        );
        // Must have main().
        assert!(src.contains("fn main()"), "missing main: {}", src);
        // Must read covenant_id and prev_seq.
        assert!(
            src.contains("let covenant_id: [u8; 32]"),
            "missing covenant_id: {}",
            src
        );
        assert!(
            src.contains("let prev_seq: u64"),
            "missing prev_seq: {}",
            src
        );
        // Must commit 104-byte journal.
        assert!(
            src.contains("journal[..32]"),
            "missing journal build: {}",
            src
        );
        assert!(
            src.contains("env::commit_slice(&journal)"),
            "missing commit_slice: {}",
            src
        );
    }

    #[test]
    fn emit_guest_main_none_when_all_covenant() {
        let cartoon = Cartoon {
            app: "AllCovenant".into(),
            roles: vec![RoleGraph {
                role: "R".into(),
                params: vec![],
                states: vec![StateNode {
                    label: "S0".into(),
                    fields: vec![],
                }],
                transitions: vec![Transition {
                    entry: "step".into(),
                    from: "S0".into(),
                    to: Some("S1".into()),
                    mode: Mode::Transition,
                    guards: vec![],
                    capability: None,
                    args: vec![],
                    body: vec![],
                }],
                channels: vec![],
            }],
            invariants: vec![],
        };
        assert!(emit_guest_main(&cartoon, None).is_none());
    }

    #[test]
    fn emit_guest_main_state_fields_read_from_env() {
        let cartoon = make_cartoon_with_mixed();
        let file = emit_guest_main(&cartoon, None).expect("should produce guest main");
        let src = &file.source;
        // balance field from state should be read in main()
        assert!(
            src.contains("let balance: i64"),
            "should read state field: {}",
            src
        );
    }

    fn make_cartoon_with_body() -> Cartoon {
        Cartoon {
            app: "BodyApp".into(),
            roles: vec![RoleGraph {
                role: "R".into(),
                params: vec![],
                states: vec![portrait_ir::StateNode {
                    label: "S0".into(),
                    fields: vec![("balance".into(), Type::Int)],
                }],
                channels: vec![],
                transitions: vec![Transition {
                    entry: "check".into(),
                    from: "S0".into(),
                    to: None,
                    mode: Mode::NonCovenant,
                    guards: vec![],
                    capability: None,
                    args: vec![("amount".into(), Type::Int)],
                    body: vec![portrait_syntax::Stmt::Return(
                        portrait_syntax::parse_return_expr("balance - amount").unwrap(),
                    )],
                }],
            }],
            invariants: vec![],
        }
    }

    #[test]
    fn emit_guest_main_body_lowering_updates_state() {
        let cartoon = make_cartoon_with_body();
        let file = emit_guest_main(&cartoon, None).expect("should produce guest main");
        let src = &file.source;
        // M2: should emit a new_balance binding derived from the return expr
        assert!(
            src.contains("let new_balance = balance - amount"),
            "M2 body lowering: {}",
            src
        );
        // encode_state should use new_balance, not balance
        assert!(
            src.contains("encode_state(new_balance)"),
            "encode_state with new var: {}",
            src
        );
    }

    #[test]
    fn emit_guest_main_unchanged_field_carried_forward() {
        // Two-field state; return expr only references one field.
        let cartoon = Cartoon {
            app: "TwoField".into(),
            roles: vec![RoleGraph {
                role: "R".into(),
                params: vec![],
                states: vec![portrait_ir::StateNode {
                    label: "S0".into(),
                    fields: vec![("balance".into(), Type::Int), ("paused".into(), Type::Bool)],
                }],
                channels: vec![],
                transitions: vec![Transition {
                    entry: "transfer".into(),
                    from: "S0".into(),
                    to: None,
                    mode: Mode::NonCovenant,
                    guards: vec![],
                    capability: None,
                    args: vec![("amount".into(), Type::Int)],
                    body: vec![portrait_syntax::Stmt::Return(
                        portrait_syntax::parse_return_expr("balance - amount").unwrap(),
                    )],
                }],
            }],
            invariants: vec![],
        };
        let file = emit_guest_main(&cartoon, None).expect("guest main");
        let src = &file.source;
        // balance changes
        assert!(
            src.contains("let new_balance = balance - amount"),
            "balance lowered: {}",
            src
        );
        // paused is unchanged — no new_paused binding
        assert!(
            !src.contains("let new_paused"),
            "paused should carry forward: {}",
            src
        );
        // encode_state uses new_balance + paused (original)
        assert!(
            src.contains("encode_state(new_balance, paused)"),
            "encode_state: {}",
            src
        );
    }

    #[test]
    fn emit_guest_main_no_body_carries_forward() {
        // No Return statement → all fields carry forward (M1 behaviour).
        let cartoon = make_cartoon_with_mixed(); // vprog_check has empty body
        let file = emit_guest_main(&cartoon, None).expect("guest main");
        let src = &file.source;
        // No new_ variable should be emitted
        assert!(
            !src.contains("let new_balance"),
            "no new_balance without body: {}",
            src
        );
        // encode_state uses original field
        assert!(
            src.contains("encode_state(balance)"),
            "original encode_state: {}",
            src
        );
    }

    fn make_cartoon_with_two_vprog() -> Cartoon {
        Cartoon {
            app: "MultiApp".into(),
            roles: vec![RoleGraph {
                role: "R".into(),
                params: vec![],
                states: vec![portrait_ir::StateNode {
                    label: "S0".into(),
                    fields: vec![("balance".into(), Type::Int)],
                }],
                channels: vec![],
                transitions: vec![
                    Transition {
                        entry: "check_a".into(),
                        from: "S0".into(),
                        to: None,
                        mode: Mode::NonCovenant,
                        guards: vec![],
                        capability: None,
                        args: vec![("x".into(), Type::Int)],
                        body: vec![],
                    },
                    Transition {
                        entry: "check_b".into(),
                        from: "S0".into(),
                        to: None,
                        mode: Mode::NonCovenant,
                        guards: vec![],
                        capability: None,
                        args: vec![],
                        body: vec![],
                    },
                ],
            }],
            invariants: vec![],
        }
    }

    #[test]
    fn emit_guest_main_multi_vprog_dispatch_table() {
        let cartoon = make_cartoon_with_two_vprog();
        let file = emit_guest_main(&cartoon, None).expect("guest main");
        let src = &file.source;
        assert!(src.contains("fn verify_check_a("), "check_a fn: {}", src);
        assert!(src.contains("fn verify_check_b("), "check_b fn: {}", src);
        assert!(
            src.contains("let transition_id: u32"),
            "transition_id: {}",
            src
        );
        assert!(
            src.contains("match transition_id"),
            "dispatch match: {}",
            src
        );
        assert!(src.contains("0 => verify_check_a("), "arm 0: {}", src);
        assert!(src.contains("1 => verify_check_b("), "arm 1: {}", src);
    }

    #[test]
    fn emit_guest_main_kov_id_const_embedded() {
        let cartoon = make_cartoon_with_body();
        let kov_id: [u8; 32] = [0xab; 32];
        let file = emit_guest_main(&cartoon, Some(kov_id)).expect("guest main");
        let src = &file.source;
        assert!(
            src.contains("const COV_ID: [u8; 32]"),
            "COV_ID const: {}",
            src
        );
        assert!(src.contains("0xab"), "KovId bytes: {}", src);
        assert!(
            src.contains("let covenant_id = COV_ID"),
            "COV_ID used in main: {}",
            src
        );
    }

    #[test]
    fn lower_body_for_guest_prefix_collision_safe() {
        // Field "bal" must NOT match inside field name "balance".
        let state_fields = vec![
            ("bal".to_string(), Type::Int),
            ("balance".to_string(), Type::Int),
        ];
        // Return expr uses "balance" but not "bal" as a standalone identifier.
        let body = vec![portrait_syntax::Stmt::Return(
            portrait_syntax::parse_return_expr("balance - 1").unwrap(),
        )];
        let bindings = lower_body_for_guest(&body, &state_fields);
        // "bal" should carry forward unchanged (not matched by "balance")
        assert_eq!(
            bindings[0],
            ("bal".to_string(), "bal".to_string()),
            "bal must carry forward: {:?}",
            bindings
        );
        // "balance" should be replaced by the return expr
        assert_eq!(
            bindings[1],
            ("balance".to_string(), "balance - 1".to_string()),
            "balance lowered: {:?}",
            bindings
        );
    }

    #[test]
    fn expr_references_var_distinguishes_prefix() {
        let e = portrait_syntax::parse_expr("balance - amount").unwrap();
        assert!(expr_references_var(&e, "balance"));
        assert!(
            !expr_references_var(&e, "bal"),
            "bal must not match inside balance (structural, not substring)"
        );
        assert!(expr_references_var(&e, "amount"));
        let e2 = portrait_syntax::parse_expr("bal + 1").unwrap();
        assert!(expr_references_var(&e2, "bal"));
    }

    #[test]
    fn emit_guest_expr_keeps_field_vars_bare() {
        // Guest lowering does NOT rewrite to prev_states[0] — fields are Rust locals.
        let e = portrait_syntax::parse_expr("balance - amount").unwrap();
        assert_eq!(emit_guest_expr(&e), "balance - amount");
        let e2 = portrait_syntax::parse_expr("checkSig(sig, owner)").unwrap();
        assert_eq!(emit_guest_expr(&e2), "checkSig(sig, owner)");
    }

    // ── M3: real lowered transition ─────────────────────────────────────────

    /// M3 fixture: a CSCI-shaped vProg companion that MIRRORS its covenant
    /// `settle` — an object return that consumes the `next_commitment` arg and
    /// advances `commitment`/`seq`, plus an assertable `require`.
    fn make_cartoon_m3_mirror() -> Cartoon {
        Cartoon {
            app: "Mirror".into(),
            roles: vec![RoleGraph {
                role: "R".into(),
                params: vec![],
                states: vec![portrait_ir::StateNode {
                    label: "S0".into(),
                    fields: vec![
                        ("owner".into(), Type::PubKey),
                        ("commitment".into(), Type::Bytes32),
                        ("seq".into(), Type::Int),
                    ],
                }],
                channels: vec![],
                transitions: vec![Transition {
                    entry: "transfer_rules".into(),
                    from: "S0".into(),
                    to: None,
                    mode: Mode::NonCovenant,
                    guards: vec![],
                    capability: None,
                    args: vec![
                        ("next_commitment".into(), Type::Bytes32),
                        ("batch_count".into(), Type::Int),
                    ],
                    body: vec![
                        portrait_syntax::Stmt::Require(
                            portrait_syntax::parse_expr("batch_count >= 1").unwrap(),
                        ),
                        portrait_syntax::Stmt::Return(
                            portrait_syntax::parse_return_expr(
                                "M { owner: owner, commitment: next_commitment, seq: seq + 1 }",
                            )
                            .unwrap(),
                        ),
                    ],
                }],
            }],
            invariants: vec![],
        }
    }

    #[test]
    fn m3_object_return_uses_arg_and_hashes_new_state() {
        let cartoon = make_cartoon_m3_mirror();
        let file = emit_guest_main(&cartoon, None).expect("guest main");
        let src = &file.source;
        // The used arg `next_commitment` must be CONSUMED (bound into new_commitment),
        // NOT discarded.
        assert!(
            src.contains("let new_commitment = next_commitment;"),
            "next_commitment must be consumed: {}",
            src
        );
        assert!(
            !src.contains("let _ = next_commitment;"),
            "used arg must not be discarded: {}",
            src
        );
        // seq advances via the return body.
        assert!(
            src.contains("let new_seq = seq + 1;"),
            "seq must advance from the body: {}",
            src
        );
        // new_state_hash is over the NEW state: encode_state takes the new bindings.
        assert!(
            src.contains("encode_state(owner, new_commitment, new_seq)"),
            "encode_state must hash the NEW state: {}",
            src
        );
        assert!(
            src.contains("let journal_state_hash = sha256_bytes(&new_state_bytes);"),
            "journal digest over new_state_bytes: {}",
            src
        );
        // The journal seq is named journal_seq to avoid colliding with new_seq.
        assert!(
            src.contains("let journal_seq = prev_seq.checked_add(1)"),
            "journal seq must be prev_seq+1 under a non-colliding name: {}",
            src
        );
        assert!(
            src.contains("journal[96..].copy_from_slice(&journal_seq.to_le_bytes());"),
            "journal trailing seq uses journal_seq: {}",
            src
        );
    }

    #[test]
    fn m3_state_hash_field_name_does_not_collide_with_journal_digest() {
        // Regression: a state field literally named `state_hash` produces a
        // `new_state_hash` binding from the return body. The journal digest must
        // NOT reuse that name (it is `journal_state_hash`), or the field value and
        // the digest collide.
        let cartoon = Cartoon {
            app: "Csci".into(),
            roles: vec![RoleGraph {
                role: "R".into(),
                params: vec![],
                states: vec![portrait_ir::StateNode {
                    label: "S0".into(),
                    fields: vec![
                        ("seq".into(), Type::Int),
                        ("state_hash".into(), Type::Bytes32),
                    ],
                }],
                channels: vec![],
                transitions: vec![Transition {
                    entry: "csci_rules".into(),
                    from: "S0".into(),
                    to: None,
                    mode: Mode::NonCovenant,
                    guards: vec![],
                    capability: None,
                    args: vec![("next_state_hash".into(), Type::Bytes32)],
                    body: vec![portrait_syntax::Stmt::Return(
                        portrait_syntax::parse_return_expr(
                            "Csci { seq: seq + 1, state_hash: next_state_hash }",
                        )
                        .unwrap(),
                    )],
                }],
            }],
            invariants: vec![],
        };
        let file = emit_guest_main(&cartoon, None).expect("guest main");
        let src = &file.source;
        // The field binding (from the body).
        assert!(
            src.contains("let new_state_hash = next_state_hash;"),
            "state_hash field must be bound from the arg: {}",
            src
        );
        // The journal digest is under a NON-colliding name.
        assert!(
            src.contains("let journal_state_hash = sha256_bytes(&new_state_bytes);"),
            "journal digest must not reuse new_state_hash: {}",
            src
        );
        assert!(
            src.contains("journal[32..64].copy_from_slice(&journal_state_hash);"),
            "journal hash slot uses journal_state_hash: {}",
            src
        );
        // The field value (new_state_hash) feeds encode_state, the digest does not.
        assert!(
            src.contains("encode_state(new_seq, new_state_hash)"),
            "encode_state hashes the NEW field values: {}",
            src
        );
    }

    #[test]
    fn m3_assertable_require_lowered_to_assert() {
        let cartoon = make_cartoon_m3_mirror();
        let file = emit_guest_main(&cartoon, None).expect("guest main");
        let src = &file.source;
        // `requires batch_count >= 1` → an in-guest assert!.
        assert!(
            src.contains("assert!(batch_count >= 1"),
            "assertable require must be lowered to assert!: {}",
            src
        );
        // The arg used only by the assert must NOT be discarded.
        assert!(
            !src.contains("let _ = batch_count;"),
            "arg consumed by assert must not be discarded: {}",
            src
        );
    }

    #[test]
    fn m3_onchain_only_require_skipped_with_comment() {
        // A require over `checkSig` has no honest guest equivalent → comment, not assert.
        let cartoon = Cartoon {
            app: "AuthApp".into(),
            roles: vec![RoleGraph {
                role: "R".into(),
                params: vec![],
                states: vec![portrait_ir::StateNode {
                    label: "S0".into(),
                    fields: vec![("seq".into(), Type::Int)],
                }],
                channels: vec![],
                transitions: vec![Transition {
                    entry: "rule".into(),
                    from: "S0".into(),
                    to: None,
                    mode: Mode::NonCovenant,
                    guards: vec![],
                    capability: None,
                    args: vec![("auth".into(), Type::Sig), ("owner".into(), Type::PubKey)],
                    body: vec![
                        portrait_syntax::Stmt::Require(
                            portrait_syntax::parse_expr("checkSig(auth, owner)").unwrap(),
                        ),
                        portrait_syntax::Stmt::Return(
                            portrait_syntax::parse_return_expr("seq + 1").unwrap(),
                        ),
                    ],
                }],
            }],
            invariants: vec![],
        };
        let file = emit_guest_main(&cartoon, None).expect("guest main");
        let src = &file.source;
        assert!(
            !src.contains("assert!(checkSig"),
            "on-chain-only builtin must NOT be asserted in-guest: {}",
            src
        );
        assert!(
            src.contains("on-chain-only builtin, asserted by the covenant"),
            "on-chain-only require must be skipped-with-comment: {}",
            src
        );
    }

    // ── DeeperGuests: explicit developer-predicate hook ─────────────────────

    #[test]
    fn guest_emits_developer_predicate_hook_section() {
        let cartoon = make_cartoon_m3_mirror();
        let file = emit_guest_main(&cartoon, None).expect("guest main");
        let src = &file.source;
        // The clearly-delimited hook section must be present.
        assert!(
            src.contains("===== DEVELOPER PREDICATE HOOK"),
            "predicate hook section marker missing: {}",
            src
        );
        assert!(
            src.contains("===== END DEVELOPER PREDICATE HOOK ====="),
            "predicate hook end marker missing: {}",
            src
        );
        // The predicate stub fn with typed inputs + TODO default-true body.
        assert!(
            src.contains("fn predicate("),
            "predicate stub fn missing: {}",
            src
        );
        assert!(
            src.contains("// TODO: author the heavy off-chain claim"),
            "predicate TODO missing: {}",
            src
        );
        // The assert wiring the predicate into the proof before journal commit.
        assert!(
            src.contains("assert!(predicate("),
            "predicate assert missing: {}",
            src
        );
        assert!(
            src.contains("\"vprog predicate failed\""),
            "predicate failure message missing: {}",
            src
        );
    }

    #[test]
    fn guest_predicate_params_are_typed_transition_inputs() {
        // Predicate signature must carry the typed state fields + transition args.
        let cartoon = make_cartoon_m3_mirror();
        let file = emit_guest_main(&cartoon, None).expect("guest main");
        let src = &file.source;
        // state fields (owner/commitment/seq) and args (next_commitment/batch_count)
        // must appear as typed predicate params.
        assert!(
            src.contains(
                "fn predicate(owner: [u8; 32], commitment: [u8; 32], seq: i64, \
                 next_commitment: [u8; 32], batch_count: i64) -> bool"
            ),
            "predicate must take typed transition inputs: {}",
            src
        );
        // And the assert call passes those same names.
        assert!(
            src.contains("assert!(predicate(owner, commitment, seq, next_commitment, batch_count)"),
            "predicate call must pass the typed inputs: {}",
            src
        );
    }

    #[test]
    fn guest_emits_self_documenting_input_preamble() {
        let cartoon = make_cartoon_m3_mirror();
        let file = emit_guest_main(&cartoon, None).expect("guest main");
        let src = &file.source;
        assert!(
            src.contains("// INPUTS (typed):"),
            "typed input preamble missing: {}",
            src
        );
        assert!(
            src.contains("// JOURNAL (104 bytes, committed at the end):"),
            "journal layout preamble missing: {}",
            src
        );
        // Documents the covenant_id + a transition arg.
        assert!(
            src.contains("covenant_id: [u8; 32]   — KovId"),
            "covenant_id doc line missing: {}",
            src
        );
        assert!(
            src.contains("batch_count: i64   — transition arg"),
            "transition arg doc line missing: {}",
            src
        );
    }

    #[test]
    fn guest_predicate_returns_true_by_default_honest_stub() {
        // Honesty guard: the stub must default to `true` (a TODO), NOT implement
        // the heavy claim. If someone replaces the stub with a real body, this
        // test should be updated deliberately.
        let cartoon = make_cartoon_m3_mirror();
        let file = emit_guest_main(&cartoon, None).expect("guest main");
        let src = &file.source;
        // The body line after the TODO comments is a bare `true`.
        assert!(
            src.contains(
                "        // by default — the guest does NOT yet prove this claim.\n        true\n"
            ),
            "predicate stub must default to true: {}",
            src
        );
    }

    #[test]
    fn expr_is_onchain_only_detects_builtins() {
        let sig = portrait_syntax::parse_expr("checkSig(auth, owner)").unwrap();
        assert!(expr_is_onchain_only(&sig));
        // Nested builtin inside a boolean expression is still on-chain-only.
        let nested = portrait_syntax::parse_expr("checkSig(auth, owner) && seq >= 0").unwrap();
        assert!(expr_is_onchain_only(&nested));
        // A pure arithmetic comparison is assertable (NOT on-chain-only).
        let cmp = portrait_syntax::parse_expr("batch_count >= 1").unwrap();
        assert!(!expr_is_onchain_only(&cmp));
    }
}
