//! Testnet evidence runner for the paired-attestation pattern.
//!
//! Demonstrates a complete two-party mutual attestation on the Kaspa testnet:
//!
//! 1. Party A commits to a shared record under `blind_a` (`PartyACommit`, `seq = 0`).
//! 2. Party B mates: negotiates disclosed blinds, builds and verifies the mate
//!    proof **off-chain**, then anchors `PartyBMate` (`seq = 1`).
//! 3. Both payloads are validated off-chain (`PA-1` through `PA-4`).
//! 4. Both carrier transactions are submitted to the testnet.
//!
//! Produces FACTS.yaml-ready output (`KCP-PA-001`) for the data room.
//!
//! ## Usage
//!
//! ```text
//! KCP_NODE_URL=ws://localhost:17210   \
//! KCP_KEY_FILE=/path/to/wallet.key   \
//! cargo run -p kcp-paired-attestation --example testnet_evidence \
//!            --features wrpc
//! ```
//!
//! Optional:
//!
//! - `KCP_NET_SUFFIX` — testnet numeric suffix (default `10`).
//! - `KCP_TS` — ISO-8601 timestamp to embed in the record (for
//!   reproducibility across runs). Omitted if not set.
//!
//! ## Safety
//!
//! This example **refuses to run unless the node reports a testnet network**.
//! No hardcoded private keys. No faucet automation.
//!
//! ## v0 note
//!
//! Bilateral mating is verified **off-chain** by `verify_mate`. The two-party
//! on-chain datasig binding (two independent `checkDataSig` checks inside one
//! covenant entry-point) is proven viable — FACTS SS-024-v4 — but requires
//! P2SH spend-path plumbing not yet in `kcp-common`. It is the next step.
//!
//! Status: **v0 — unaudited — testnet first.**

use std::env;

use kcp_common::{
    wallet::{Prefix, Wallet},
    wrpc::{NodeClient, NodeConfig},
};
use kcp_paired_attestation::{
    invariants::{validate_chain, PARTY_A_COMMIT, PARTY_B_MATE},
    mate::{build_mate_proof, negotiate_blind},
    payload::Payload,
    record::{attestation_id, commit, AttestationRecord},
    tx::{append_mate_tx, create_attestation_tx, DEFAULT_ATTESTATION_VALUE_SOMPI},
};

type BoxError = Box<dyn std::error::Error>;

#[tokio::main]
async fn main() -> Result<(), BoxError> {
    // ---- read environment ------------------------------------------------
    let node_url = env::var("KCP_NODE_URL").unwrap_or_else(|_| {
        eprintln!("KCP_NODE_URL not set; defaulting to ws://localhost:17210");
        "ws://localhost:17210".to_string()
    });
    let key_file = env::var("KCP_KEY_FILE")
        .map_err(|_| "KCP_KEY_FILE is required — path to a testnet wallet key file")?;
    let ts_field = env::var("KCP_TS").ok();

    // ---- connect ---------------------------------------------------------
    let net_suffix: u32 = env::var("KCP_NET_SUFFIX")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(10);
    let config = NodeConfig::testnet(&node_url, net_suffix);
    let node = NodeClient::new(config);
    let rpc = node.rpc().await?;

    let info = node.server_info().await?;
    println!(
        "connected: server={} network={} synced={} daa={}",
        info.server_version, info.network_id, info.is_synced, info.virtual_daa_score
    );

    // ---- testnet guard ---------------------------------------------------
    if !info.network_id.contains("testnet") {
        return Err(format!(
            "REFUSED: network_id '{}' is not testnet. \
             This example must only run against a testnet node.",
            info.network_id
        )
        .into());
    }

    // ---- load wallet -----------------------------------------------------
    let wallet = Wallet::load(std::path::Path::new(&key_file), 0, Prefix::Testnet)
        .map_err(|e| format!("failed to load wallet: {e}"))?;
    println!("wallet: {}", wallet.address_string());

    // ---- build the shared attestation record ----------------------------
    // In production the subject and terms_hash would be real document hashes.
    // Here we use deterministic values for testnet reproducibility.
    let subject_bytes = [0x01u8; 32];
    let terms_bytes = [0x02u8; 32];
    let nonce: u64 = 1;
    let mut record = AttestationRecord::new(subject_bytes, terms_bytes, nonce);
    if let Some(ts) = ts_field {
        // Embed the timestamp in the record subject for run disambiguation.
        record.subject = format!("kcp-pa-{ts}");
    }

    // attestation_id = SHA-256(canonical_json(record))
    let aid = attestation_id(&record).map_err(|e| format!("attestation_id: {e}"))?;
    println!("attestation_id:   {}", hex::encode(aid));

    // ---- Party A commits -------------------------------------------------
    // In a real two-party protocol, share_a is generated by Party A, shared
    // with Party B, and the combined blind = share_a XOR share_b. In this
    // single-wallet testnet runner, we use deterministic shares.
    let share_a = [0x11u8; 32];
    let share_b = [0x22u8; 32];
    let blind_a = negotiate_blind(share_a, share_b);
    let commit_a = commit(&record, &blind_a).map_err(|e| format!("commit_a: {e}"))?;
    println!("party A commit:   {}", hex::encode(commit_a));

    let payload_a = Payload {
        attestation_id: aid,
        seq: 0,
        event_class: PARTY_A_COMMIT,
        commitment: commit_a,
    }
    .encode();

    println!("\n--- CREATE ATTESTATION (Party A commit, seq=0) ---");
    let create_tx_id =
        create_attestation_tx(&rpc, &wallet, payload_a, DEFAULT_ATTESTATION_VALUE_SOMPI)
            .await
            .map_err(|e| format!("create_attestation_tx: {e}"))?;
    println!("create tx_id:     {create_tx_id}");
    println!("lookup:           tx {create_tx_id} on {}", info.network_id);

    // ---- Party B mates ---------------------------------------------------
    // Party B uses a different blind (share_b only — in this single-wallet
    // demo each party's blind is their own share, not the XOR, to illustrate
    // distinct commitments).
    let blind_b_only = share_b; // Party B's individual blind for this demo.
    let commit_b = commit(&record, &blind_b_only).map_err(|e| format!("commit_b: {e}"))?;
    println!("party B commit:   {}", hex::encode(commit_b));

    // Build and verify the mate proof off-chain before anchoring.
    let mate_proof = build_mate_proof(&record, blind_a, blind_b_only, commit_a, commit_b)
        .map_err(|e| format!("build_mate_proof: {e}"))?;
    kcp_paired_attestation::mate::verify_mate(&mate_proof)
        .map_err(|e| format!("verify_mate: {e}"))?;
    println!("mate proof:       verified off-chain (equality-under-disclosed-blinds)");

    let payload_b = Payload {
        attestation_id: aid,
        seq: 1,
        event_class: PARTY_B_MATE,
        commitment: commit_b,
    }
    .encode();

    // ---- validate chain off-chain before anchoring ----------------------
    let chain = vec![
        Payload {
            attestation_id: aid,
            seq: 0,
            event_class: PARTY_A_COMMIT,
            commitment: commit_a,
        },
        Payload {
            attestation_id: aid,
            seq: 1,
            event_class: PARTY_B_MATE,
            commitment: commit_b,
        },
    ];
    validate_chain(&chain, Some(&mate_proof)).map_err(|e| format!("validate_chain: {e}"))?;
    println!("chain:            validated off-chain (PA-1/PA-2/PA-3/PA-4)");

    // ---- anchor Party B mate on-chain -----------------------------------
    let attestation_txid: kaspa_consensus_core::tx::TransactionId = create_tx_id
        .parse()
        .map_err(|e| format!("failed to parse create tx_id: {e}"))?;
    let attestation_outpoint = (attestation_txid, 0u32);

    println!("\n--- APPEND MATE (Party B, seq=1) ---");
    // The attestation UTXO must be block-included and indexed before it can be
    // spent; poll briefly for confirmation instead of failing on the race.
    let mut mate_tx_id = String::new();
    for attempt in 1..=30u32 {
        match append_mate_tx(&rpc, &wallet, attestation_outpoint, payload_b.clone()).await {
            Ok(id) => {
                mate_tx_id = id;
                break;
            }
            Err(e) if e.to_string().contains("not found") && attempt < 30 => {
                tokio::time::sleep(std::time::Duration::from_secs(2)).await;
            }
            Err(e) => return Err(format!("append_mate_tx: {e}").into()),
        }
    }
    if mate_tx_id.is_empty() {
        return Err("attestation UTXO not confirmed after 60s".into());
    }
    println!("mate tx_id:       {mate_tx_id}");
    println!("lookup:           tx {mate_tx_id} on {}", info.network_id);

    // ---- FACTS.yaml-ready output -----------------------------------------
    let aid_hex = hex::encode(aid);
    println!("\n--- FACTS.yaml-ready ---");
    println!("  id: KCP-PA-001");
    println!(
        "  claim: \"kcp-paired-attestation v0 pattern exercised on {}: \
         attestation_id={aid_hex}, create_tx={create_tx_id}, mate_tx={mate_tx_id}\"",
        info.network_id
    );
    println!("  source: examples/testnet_evidence.rs");
    println!("  verified_at: [FACT-NEEDED: fill in today's date]");
    println!(
        "  note: \"v0 — unaudited — bilateral mating verified OFF-CHAIN; \
         two-party on-chain datasig binding is proven viable (FACTS SS-024-v4) \
         and is the next step (needs P2SH spend plumbing)\""
    );

    Ok(())
}
