//! Composite scaffold generator — produces a compilable Cargo project for a
//! P2SH `All([TimelockHeight, MultiSig])` composite covenant.
//!
//! This is the most realistic custody pattern: k-of-n multisig AND a
//! DAA-height deadline must BOTH be satisfied to spend.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

/// Configuration for a generated composite scaffold.
pub struct CompositeConfig {
    /// DAA height at or after which spending is allowed (CLTV deadline).
    pub deadline: u64,
    /// Number of multisig signatures required (1 ≤ threshold ≤ n).
    pub threshold: u8,
    /// Total number of multisig keys (1 ≤ n ≤ 16).
    pub n: usize,
    /// Directory to write the generated project into.
    pub out_dir: PathBuf,
    /// Absolute path to the kaspa-compliance-patterns workspace root.
    pub workspace_path: PathBuf,
}

/// Generate a composite scaffold project at `cfg.out_dir`.
///
/// Creates `Cargo.toml`, `src/main.rs`, `tests/composite_smoke.rs`, and
/// `README.md`. The generated project compiles with `cargo check` (or
/// `cargo test`) using path deps to the local library workspace.
///
/// Fails if any output file already exists — use a fresh directory.
///
/// **Pre-production, unaudited, testnet-only.**
pub fn generate(cfg: &CompositeConfig) -> anyhow::Result<()> {
    if cfg.deadline == 0 {
        bail!("deadline must be > 0");
    }
    let t = cfg.threshold as usize;
    if cfg.n == 0 {
        bail!("composite scaffold requires at least one multisig key");
    }
    if t == 0 || t > cfg.n {
        bail!("threshold {t} must be >= 1 and <= n ({})", cfg.n);
    }

    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist or is not accessible")?;

    let guard_paths = [
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/composite_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ];
    for p in &guard_paths {
        if p.exists() {
            bail!(
                "output file already exists: {:?}\n\
                 Use a fresh, empty directory to avoid accidental overwrites.",
                p
            );
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create out_dir/src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create out_dir/tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(&cfg.out_dir, cfg.deadline, cfg.threshold, cfg.n)?;
    write_smoke_test(&cfg.out_dir, cfg.deadline, cfg.threshold, cfg.n)?;
    write_readme(&cfg.out_dir, cfg.deadline, cfg.threshold, cfg.n)?;

    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let kcp_common = ws.join("crates/kcp-common");
    let kcp_vault = ws.join("crates/kcp-vault");
    let content = format!(
        r#"[package]
name = "my-composite"
version = "0.1.0"
edition = "2021"
# Generated by `kcp scaffold composite` — pre-production, unaudited, testnet-only.
# kcp-vault is not yet on crates.io. Use --workspace-path until v0.2 publishes.
# Replace path deps with: kcp-vault = {{ version = "0.2" }} once published.
# WARNING: path deps below are absolute paths on the generating machine.
# If you move the kaspa-compliance-patterns workspace, regenerate with kcp scaffold.
publish = false

# Prevents Cargo from merging this project into any parent workspace.
[workspace]

[dependencies]
kcp-common = {{ path = {kcp_common:?}, features = ["wrpc"] }}
kcp-vault   = {{ path = {kcp_vault:?},   features = ["wrpc"] }}
kaspa-consensus-core = {{ git = "https://github.com/kaspanet/rusty-kaspa", tag = "v2.0.0" }}
kaspa-bip32          = {{ git = "https://github.com/kaspanet/rusty-kaspa", tag = "v2.0.0" }}
"#
    );
    std::fs::write(out.join("Cargo.toml"), content).context("write Cargo.toml")?;
    Ok(())
}

fn write_main_rs(out: &Path, deadline: u64, threshold: u8, n: usize) -> anyhow::Result<()> {
    let t = threshold as usize;

    // Multisig keypair declarations: 0xA1, 0xA2, ... 0xA0+n
    let msig_kp_decls: String = (0..n)
        .map(|i| {
            let byte = 0xA0u8 + (i as u8 + 1);
            format!(
                "    let msig_kp{i1} = test_keypair(0x{byte:02X}); // msig key {i1} — replace with real key\n",
                i1 = i + 1,
            )
        })
        .collect();

    let msig_pk_decls: String = (0..n)
        .map(|i| {
            format!(
                "    let msig_pk{i1} = msig_kp{i1}.x_only_public_key().0.serialize();\n",
                i1 = i + 1,
            )
        })
        .collect();

    let msig_pks_vec: String = (0..n)
        .map(|i| format!("msig_pk{}", i + 1))
        .collect::<Vec<_>>()
        .join(", ");

    // Sign with the first `t` multisig keys
    let msig_sig_decls: String = (0..t)
        .map(|i| {
            format!(
                "    let msig_sig{i1} = schnorr_satisfier_sig(&sighash, &msig_kp{i1});\n",
                i1 = i + 1,
            )
        })
        .collect();

    // Satisfier order for All([leaf_0: TimelockHeight, leaf_1: MultiSig]):
    // leaf_0 (CLTV CHECKSIG) runs first, consuming stack TOP → ctrl_sig must be on top.
    // leaf_1 (CHECKMULTISIG) runs second → msig sigs must be below ctrl_sig.
    // Push order: msig sigs first (deepest), ctrl_sig last (top).
    let msig_sigs_list: String = (0..t)
        .map(|i| format!("msig_sig{}", i + 1))
        .collect::<Vec<_>>()
        .join(", ");
    let satisfier_elems = format!("{msig_sigs_list}, ctrl_sig");

    let content = format!(
        r#"//! Generated by `kcp scaffold composite` — pre-production, unaudited, testnet-only.
//!
//! Composite P2SH covenant: `All([TimelockHeight, MultiSig])`.
//! BOTH conditions must be satisfied to spend:
//!   1. DAA height must be >= {deadline} (CLTV).
//!   2. {t}-of-{n} multisig signatures must be valid.
//!
//! Runs entirely offline — no live node, no funds, no network.
//! Uses the real rusty-kaspa v2.0.0 script engine.
//!
//! TODO: replace synthetic test keypairs with real keys before use.
//! See README.md and crates/kcp-vault/README.md for next steps.
//!
//! ## CLTV spend requirements
//!
//! `OP_CHECKLOCKTIMEVERIFY` requires:
//!   1. `tx.lock_time >= deadline` (height-based: lock_time < 500_000_000_000)
//!   2. `input.sequence != 0xffffffffffffffff` (input must not be finalised)
//!
//! ## Satisfier ordering for All([TimelockHeight, MultiSig])
//!
//! The redeem script runs leaf_0 (TimelockHeight) first, consuming the TOP of
//! the stack. So the controller signature must sit on top. The multisig sigs
//! must be pushed first (deepest in stack) so they remain for leaf_1.
//!
//! Push order: `[msig_sig_0, ..., msig_sig_{{t-1}}, ctrl_sig]`

use kaspa_bip32::secp256k1::{{Keypair, SECP256K1}};
use kaspa_consensus_core::{{
    mass::SigopCount,
    subnets::SUBNETWORK_ID_NATIVE,
    tx::{{
        ComputeCommit, ScriptPublicKey, ScriptVec, Transaction, TransactionId,
        TransactionInput, TransactionOutpoint, TransactionOutput, UtxoEntry,
    }},
}};
use kcp_common::{{
    p2sh::{{
        build_p2sh_signature_script, p2sh_input_sighash, p2sh_lock_script,
        p2sh_redeem_sigop_count, schnorr_satisfier_sig, verify_p2sh_spend_offline,
    }},
    tx::CARRIER_FEE_SOMPI,
}};
// IMPORTANT: compile_condition_p2sh, NOT compile_condition.
// Kaspa's OP_CHECKLOCKTIMEVERIFY *pops* the deadline (unlike Bitcoin where
// CLTV peeks). compile_condition emits OP_DROP after CLTV which removes the
// signature instead of the deadline. compile_condition_p2sh omits OP_DROP.
use kcp_vault::{{condition::SpendCondition, onchain::compile_condition_p2sh}};

const LOCK_VALUE_SOMPI: u64 = 200_000_000;

fn test_keypair(byte: u8) -> Keypair {{
    // SYNTHETIC KEY — never use in production. Replace with your real keypair.
    Keypair::from_seckey_slice(SECP256K1, &[byte; 32])
        .expect("32 repeated bytes is a valid secp256k1 secret key")
}}

fn op_true_spk() -> ScriptPublicKey {{
    ScriptPublicKey::new(0, ScriptVec::from_slice(&[0x51]))
}}

fn build_spend_tx(redeem: &[u8], amount: u64, lock_time: u64) -> (Transaction, UtxoEntry) {{
    let p2sh_spk = p2sh_lock_script(redeem);
    let prev = TransactionOutpoint::new(TransactionId::from_slice(&[0xabu8; 32]), 0);
    // sequence = 0: input must NOT be finalised (0xffffffffffffffff) for CLTV to work.
    let input = TransactionInput::new(prev, vec![], 0, 0);
    let output = TransactionOutput::new(amount - CARRIER_FEE_SOMPI, op_true_spk());
    let mut tx = Transaction::new(
        0,
        vec![input],
        vec![output],
        lock_time, // tx.lock_time must be >= the CLTV deadline
        SUBNETWORK_ID_NATIVE,
        0,
        vec![],
    );
    let sigops = p2sh_redeem_sigop_count(redeem);
    let commit: ComputeCommit = SigopCount(sigops).into();
    for inp in tx.inputs.iter_mut() {{
        inp.compute_commit = commit;
    }}
    let entry = UtxoEntry::new(amount, p2sh_spk, 0, false, None);
    (tx, entry)
}}

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    println!(
        "Generated composite — All([TimelockHeight({deadline}), {t}-of-{n} MultiSig]) (offline demo)"
    );

    // [1/6] Build controller keypair (for the TimelockHeight leaf)
    //       TODO: replace with your real controller keypair.
    let ctrl_kp = test_keypair(0xC1);
    let ctrl_xonly = ctrl_kp.x_only_public_key().0.serialize();

    // [2/6] Build multisig keypairs (for the MultiSig leaf)
    //       TODO: replace with your real multisig keypairs.
{msig_kp_decls}
{msig_pk_decls}
    // [3/6] Build the composite SpendCondition and compile to a P2SH redeem script
    let condition = SpendCondition::All {{
        children: vec![
            SpendCondition::TimelockHeight {{
                deadline: {deadline},
                controller_xonly: ctrl_xonly,
            }},
            SpendCondition::MultiSig {{
                threshold: {threshold},
                xonly_keys: vec![{msig_pks_vec}],
            }},
        ],
    }};
    let redeem = compile_condition_p2sh(&condition)?;

    // [4/6] Build synthetic spend tx with lock_time = deadline (satisfies CLTV)
    let (mut tx, entry) = build_spend_tx(&redeem, LOCK_VALUE_SOMPI, {deadline});

    // [5/6] Sign — sighash covers the whole tx
    let sighash = p2sh_input_sighash(&tx, std::slice::from_ref(&entry), 0);
    // Controller sig for the TimelockHeight leaf
    let ctrl_sig = schnorr_satisfier_sig(&sighash, &ctrl_kp);
    // Multisig sigs for the MultiSig leaf — first {t} key(s) in key order
{msig_sig_decls}
    // Satisfier ordering for All([TimelockHeight, MultiSig]):
    // leaf_0 (CLTV CHECKSIG) consumes stack TOP → ctrl_sig must be on top (pushed last).
    // leaf_1 (CHECKMULTISIG) consumes what remains → msig sigs pushed first (deepest).
    tx.inputs[0].signature_script =
        build_p2sh_signature_script(&[{satisfier_elems}], &redeem)?;

    // [6/6] Run through the real rusty-kaspa script engine
    verify_p2sh_spend_offline(&tx, 0, &entry, false)?;
    println!(
        "✓ PASSED — real rusty-kaspa engine accepted the composite spend at height {deadline}"
    );
    Ok(())
}}
"#,
        deadline = deadline,
        threshold = threshold,
        t = t,
        n = n,
        msig_kp_decls = msig_kp_decls,
        msig_pk_decls = msig_pk_decls,
        msig_pks_vec = msig_pks_vec,
        msig_sig_decls = msig_sig_decls,
        satisfier_elems = satisfier_elems,
    );
    std::fs::write(out.join("src/main.rs"), content).context("write src/main.rs")?;
    Ok(())
}

fn write_smoke_test(out: &Path, deadline: u64, threshold: u8, n: usize) -> anyhow::Result<()> {
    let t = threshold as usize;

    let msig_kp_decls: String = (0..n)
        .map(|i| {
            let byte = 0xA0u8 + (i as u8 + 1);
            format!(
                "    let msig_kp{i1} = test_keypair(0x{byte:02X});\n",
                i1 = i + 1,
            )
        })
        .collect();

    let msig_pk_decls: String = (0..n)
        .map(|i| {
            format!(
                "    let msig_pk{i1} = msig_kp{i1}.x_only_public_key().0.serialize();\n",
                i1 = i + 1,
            )
        })
        .collect();

    let msig_pks_vec: String = (0..n)
        .map(|i| format!("msig_pk{}", i + 1))
        .collect::<Vec<_>>()
        .join(", ");

    let msig_sig_decls: String = (0..t)
        .map(|i| {
            format!(
                "    let msig_sig{i1} = schnorr_satisfier_sig(&sighash, &msig_kp{i1});\n",
                i1 = i + 1,
            )
        })
        .collect();

    let msig_sigs_list: String = (0..t)
        .map(|i| format!("msig_sig{}", i + 1))
        .collect::<Vec<_>>()
        .join(", ");
    let satisfier_elems = format!("{msig_sigs_list}, ctrl_sig");

    let content = format!(
        r#"// Generated by `kcp scaffold composite` — pre-production, unaudited, testnet-only.
//
// Run: cargo test --manifest-path <out_dir>/Cargo.toml
// (fetches rusty-kaspa git dep on first run — requires network)

use kaspa_bip32::secp256k1::{{Keypair, SECP256K1}};
use kaspa_consensus_core::{{
    mass::SigopCount,
    subnets::SUBNETWORK_ID_NATIVE,
    tx::{{
        ComputeCommit, ScriptPublicKey, ScriptVec, Transaction, TransactionId,
        TransactionInput, TransactionOutpoint, TransactionOutput, UtxoEntry,
    }},
}};
use kcp_common::{{
    p2sh::{{
        build_p2sh_signature_script, p2sh_input_sighash, p2sh_lock_script,
        p2sh_redeem_sigop_count, schnorr_satisfier_sig, verify_p2sh_spend_offline,
    }},
    tx::CARRIER_FEE_SOMPI,
}};
// IMPORTANT: compile_condition_p2sh — Kaspa CLTV pops the deadline.
// See src/main.rs for the full explanation.
use kcp_vault::{{condition::SpendCondition, onchain::compile_condition_p2sh}};

fn test_keypair(byte: u8) -> Keypair {{
    Keypair::from_seckey_slice(SECP256K1, &[byte; 32]).unwrap()
}}

fn op_true_spk() -> ScriptPublicKey {{
    ScriptPublicKey::new(0, ScriptVec::from_slice(&[0x51]))
}}

fn build_condition(
    ctrl_xonly: [u8; 32],
    msig_pks: Vec<[u8; 32]>,
) -> SpendCondition {{
    SpendCondition::All {{
        children: vec![
            SpendCondition::TimelockHeight {{
                deadline: {deadline},
                controller_xonly: ctrl_xonly,
            }},
            SpendCondition::MultiSig {{
                threshold: {threshold},
                xonly_keys: msig_pks,
            }},
        ],
    }}
}}

fn build_spend_tx(redeem: &[u8], amount: u64, lock_time: u64, sequence: u64) -> (Transaction, UtxoEntry) {{
    let p2sh_spk = p2sh_lock_script(redeem);
    let prev = TransactionOutpoint::new(TransactionId::from_slice(&[0xabu8; 32]), 0);
    let input = TransactionInput::new(prev, vec![], sequence, 0);
    let output = TransactionOutput::new(amount - CARRIER_FEE_SOMPI, op_true_spk());
    let mut tx = Transaction::new(
        0,
        vec![input],
        vec![output],
        lock_time,
        SUBNETWORK_ID_NATIVE,
        0,
        vec![],
    );
    let sigops = p2sh_redeem_sigop_count(redeem);
    let commit: ComputeCommit = SigopCount(sigops).into();
    for inp in tx.inputs.iter_mut() {{
        inp.compute_commit = commit;
    }}
    let entry = UtxoEntry::new(amount, p2sh_spk, 0, false, None);
    (tx, entry)
}}

#[test]
fn composite_all_timelock_multisig_{deadline}_offline_smoke() {{
    let ctrl_kp = test_keypair(0xC1);
    let ctrl_xonly = ctrl_kp.x_only_public_key().0.serialize();

{msig_kp_decls}
{msig_pk_decls}

    let condition = build_condition(ctrl_xonly, vec![{msig_pks_vec}]);
    let redeem = compile_condition_p2sh(&condition).unwrap();

    // sequence = 0: must not be finalised for CLTV to pass.
    let (mut tx, entry) = build_spend_tx(&redeem, 200_000_000, {deadline}, 0);

    let sighash = p2sh_input_sighash(&tx, std::slice::from_ref(&entry), 0);
    let ctrl_sig = schnorr_satisfier_sig(&sighash, &ctrl_kp);
{msig_sig_decls}

    // Satisfier order: msig sigs first (deepest), ctrl_sig last (top).
    tx.inputs[0].signature_script =
        build_p2sh_signature_script(&[{satisfier_elems}], &redeem).unwrap();

    verify_p2sh_spend_offline(&tx, 0, &entry, false)
        .expect("engine must accept composite spend when lock_time >= {deadline} and sigs valid");
}}

#[test]
fn composite_rejected_before_deadline() {{
    // lock_time < deadline must be rejected regardless of valid sigs.
    let ctrl_kp = test_keypair(0xC1);
    let ctrl_xonly = ctrl_kp.x_only_public_key().0.serialize();

{msig_kp_decls}
{msig_pk_decls}

    let condition = build_condition(ctrl_xonly, vec![{msig_pks_vec}]);
    let redeem = compile_condition_p2sh(&condition).unwrap();

    let early_lock_time = {deadline}.saturating_sub(1);
    let (mut tx, entry) = build_spend_tx(&redeem, 200_000_000, early_lock_time, 0);

    let sighash = p2sh_input_sighash(&tx, std::slice::from_ref(&entry), 0);
    let ctrl_sig = schnorr_satisfier_sig(&sighash, &ctrl_kp);
{msig_sig_decls}

    tx.inputs[0].signature_script =
        build_p2sh_signature_script(&[{satisfier_elems}], &redeem).unwrap();

    assert!(
        verify_p2sh_spend_offline(&tx, 0, &entry, false).is_err(),
        "engine must reject composite spend when lock_time < deadline"
    );
}}
"#,
        deadline = deadline,
        threshold = threshold,
        msig_kp_decls = msig_kp_decls,
        msig_pk_decls = msig_pk_decls,
        msig_pks_vec = msig_pks_vec,
        msig_sig_decls = msig_sig_decls,
        satisfier_elems = satisfier_elems,
    );
    std::fs::write(out.join("tests/composite_smoke.rs"), content)
        .context("write tests/composite_smoke.rs")?;
    Ok(())
}

fn write_readme(out: &Path, deadline: u64, threshold: u8, n: usize) -> anyhow::Result<()> {
    let t = threshold as usize;
    let content = format!(
        r#"# my-composite

**Generated by `kcp scaffold composite` — pre-production, unaudited, testnet-only.**

A Kaspa P2SH covenant using `SpendCondition::All([TimelockHeight, MultiSig])`:
- **Timelock**: DAA height must be ≥ {deadline} before any spend is valid.
- **Multisig**: {t}-of-{n} Schnorr signatures required.

Both conditions must be satisfied simultaneously.

## Run the demo

```sh
cargo run
cargo test
```

First run fetches `rusty-kaspa v2.0.0` from GitHub — network required.

## Replace synthetic keys

The generated code uses synthetic test keypairs (`test_keypair(0xNN)`).
Before using on any real network:
1. Replace `ctrl_kp` (TimelockHeight controller) with your real keypair.
2. Replace `msig_kp1..{n}` (multisig signers) with real keypairs.
3. Remove `test_keypair` entirely — use a proper key management solution.

## Satisfier ordering

For `All([leaf_0: TimelockHeight, leaf_1: MultiSig])`, the redeem script
runs `leaf_0` first (consuming the stack TOP). Push order must be reversed:

```
[msig_sig_0, ..., msig_sig_{{t-1}}, ctrl_sig]
```

Multisig sigs are pushed first (deepest), controller sig is pushed last (on
top) so it is consumed first by the CHECKSIG in leaf_0.

## Next steps

- See `crates/kcp-vault/README.md` for the full pattern catalogue.
- See `docs/EVIDENCE.md` for on-chain evidence and test references.
- File issues at https://github.com/kii-foundation/kaspa-compliance-patterns.
- Stichting Kii Foundation — MIT licence — pre-production, unaudited.
"#,
        deadline = deadline,
        t = t,
        n = n,
    );
    std::fs::write(out.join("README.md"), content).context("write README.md")?;
    Ok(())
}
