//! `kcp new --from-solidity erc20` — ERC20→KTT migration scaffold.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

pub struct FromSolidityErc20Config {
    pub name: String,
    pub symbol: String,
    pub decimals: u8,
    pub initial_supply: u64,
    pub out_dir: PathBuf,
    pub workspace_path: PathBuf,
}

pub fn generate(cfg: &FromSolidityErc20Config) -> anyhow::Result<()> {
    if cfg.name.trim().is_empty() {
        bail!("name must not be empty");
    }
    if cfg.symbol.trim().is_empty() {
        bail!("symbol must not be empty");
    }
    if cfg.initial_supply == 0 {
        bail!("initial_supply must be > 0");
    }

    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist")?;

    for p in &[
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/erc20_migration_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ] {
        if p.exists() {
            bail!("output file already exists: {:?}", p);
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(
        &cfg.out_dir,
        &cfg.name,
        &cfg.symbol,
        cfg.decimals,
        cfg.initial_supply,
    )?;
    write_smoke_test(&cfg.out_dir, cfg.initial_supply)?;
    write_readme(&cfg.out_dir, &cfg.name, &cfg.symbol, cfg.initial_supply)?;
    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let dep = ws.join("crates/kii-solidity-compat");
    std::fs::write(
        out.join("Cargo.toml"),
        format!(
            r#"[package]
name = "my-erc20-migration"
version = "0.1.0"
edition = "2021"
# Generated by `kcp new --from-solidity erc20` — pre-production, unaudited, testnet-only.
publish = false

[workspace]

[[bin]]
name = "my-erc20-migration"
path = "src/main.rs"

[dependencies]
kii-solidity-compat = {{ path = "{}" }}
hex = "0.4"
"#,
            dep.display()
        ),
    )?;
    Ok(())
}

fn write_main_rs(
    out: &Path,
    name: &str,
    symbol: &str,
    decimals: u8,
    initial_supply: u64,
) -> anyhow::Result<()> {
    std::fs::write(
        out.join("src/main.rs"),
        format!(
            r#"//! ERC20 → KTT migration scaffold — pre-production, unaudited, testnet-only.
//! Generated by `kcp new --from-solidity erc20`.
//!
//! Demonstrates the Solidity ERC20-shaped API for KTT (Kaspa Trust Token).
//! Replace synthetic keys with real Schnorr x-only public keys before use.

use kii_solidity_compat::erc20::Token;

fn main() {{
    // [1] Construct the token — the ERC20(name, symbol) constructor equivalent.
    //     minter_key = the issuer's 32-byte x-only Schnorr public key.
    //     Replace [0x0fu8; 32] with a real key.
    let minter_key = [0x0fu8; 32];
    let token = Token::new("{name}", "{symbol}", {decimals}, minter_key);
    println!("=== {name} ({symbol}) — ERC20 → KTT migration demo ===");
    println!("    decimals : {decimals}");

    // [2] Initial mint — the `_mint(to, amount)` constructor pattern.
    //     Replace [0x01u8; 32] with a real recipient key.
    let alice_key = [0x01u8; 32];
    let (alice_state, minter_state) = token
        .initial_mint(alice_key, {initial_supply})
        .expect("initial mint");
    println!("    minted   : {{}} {symbol} → alice", alice_state.amount);
    println!("    minter UTXO persisted (is_minter=true): {{}}", minter_state.is_minter);

    // [3] Transfer — token.transfer(from_utxo, to, amount).
    //     Unlike ERC20, you pass the UTXO being spent, not msg.sender.
    //     Replace [0x02u8; 32] with a real recipient key.
    let bob_key = [0x02u8; 32];
    let transfer_amount = {initial_supply} / 4;
    let (to_bob, change) = token
        .transfer(&alice_state, bob_key, transfer_amount)
        .expect("transfer");
    println!("    transfer : {{}} {symbol} to bob; change {{}} back to alice",
        to_bob.amount, change.amount);

    // [4] Burn — token.burn(utxo, amount).
    let burn_amount = to_bob.amount / 2;
    let remaining = token.burn(&to_bob, burn_amount).expect("burn");
    println!("    burn     : {{}} {symbol} burned; {{}} remaining in bob's UTXO",
        burn_amount, remaining.amount);

    // [5] What's different from ERC20 (print as a reminder, not an error):
    println!();
    println!("NOTE: balanceOf, approve, allowance, and transferFrom are absent.");
    println!("  A holder's balance = sum of their KTT UTXOs (query from kaspad).");
    println!("  Delegated spending = model as a covenant spend condition.");
    println!();
    println!("Pre-production, unaudited, testnet-only.");
    println!("To deploy on TN10, encode these KttState values into a transaction");
    println!("and submit via kcp-ktt-token's wrpc feature.");
}}
"#,
            name = name,
            symbol = symbol,
            decimals = decimals,
            initial_supply = initial_supply
        ),
    )?;
    Ok(())
}

fn write_smoke_test(out: &Path, initial_supply: u64) -> anyhow::Result<()> {
    std::fs::write(
        out.join("tests/erc20_migration_smoke.rs"),
        format!(
            r#"use kii_solidity_compat::erc20::Token;
use kii_solidity_compat::Error;

const MINTER: [u8; 32] = [0x0fu8; 32];
const ALICE:  [u8; 32] = [0x01u8; 32];
const BOB:    [u8; 32] = [0x02u8; 32];

fn token() -> Token {{
    Token::new("TestToken", "TST", 8, MINTER)
}}

#[test]
fn initial_mint_matches_supply() {{
    let token = token();
    let (alice, minter) = token.initial_mint(ALICE, {initial_supply}).unwrap();
    assert_eq!(alice.amount, {initial_supply});
    assert!(minter.is_minter);
}}

#[test]
fn transfer_conserves_supply() {{
    let token = token();
    let (alice, _) = token.initial_mint(ALICE, {initial_supply}).unwrap();
    let (to_bob, change) = token.transfer(&alice, BOB, {initial_supply} / 4).unwrap();
    assert_eq!(to_bob.amount + change.amount, {initial_supply});
}}

#[test]
fn burn_reduces_amount() {{
    let token = token();
    let (alice, _) = token.initial_mint(ALICE, {initial_supply}).unwrap();
    let remaining = token.burn(&alice, {initial_supply} / 2).unwrap();
    assert_eq!(remaining.amount, {initial_supply} / 2);
}}

#[test]
fn transfer_over_balance_rejected() {{
    let token = token();
    let (alice, _) = token.initial_mint(ALICE, 100).unwrap();
    let err = token.transfer(&alice, BOB, 101).unwrap_err();
    assert!(matches!(err, Error::InsufficientBalance {{ .. }}));
}}
"#,
            initial_supply = initial_supply
        ),
    )?;
    Ok(())
}

fn write_readme(out: &Path, name: &str, symbol: &str, initial_supply: u64) -> anyhow::Result<()> {
    std::fs::write(
        out.join("README.md"),
        format!(
            r#"# {name} ({symbol}) — ERC20 → KTT migration

> **Pre-production, unaudited, testnet-only.**

Generated by `kcp new --from-solidity erc20`. Demonstrates the ERC20→KTT
migration path for **{name} ({symbol})** with an initial supply of
{initial_supply} smallest-units.

## Run

```sh
cargo run
cargo test
```

## The ERC20 → KTT method map

| ERC20 | This demo | Difference |
|---|---|---|
| `ERC20(name, symbol)` | `Token::new(...)` | No on-chain deployment; returns a descriptor |
| `_mint(to, amount)` | `token.initial_mint(recipient, amount)` | Returns UTXOs |
| `transfer(to, amount)` | `token.transfer(from_utxo, to, amount)` | Takes the UTXO being spent |
| `_burn(from, amount)` | `token.burn(utxo, amount)` | Returns remaining UTXO |
| `balanceOf` | *(no equivalent)* | Sum KTT UTXOs from kaspad |
| `approve` / `transferFrom` | *(not present)* | Model via covenant spend condition |

## Before live use

- Replace `[0x0fu8; 32]` with your real Schnorr x-only minter public key.
- Replace `[0x01u8; 32]` / `[0x02u8; 32]` with real recipient keys.
- To deploy on TN10, encode `KttState` values into a transaction and submit
  via `kcp-ktt-token`'s `wrpc` feature.
- Verify the resulting txid is accepted on TN10 before relying on it.
"#,
            name = name,
            symbol = symbol,
            initial_supply = initial_supply
        ),
    )?;
    Ok(())
}
