//! `kcp new --from-solidity ownable` — Ownable migration scaffold.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

pub struct FromSolidityOwnableConfig {
    pub out_dir: PathBuf,
    pub workspace_path: PathBuf,
}

pub fn generate(cfg: &FromSolidityOwnableConfig) -> anyhow::Result<()> {
    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist")?;

    for p in &[
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/ownable_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ] {
        if p.exists() {
            bail!("output file already exists: {:?}", p);
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(&cfg.out_dir)?;
    write_smoke_test(&cfg.out_dir)?;
    write_readme(&cfg.out_dir)?;
    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let dep = ws.join("crates/kii-solidity-compat");
    std::fs::write(
        out.join("Cargo.toml"),
        format!(
            r#"[package]
name = "my-ownable-migration"
version = "0.1.0"
edition = "2021"
# Generated by `kcp new --from-solidity ownable` — pre-production, unaudited, testnet-only.
publish = false

[workspace]

[[bin]]
name = "my-ownable-migration"
path = "src/main.rs"

[dependencies]
kii-solidity-compat = {{ path = "{}" }}
"#,
            dep.display()
        ),
    )?;
    Ok(())
}

fn write_main_rs(out: &Path) -> anyhow::Result<()> {
    std::fs::write(
        out.join("src/main.rs"),
        r#"//! Ownable migration scaffold — pre-production, unaudited, testnet-only.
//! Generated by `kcp new --from-solidity ownable`.
//!
//! Demonstrates the Solidity Ownable-shaped API over a single-key UTXO ownership
//! record. Replace synthetic keys with real Schnorr x-only public keys.

use kii_solidity_compat::OwnershipRecord;

fn main() {
    // [1] Create the ownership record — Ownable(address initialOwner) equivalent.
    //     Replace [0x01u8; 32] with your real owner x-only public key.
    let owner_key = [0x01u8; 32];
    let record = OwnershipRecord::new(owner_key);
    println!("owner: {}", hex::encode(record.owner()));

    // [2] Verify owner — the onlyOwner modifier equivalent.
    //     Returns Err(NotOwner) if the key does not match.
    record.verify_owner(owner_key).expect("caller is owner");
    println!("verify_owner: OK");

    // [3] Transfer ownership — transferOwnership(newOwner) equivalent.
    //     Returns a new OwnershipRecord; the old record is consumed.
    let new_owner_key = [0x02u8; 32];
    let record = record.transfer_ownership(new_owner_key);
    println!("new owner:  {}", hex::encode(record.owner()));

    // [4] Renounce ownership — renounceOwnership() equivalent.
    //     Sets owner to all-zero bytes (irreversible in application logic).
    let record = record.renounce_ownership();
    println!("renounced:  {}", record.is_renounced());

    // Kaspa difference note:
    println!();
    println!("KASPA NOTE: there is no msg.sender — the signing key must be");
    println!("  supplied explicitly. Covenant scripts enforce the owner's");
    println!("  Schnorr signature on-chain; this type tracks it in app logic.");
    println!("Pre-production, unaudited, testnet-only.");
}
"#,
    )?;
    Ok(())
}

fn write_smoke_test(out: &Path) -> anyhow::Result<()> {
    std::fs::write(
        out.join("tests/ownable_smoke.rs"),
        r#"use kii_solidity_compat::{Error, OwnershipRecord};

fn key(b: u8) -> [u8; 32] {
    let mut k = [0u8; 32];
    k[0] = b;
    k
}

#[test]
fn owner_is_initial_key() {
    let rec = OwnershipRecord::new(key(1));
    assert_eq!(rec.owner(), key(1));
}

#[test]
fn verify_owner_passes_for_owner() {
    let rec = OwnershipRecord::new(key(2));
    assert!(rec.verify_owner(key(2)).is_ok());
}

#[test]
fn verify_owner_fails_for_other() {
    let rec = OwnershipRecord::new(key(3));
    assert!(matches!(rec.verify_owner(key(4)), Err(Error::NotOwner)));
}

#[test]
fn transfer_ownership_changes_owner() {
    let rec = OwnershipRecord::new(key(5)).transfer_ownership(key(6));
    assert_eq!(rec.owner(), key(6));
}

#[test]
fn renounce_ownership_zeroes_key() {
    let rec = OwnershipRecord::new(key(7)).renounce_ownership();
    assert!(rec.is_renounced());
}
"#,
    )?;
    Ok(())
}

fn write_readme(out: &Path) -> anyhow::Result<()> {
    std::fs::write(
        out.join("README.md"),
        r#"# Ownable migration scaffold

> **Pre-production, unaudited, testnet-only.**

Generated by `kcp new --from-solidity ownable`. Demonstrates the
`OwnershipRecord` type from `kii-solidity-compat` — the Solidity `Ownable`
equivalent for Kaspa.

## Run

```sh
cargo run
cargo test
```

## Solidity → Kaspa method map

| Solidity `Ownable` | This demo | Difference |
|---|---|---|
| `Ownable(address initialOwner)` | `OwnershipRecord::new(owner_key)` | Key, not address |
| `owner()` | `record.owner()` | Returns 32-byte x-only Schnorr pubkey |
| `onlyOwner` modifier | `record.verify_owner(key)?` | Supply the key explicitly — no `msg.sender` |
| `transferOwnership(newOwner)` | `record.transfer_ownership(new_owner)` | Returns new record (pure value) |
| `renounceOwnership()` | `record.renounce_ownership()` | Zeroes the key |

## Before live use

Replace synthetic keys with real 32-byte x-only Schnorr public keys.
The covenant script (e.g., compiled by `kcp scaffold vault`) enforces
the owner's Schnorr signature on-chain; this type tracks it in app logic.
"#,
    )?;
    Ok(())
}
