//! `kcp new --from-solidity timelock` — TimelockController migration scaffold.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

pub struct FromSolidityTimelockConfig {
    pub min_delay_daa: u64,
    pub out_dir: PathBuf,
    pub workspace_path: PathBuf,
}

pub fn generate(cfg: &FromSolidityTimelockConfig) -> anyhow::Result<()> {
    if cfg.min_delay_daa == 0 {
        bail!("min-delay-daa must be ≥ 1 (at 1 BPS ≈ 1 second per DAA unit)");
    }

    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist")?;

    for p in &[
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/timelock_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ] {
        if p.exists() {
            bail!("output file already exists: {:?}", p);
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(&cfg.out_dir, cfg.min_delay_daa)?;
    write_smoke_test(&cfg.out_dir, cfg.min_delay_daa)?;
    write_readme(&cfg.out_dir, cfg.min_delay_daa)?;
    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let dep = ws.join("crates/kii-solidity-compat");
    std::fs::write(
        out.join("Cargo.toml"),
        format!(
            r#"[package]
name = "my-timelock-migration"
version = "0.1.0"
edition = "2021"
# Generated by `kcp new --from-solidity timelock` — pre-production, unaudited, testnet-only.
publish = false

[workspace]

[[bin]]
name = "my-timelock-migration"
path = "src/main.rs"

[dependencies]
kii-solidity-compat = {{ path = "{}" }}
"#,
            dep.display()
        ),
    )?;
    Ok(())
}

fn write_main_rs(out: &Path, min_delay: u64) -> anyhow::Result<()> {
    std::fs::write(
        out.join("src/main.rs"),
        format!(
            r#"//! TimelockController migration scaffold — pre-production, unaudited, testnet-only.
//! Generated by `kcp new --from-solidity timelock`.
//!
//! Demonstrates the Solidity TimelockController-shaped API over kcp-governance's
//! TimelockAction. Replace synthetic keys and heights with real values.

use kii_solidity_compat::TimelockController;

fn main() {{
    // Minimum delay in DAA heights. At 1 BPS ≈ {min_delay} seconds.
    const MIN_DELAY: u64 = {min_delay};

    // Role keys — replace with real 32-byte x-only Schnorr public keys.
    let proposer_key = [0x01u8; 32];
    let executor_key = [0x02u8; 32];

    // [1] Constructor — TimelockController(minDelay, proposers[], executors[]) equivalent.
    let mut ctrl = TimelockController::new(MIN_DELAY, proposer_key, executor_key)
        .expect("valid delay");
    println!("TimelockController created. min_delay = {{}} DAA heights", MIN_DELAY);

    // [2] Schedule — propose an operation at the current DAA height.
    //     Replace 1_000_000 with the real current DAA height from kaspad.
    let current_daa = 1_000_000u64;
    ctrl.schedule(proposer_key, current_daa).expect("proposer schedules");
    let earliest = ctrl.earliest_execution_height().unwrap();
    println!("Scheduled at DAA {{}}; earliest execution at {{}}",
        current_daa, earliest);

    // [3] isOperationReady — check if delay has elapsed.
    let before = current_daa + MIN_DELAY - 1;
    let at     = current_daa + MIN_DELAY;
    println!("is_ready at {{}}: {{}}", before, ctrl.is_ready(before));
    println!("is_ready at {{}}: {{}}", at,     ctrl.is_ready(at));

    // [4] Execute — only by the executor key after delay.
    ctrl.execute(executor_key, at).expect("executor executes after delay");
    println!("Executed at DAA {{}}.", at);

    // [5] Cancel — cancel a queued operation.
    let mut ctrl2 = TimelockController::new(MIN_DELAY, proposer_key, executor_key).unwrap();
    ctrl2.schedule(proposer_key, current_daa).unwrap();
    ctrl2.cancel();
    println!("cancel(): is_cancelled = {{}}", ctrl2.is_cancelled());

    println!();
    println!("KASPA NOTE: time is measured in DAA heights (≈ 1 s/height at 1 BPS),");
    println!("  not unix seconds. Supply current height from kaspad.");
    println!("Pre-production, unaudited, testnet-only.");
}}
"#,
            min_delay = min_delay
        ),
    )?;
    Ok(())
}

fn write_smoke_test(out: &Path, min_delay: u64) -> anyhow::Result<()> {
    std::fs::write(
        out.join("tests/timelock_smoke.rs"),
        format!(
            r#"use kii_solidity_compat::{{Error, TimelockController}};

const MIN_DELAY: u64 = {min_delay};
const PROPOSER: [u8; 32] = [0x01u8; 32];
const EXECUTOR: [u8; 32] = [0x02u8; 32];
const OTHER:    [u8; 32] = [0x09u8; 32];

fn ctrl() -> TimelockController {{
    TimelockController::new(MIN_DELAY, PROPOSER, EXECUTOR).unwrap()
}}

#[test]
fn happy_path() {{
    let mut c = ctrl();
    c.schedule(PROPOSER, 1_000_000).unwrap();
    assert!(c.is_ready(1_000_000 + MIN_DELAY));
    assert!(c.execute(EXECUTOR, 1_000_000 + MIN_DELAY).is_ok());
}}

#[test]
fn not_ready_before_delay() {{
    let mut c = ctrl();
    c.schedule(PROPOSER, 1_000_000).unwrap();
    assert!(!c.is_ready(1_000_000 + MIN_DELAY - 1));
}}

#[test]
fn wrong_proposer_rejected() {{
    let mut c = ctrl();
    assert!(matches!(c.schedule(OTHER, 1_000_000), Err(Error::NotProposer)));
}}

#[test]
fn wrong_executor_rejected() {{
    let mut c = ctrl();
    c.schedule(PROPOSER, 1_000_000).unwrap();
    assert!(matches!(c.execute(OTHER, 2_000_000), Err(Error::NotExecutor)));
}}

#[test]
fn cancel_blocks_all() {{
    let mut c = ctrl();
    c.cancel();
    assert!(matches!(c.schedule(PROPOSER, 1_000_000), Err(Error::AlreadyCancelled)));
}}
"#,
            min_delay = min_delay
        ),
    )?;
    Ok(())
}

fn write_readme(out: &Path, min_delay: u64) -> anyhow::Result<()> {
    std::fs::write(
        out.join("README.md"),
        format!(
            r#"# TimelockController migration scaffold

> **Pre-production, unaudited, testnet-only.**

Generated by `kcp new --from-solidity timelock`. Demonstrates the
`TimelockController` type from `kii-solidity-compat` — the Solidity
`TimelockController` equivalent for Kaspa. Minimum delay: {min_delay} DAA heights
(≈ {min_delay} seconds at 1 BPS).

## Run

```sh
cargo run
cargo test
```

## Solidity → Kaspa method map

| Solidity `TimelockController` | This demo | Difference |
|---|---|---|
| `constructor(minDelay, proposers, executors)` | `TimelockController::new(min_delay_daa, proposer, executor)` | One proposer + one executor key |
| `schedule(target, …, delay)` | `ctrl.schedule(proposer_key, current_daa)` | Caller supplies current DAA height |
| `isOperationReady(id)` | `ctrl.is_ready(current_daa)` | DAA height, not unix timestamp |
| `execute(target, …)` | `ctrl.execute(executor_key, current_daa)` | Supply executor key explicitly |
| `cancel(id)` | `ctrl.cancel()` | Irreversible; blocks schedule + execute |

## Before live use

- Replace synthetic keys with real 32-byte x-only Schnorr public keys.
- Obtain the current DAA height from a kaspad node.
- Persist `TimelockController` state to a `kcp-sealed-lineage` covenant for
  on-chain continuity.
"#,
            min_delay = min_delay
        ),
    )?;
    Ok(())
}
