//! `kcp new --from-solidity vault` — Vault (ERC4626/Escrow) migration scaffold.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

pub struct FromSolidityVaultConfig {
    pub deadline_daa: u64,
    pub out_dir: PathBuf,
    pub workspace_path: PathBuf,
}

pub fn generate(cfg: &FromSolidityVaultConfig) -> anyhow::Result<()> {
    if cfg.deadline_daa == 0 {
        bail!("deadline-daa must be > 0");
    }

    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist")?;

    for p in &[
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/vault_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ] {
        if p.exists() {
            bail!("output file already exists: {:?}", p);
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(&cfg.out_dir, cfg.deadline_daa)?;
    write_smoke_test(&cfg.out_dir, cfg.deadline_daa)?;
    write_readme(&cfg.out_dir, cfg.deadline_daa)?;
    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let compat_dep = ws.join("crates/kii-solidity-compat");
    let vault_dep = ws.join("crates/kcp-vault");
    std::fs::write(
        out.join("Cargo.toml"),
        format!(
            r#"[package]
name = "my-vault-migration"
version = "0.1.0"
edition = "2021"
# Generated by `kcp new --from-solidity vault` — pre-production, unaudited, testnet-only.
publish = false

[workspace]

[[bin]]
name = "my-vault-migration"
path = "src/main.rs"

[dependencies]
kii-solidity-compat = {{ path = "{compat}" }}
kcp-vault = {{ path = "{vault}" }}
"#,
            compat = compat_dep.display(),
            vault = vault_dep.display(),
        ),
    )?;
    Ok(())
}

fn write_main_rs(out: &Path, deadline: u64) -> anyhow::Result<()> {
    std::fs::write(
        out.join("src/main.rs"),
        format!(
            r#"//! Vault migration scaffold — pre-production, unaudited, testnet-only.
//! Generated by `kcp new --from-solidity vault`.
//!
//! Demonstrates the Solidity ERC4626/Escrow-shaped Vault API over kcp-vault's
//! SpendCondition model. Replace the deadline and keys with real values.

use kcp_vault::{{
    condition::SpendCondition,
    evaluator::EvalContext,
}};
use kii_solidity_compat::Vault;

fn main() {{
    // [1] Define the spending condition — the "constructor" equivalent.
    //     Replace the deadline and controller_xonly with real values.
    let deadline_daa: u64 = {deadline};
    let controller_key = [0x01u8; 32]; // 32-byte x-only Schnorr pubkey

    let condition = SpendCondition::TimelockHeight {{
        deadline: deadline_daa,
        controller_xonly: controller_key,
    }};

    // [2] Create the vault — ERC4626.deploy() / Escrow.new() equivalent.
    let vault = Vault::new(condition).expect("valid condition");
    println!("Vault created. deadline_daa = {{}}", deadline_daa);

    // [3] Deposit — ERC4626.deposit(assets, receiver) equivalent.
    //     Returns a VaultDescriptor (the UTXO to create), not a share token.
    let deposit_sompi: u64 = 500_000_000; // 500 KAS
    let descriptor = vault.deposit(deposit_sompi).expect("non-zero deposit");
    println!("Deposit: {{}} sompi under timelock DAA {{}}", descriptor.amount_sompi, deadline_daa);

    // [4] Evaluate — check if the vault can be spent now.
    let before_ctx = EvalContext {{
        daa_score: deadline_daa - 1,
        unix_seconds: 0,
        signers_present: vec![controller_key],
    }};
    let at_ctx = EvalContext {{
        daa_score: deadline_daa,
        unix_seconds: 0,
        signers_present: vec![controller_key],
    }};
    println!("can_spend at DAA {{}}: {{}}", deadline_daa - 1, vault.evaluate(&before_ctx));
    println!("can_spend at DAA {{}}: {{}}", deadline_daa,     vault.evaluate(&at_ctx));

    println!();
    println!("KASPA NOTE: a vault is a UTXO locked under a covenant script.");
    println!("  The condition is enforced by the Toccata consensus engine.");
    println!("  Use `kcp-vault`'s wrpc feature to build and submit the lock tx.");
    println!("Pre-production, unaudited, testnet-only.");
}}
"#,
            deadline = deadline
        ),
    )?;
    Ok(())
}

fn write_smoke_test(out: &Path, deadline: u64) -> anyhow::Result<()> {
    std::fs::write(
        out.join("tests/vault_smoke.rs"),
        format!(
            r#"use kcp_vault::{{condition::SpendCondition, evaluator::EvalContext}};
use kii_solidity_compat::{{Error, Vault}};

const DEADLINE: u64 = {deadline};
const CTRL: [u8; 32] = [0x01u8; 32];

fn timelock_vault() -> Vault {{
    Vault::new(SpendCondition::TimelockHeight {{
        deadline: DEADLINE,
        controller_xonly: CTRL,
    }})
    .unwrap()
}}

fn ctx(daa: u64) -> EvalContext {{
    EvalContext {{ daa_score: daa, unix_seconds: 0, signers_present: vec![] }}
}}

#[test]
fn deposit_returns_descriptor() {{
    let desc = timelock_vault().deposit(1_000_000_000).unwrap();
    assert_eq!(desc.amount_sompi, 1_000_000_000);
}}

#[test]
fn zero_deposit_rejected() {{
    assert!(matches!(timelock_vault().deposit(0), Err(Error::ZeroDeposit)));
}}

#[test]
fn not_spendable_before_deadline() {{
    assert!(!timelock_vault().evaluate(&ctx(DEADLINE - 1)));
}}

#[test]
fn spendable_at_deadline() {{
    assert!(timelock_vault().evaluate(&ctx(DEADLINE)));
}}

#[test]
fn invalid_condition_rejected() {{
    let bad = SpendCondition::MultiSig {{ threshold: 5, xonly_keys: vec![] }};
    assert!(matches!(Vault::new(bad), Err(Error::VaultConditionInvalid(_))));
}}
"#,
            deadline = deadline
        ),
    )?;
    Ok(())
}

fn write_readme(out: &Path, deadline: u64) -> anyhow::Result<()> {
    std::fs::write(
        out.join("README.md"),
        format!(
            r#"# Vault migration scaffold

> **Pre-production, unaudited, testnet-only.**

Generated by `kcp new --from-solidity vault`. Demonstrates the `Vault` type
from `kii-solidity-compat` — the `ERC4626`/`Escrow` equivalent for Kaspa.
This scaffold uses a `TimelockHeight` condition with deadline `{deadline}` DAA
heights.

## Run

```sh
cargo run
cargo test
```

## Solidity → Kaspa method map

| EVM concept | This demo | Difference |
|---|---|---|
| `ERC4626` constructor | `Vault::new(SpendCondition::…)` | Condition, not asset address |
| `deposit(assets, receiver)` | `vault.deposit(amount_sompi)` | Returns `VaultDescriptor`; no share token |
| `maxWithdraw(owner)` | `descriptor.amount_sompi` | No account balance |
| `withdraw(assets, …)` | broadcast tx satisfying the condition | Consensus-enforced on L1 |
| Condition check | `vault.evaluate(&ctx)` | Offline evaluation only |

## Before live use

- Replace `deadline_daa` with your real DAA-height deadline.
- Replace `controller_key` with your real 32-byte x-only Schnorr public key.
- Use `kcp-vault`'s `wrpc` feature to build and broadcast the locking
  transaction, then satisfy the spend condition in a separate tx.
- All conditions are validated by the Toccata covenant script engine —
  an invalid spend is rejected by consensus.
"#,
            deadline = deadline
        ),
    )?;
    Ok(())
}
