//! Governance scaffold — GovernanceProposal + MultiSigVote + TimelockAction + GovernorState demo.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

pub struct GovernanceConfig {
    pub title: String,
    pub threshold: u8,
    pub n: usize,
    pub voting_window: u64,
    pub timelock_delay: u64,
    pub out_dir: PathBuf,
    pub workspace_path: PathBuf,
}

pub fn generate(cfg: &GovernanceConfig) -> anyhow::Result<()> {
    if cfg.title.trim().is_empty() {
        bail!("title must not be empty");
    }
    if cfg.n == 0 || cfg.threshold == 0 || cfg.threshold as usize > cfg.n {
        bail!("threshold must be ≥1 and ≤ n");
    }
    if cfg.voting_window == 0 {
        bail!("voting_window must be > 0");
    }
    if cfg.timelock_delay == 0 {
        bail!("timelock_delay must be > 0");
    }

    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist")?;

    for p in &[
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/governance_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ] {
        if p.exists() {
            bail!("output file already exists: {:?}", p);
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(
        &cfg.out_dir,
        &cfg.title,
        cfg.threshold,
        cfg.n,
        cfg.voting_window,
        cfg.timelock_delay,
    )?;
    write_smoke_test(&cfg.out_dir, cfg.threshold)?;
    write_readme(&cfg.out_dir, &cfg.title, cfg.threshold, cfg.n)?;
    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let dep = ws.join("crates/kcp-governance");
    std::fs::write(
        out.join("Cargo.toml"),
        format!(
            r#"[package]
name = "my-governance"
version = "0.1.0"
edition = "2021"
# Generated by `kcp scaffold governance` — pre-production, unaudited, testnet-only.
publish = false

[workspace]

[[bin]]
name = "my-governance"
path = "src/main.rs"

[dependencies]
kcp-governance = {{ path = "{}" }}
hex = "0.4"
"#,
            dep.display()
        ),
    )?;
    Ok(())
}

fn write_main_rs(
    out: &Path,
    title: &str,
    threshold: u8,
    n: usize,
    voting_window: u64,
    timelock_delay: u64,
) -> anyhow::Result<()> {
    let keys: String = (0..n)
        .map(|i| format!("    let key_{} = [0x{:02X}u8; 32];", i, i + 1))
        .collect::<Vec<_>>()
        .join("\n");
    let key_vec: String = (0..n)
        .map(|i| format!("key_{}", i))
        .collect::<Vec<_>>()
        .join(", ");
    let approvals: String = (0..threshold as usize)
        .map(|i| format!("    vote.approve(key_{}).expect(\"approve key_{}\");", i, i))
        .collect::<Vec<_>>()
        .join("\n");

    std::fs::write(
        out.join("src/main.rs"),
        format!(
            r#"//! Governance scaffold — pre-production, unaudited, testnet-only.
//! Generated by `kcp scaffold governance`.
//!
//! Demonstrates: GovernanceProposal → MultiSigVote → TimelockAction → GovernorState

use kcp_governance::{{
    action::TimelockAction,
    governor::GovernorState,
    proposal::GovernanceProposal,
    vote::MultiSigVote,
}};

fn main() {{
    let current_height: u64 = 100_000;
    let voting_deadline = current_height + {voting_window};
    let execute_after  = voting_deadline + {timelock_delay};

    println!("=== Governance scaffold: {title} ===");
    println!("    voting window : height {{}} → {{}}", current_height, voting_deadline);
    println!("    timelock delay: {{}} DAA units", {timelock_delay});

    // [1] Synthetic committee keys — replace with real Schnorr x-only keys
{keys}
    let signatories = vec![{key_vec}];

    // [2] Build vote — apply approvals BEFORE creating GovernorState
    let mut vote = MultiSigVote::new(signatories, {threshold}).expect("valid vote");
{approvals}
    println!("    ✓ quorum reached ({threshold} of {n})");

    // [3] Create GovernorState
    let proposal = GovernanceProposal::new("{title}", current_height, voting_deadline)
        .expect("valid proposal");
    let action   = TimelockAction::new({timelock_delay}).expect("valid action");
    let mut gov  = GovernorState::new(proposal, vote, action, current_height);

    // [4] Advance past deadline → Passed
    gov.refresh_status(voting_deadline + 1);
    println!("    ✓ status after deadline: {{:?}}", gov.status());

    // [5] Schedule and execute
    gov.schedule_action(voting_deadline + 1).expect("schedule");
    gov.execute(execute_after + 1).expect("execute");
    println!("    ✓ action executed at height {{}}", execute_after + 1);

    println!("Pre-production, unaudited, testnet-only.");
}}
"#,
            voting_window = voting_window,
            timelock_delay = timelock_delay,
            title = title,
            keys = keys,
            key_vec = key_vec,
            approvals = approvals,
            threshold = threshold,
            n = n
        ),
    )?;
    Ok(())
}

fn write_smoke_test(out: &Path, threshold: u8) -> anyhow::Result<()> {
    let _ = threshold;
    std::fs::write(
        out.join("tests/governance_smoke.rs"),
        r#"use kcp_governance::{
    action::TimelockAction, governor::GovernorState,
    proposal::GovernanceProposal, vote::MultiSigVote,
};

fn key(seed: u8) -> [u8; 32] { let mut k = [0u8; 32]; k[0] = seed; k }

#[test]
fn governance_cycle_completes() {
    let mut vote = MultiSigVote::new(vec![key(1), key(2), key(3)], 2).unwrap();
    vote.approve(key(1)).unwrap();
    vote.approve(key(2)).unwrap();

    let proposal = GovernanceProposal::new("test", 1_000, 2_000).unwrap();
    let action   = TimelockAction::new(100).unwrap();
    let mut gov  = GovernorState::new(proposal, vote, action, 1_000);

    gov.refresh_status(2_001);
    gov.schedule_action(2_001).unwrap();
    gov.execute(2_102).unwrap();
}

#[test]
fn quorum_required() {
    let vote = MultiSigVote::new(vec![key(1), key(2), key(3)], 2).unwrap();
    // No approvals — quorum not met
    let proposal = GovernanceProposal::new("test", 1_000, 2_000).unwrap();
    let action   = TimelockAction::new(100).unwrap();
    let mut gov  = GovernorState::new(proposal, vote, action, 1_000);
    gov.refresh_status(2_001);
    assert!(gov.schedule_action(2_001).is_err());
}
"#,
    )?;
    Ok(())
}

fn write_readme(out: &Path, title: &str, threshold: u8, n: usize) -> anyhow::Result<()> {
    std::fs::write(
        out.join("README.md"),
        format!(
            r#"# Governance scaffold: {title}

> **Pre-production, unaudited, testnet-only.**

Generated by `kcp scaffold governance`. Demonstrates a {threshold}-of-{n}
committee governance cycle on the Kaspa BlockDAG:

`GovernanceProposal → MultiSigVote → TimelockAction → GovernorState`

## Run

```sh
cargo run
cargo test
```

## Before live use

- Replace synthetic keys with real Schnorr x-only public keys.
- Use real DAA heights from a connected `kaspad` node.
- Verify Schnorr signatures before calling `MultiSigVote::approve()`.
- Persist `GovernorState` after each state transition.
"#,
            title = title,
            threshold = threshold,
            n = n
        ),
    )?;
    Ok(())
}
