//! KTT-token scaffold generator — produces a compilable Cargo project for a
//! KCC20-shape regulated-token state-machine demo.
//!
//! The generated project demonstrates `mint → transfer → burn` using the pure
//! state-transition functions in `kcp-ktt-token`. No live node or UTXO
//! encoding required — runs entirely offline.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

/// Configuration for a generated KTT-token scaffold.
pub struct KttTokenConfig {
    /// Token name used in generated comments (display only in v0).
    pub token_name: String,
    /// Initial supply minted in the demo.
    pub initial_supply: u64,
    /// Output directory for the generated project.
    pub out_dir: PathBuf,
    /// Absolute path to the kaspa-compliance-patterns workspace root.
    pub workspace_path: PathBuf,
}

/// Generate a KTT-token scaffold project at `cfg.out_dir`.
///
/// Creates `Cargo.toml`, `src/main.rs`, `tests/ktt_smoke.rs`, and `README.md`.
/// The generated project uses pure state-transition functions; no engine call
/// or live node required.
///
/// Fails if any output file already exists.
///
/// **Pre-production, unaudited, testnet-only.**
pub fn generate(cfg: &KttTokenConfig) -> anyhow::Result<()> {
    if cfg.token_name.trim().is_empty() {
        bail!("token_name must not be empty");
    }
    if cfg.initial_supply == 0 {
        bail!("initial_supply must be > 0");
    }

    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist or is not accessible")?;

    let guard_paths = [
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/ktt_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ];
    for p in &guard_paths {
        if p.exists() {
            bail!(
                "output file already exists: {:?}\n\
                 Use a fresh, empty directory to avoid accidental overwrites.",
                p
            );
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create out_dir/src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create out_dir/tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(&cfg.out_dir, &cfg.token_name, cfg.initial_supply)?;
    write_smoke_test(&cfg.out_dir, cfg.initial_supply)?;
    write_readme(&cfg.out_dir, &cfg.token_name, cfg.initial_supply)?;

    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let kcp_ktt = ws.join("crates/kcp-ktt-token");
    let content = format!(
        r#"[package]
name = "my-ktt-token"
version = "0.1.0"
edition = "2021"
# Generated by `kcp scaffold ktt-token` — pre-production, unaudited, testnet-only.
# kcp-ktt-token is not yet on crates.io. Use --workspace-path until v0.2 publishes.
# WARNING: path dep below is an absolute path on the generating machine.
publish = false

[workspace]

[dependencies]
kcp-ktt-token = {{ path = {kcp_ktt:?} }}
serde_json = "1"
"#
    );
    std::fs::write(out.join("Cargo.toml"), content).context("write Cargo.toml")?;
    Ok(())
}

fn write_main_rs(out: &Path, token_name: &str, initial_supply: u64) -> anyhow::Result<()> {
    let transfer_amount = initial_supply / 4;
    let burn_amount = initial_supply / 8;
    let content = format!(
        r#"//! Generated by `kcp scaffold ktt-token` — pre-production, unaudited, testnet-only.
//!
//! KCC20-shape regulated-token demo: `{token_name}`.
//! Demonstrates mint → transfer → burn state transitions using
//! `kcp-ktt-token`'s pure state-transition functions.
//!
//! Runs entirely offline — no live node, no funds, no UTXO encoding.
//!
//! TODO: integrate with a UTXO-bearing transaction to commit state on-chain.
//! See `kcp-ktt-token/src/tx.rs` and `crates/kcp-ktt-token/README.md`.

use kcp_ktt_token::{{
    state::{{IdentifierType, KttState}},
    token::{{AuthContext, burn, mint, transfer}},
}};

// Synthetic owner identifiers — 32-byte x-only public keys.
// TODO: replace with real Schnorr public keys before use.
const MINTER_ID: [u8; 32] = [0x0fu8; 32]; // minter authority
const ALICE_ID: [u8; 32]  = [0x01u8; 32]; // first recipient
const BOB_ID: [u8; 32]    = [0x02u8; 32]; // second recipient

fn make_state(owner: [u8; 32], amount: u64, is_minter: bool) -> KttState {{
    KttState {{
        identifier_type: IdentifierType::Pubkey,
        owner_identifier: owner,
        amount,
        is_minter,
    }}
}}

fn auth(owners: &[[u8; 32]]) -> AuthContext {{
    AuthContext {{ authorised_owners: owners.to_vec() }}
}}

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    println!("{token_name} — KTT-token state-machine demo (offline)");

    // [1/3] MINT — minter creates {initial_supply} tokens for ALICE.
    let minter_input = make_state(MINTER_ID, 0, true); // minter branch (amount unused)
    let minted_output = make_state(ALICE_ID, {initial_supply}, false);
    let persisted_minter = make_state(MINTER_ID, 0, true); // minter branch carries forward
    mint(
        &minter_input,
        &minted_output,
        &persisted_minter,
        &auth(&[MINTER_ID]),
        0,
    )?;
    println!(
        "  ✓ mint: ALICE holds {initial_supply} {token_name}"
    );

    // [2/3] TRANSFER — ALICE sends {transfer_amount} tokens to BOB.
    let transfer_in = make_state(ALICE_ID, {initial_supply}, false);
    let transfer_to_bob = make_state(BOB_ID, {transfer_amount}, false);
    let transfer_change = make_state(ALICE_ID, {initial_supply} - {transfer_amount}, false);
    transfer(
        &[transfer_in],
        &[transfer_to_bob, transfer_change],
        &auth(&[ALICE_ID]),
        0,
    )?;
    println!(
        "  ✓ transfer: BOB receives {transfer_amount}, ALICE retains {{remaining}}",
        remaining = {initial_supply} - {transfer_amount},
    );

    // [3/3] BURN — BOB burns {burn_amount} tokens.
    let burn_in = make_state(BOB_ID, {transfer_amount}, false);
    let burn_out = make_state(BOB_ID, {transfer_amount} - {burn_amount}, false);
    burn(&burn_in, &burn_out, {burn_amount}, &auth(&[BOB_ID]), 0)?;
    println!(
        "  ✓ burn: {burn_amount} tokens burned; BOB retains {{retained}}",
        retained = {transfer_amount} - {burn_amount},
    );

    println!(
        "✓ PASSED — mint/transfer/burn state transitions all accepted by {token_name} rules"
    );
    Ok(())
}}
"#,
        token_name = token_name,
        initial_supply = initial_supply,
        transfer_amount = transfer_amount,
        burn_amount = burn_amount,
    );
    std::fs::write(out.join("src/main.rs"), content).context("write src/main.rs")?;
    Ok(())
}

fn write_smoke_test(out: &Path, initial_supply: u64) -> anyhow::Result<()> {
    let transfer_amount = initial_supply / 4;
    let burn_amount = initial_supply / 8;
    let content = format!(
        r#"// Generated by `kcp scaffold ktt-token` — pre-production, unaudited, testnet-only.

use kcp_ktt_token::{{
    state::{{IdentifierType, KttState}},
    token::{{AuthContext, burn, mint, transfer}},
}};

const MINTER_ID: [u8; 32] = [0x0fu8; 32];
const ALICE_ID: [u8; 32]  = [0x01u8; 32];
const BOB_ID: [u8; 32]    = [0x02u8; 32];

fn make_state(owner: [u8; 32], amount: u64, is_minter: bool) -> KttState {{
    KttState {{
        identifier_type: IdentifierType::Pubkey,
        owner_identifier: owner,
        amount,
        is_minter,
    }}
}}

fn auth(owners: &[[u8; 32]]) -> AuthContext {{
    AuthContext {{ authorised_owners: owners.to_vec() }}
}}

#[test]
fn mint_transfer_burn_round_trip() {{
    // Mint
    mint(
        &make_state(MINTER_ID, 0, true),
        &make_state(ALICE_ID, {initial_supply}, false),
        &make_state(MINTER_ID, 0, true),
        &auth(&[MINTER_ID]),
        0,
    ).unwrap();

    // Transfer
    transfer(
        &[make_state(ALICE_ID, {initial_supply}, false)],
        &[
            make_state(BOB_ID, {transfer_amount}, false),
            make_state(ALICE_ID, {initial_supply} - {transfer_amount}, false),
        ],
        &auth(&[ALICE_ID]),
        0,
    ).unwrap();

    // Burn
    burn(
        &make_state(BOB_ID, {transfer_amount}, false),
        &make_state(BOB_ID, {transfer_amount} - {burn_amount}, false),
        {burn_amount},
        &auth(&[BOB_ID]),
        0,
    ).unwrap();
}}

#[test]
fn transfer_without_auth_rejected() {{
    // Attempting to transfer ALICE's tokens with BOB's auth must fail.
    let err = transfer(
        &[make_state(ALICE_ID, {initial_supply}, false)],
        &[make_state(BOB_ID, {initial_supply}, false)],
        &auth(&[BOB_ID]), // wrong owner
        0,
    ).unwrap_err();
    assert!(
        format!("{{err:?}}").contains("OwnerAuthAbsent"),
        "expected OwnerAuthAbsent, got {{err:?}}"
    );
}}

#[test]
fn supply_conservation_enforced() {{
    // Output sum less than input sum must be rejected (KTT-1).
    let err = transfer(
        &[make_state(ALICE_ID, {initial_supply}, false)],
        &[make_state(BOB_ID, {initial_supply} - 1, false)],
        &auth(&[ALICE_ID]),
        0,
    ).unwrap_err();
    assert!(
        format!("{{err:?}}").contains("SupplyConservation"),
        "expected SupplyConservation, got {{err:?}}"
    );
}}
"#,
        initial_supply = initial_supply,
        transfer_amount = transfer_amount,
        burn_amount = burn_amount,
    );
    std::fs::write(out.join("tests/ktt_smoke.rs"), content).context("write tests/ktt_smoke.rs")?;
    Ok(())
}

fn write_readme(out: &Path, token_name: &str, initial_supply: u64) -> anyhow::Result<()> {
    let content = format!(
        r#"# my-ktt-token

**Generated by `kcp scaffold ktt-token` — pre-production, unaudited, testnet-only.**

A KCC20-shape regulated-token demo: **{token_name}**.

Demonstrates `mint → transfer → burn` state transitions using `kcp-ktt-token`'s
pure state-validation functions. Runs entirely offline.

## Run the demo

```sh
cargo run
cargo test
```

## KTT invariants demonstrated

- **KTT-1** supply conservation: `sum(outputs.amount) == sum(inputs.amount)` (except burn).
- **KTT-2** minter escalation guard: non-minter inputs cannot produce minter outputs.
- **KTT-3** owner authorisation: every input owner must be in the `AuthContext`.
- **KTT-4** identifier validity: output identifier types must be valid.

## Initial supply

{initial_supply} tokens minted to ALICE (synthetic owner `0x01..01`).

## Next steps

- Replace synthetic owner ids with real Schnorr public keys.
- Add UTXO encoding (`kcp-ktt-token::tx`) to commit state on testnet-10.
- See `crates/kcp-ktt-token/README.md` for the full pattern spec.
- See `docs/EVIDENCE.md` for on-chain evidence (`[KCP-KTT-002]` + `[KCP-KTT-003]`).
- Stichting Kii Foundation — MIT licence — pre-production, unaudited.
"#,
        token_name = token_name,
        initial_supply = initial_supply,
    );
    std::fs::write(out.join("README.md"), content).context("write README.md")?;
    Ok(())
}
