//! Paired-attestation scaffold generator — produces a compilable Cargo project
//! demonstrating the two-party mutual attestation (mate-proof) flow.
//!
//! Runs entirely offline — no CSFS opcode or live node required in v0.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

/// Configuration for a generated paired-attestation scaffold.
pub struct PairedAttestationConfig {
    /// Attestation subject label used in generated comments.
    pub subject_label: String,
    /// Output directory for the generated project.
    pub out_dir: PathBuf,
    /// Absolute path to the kaspa-compliance-patterns workspace root.
    pub workspace_path: PathBuf,
}

/// Generate a paired-attestation scaffold project at `cfg.out_dir`.
///
/// Creates `Cargo.toml`, `src/main.rs`, `tests/attestation_smoke.rs`, and `README.md`.
///
/// Fails if any output file already exists.
///
/// **Pre-production, unaudited, testnet-only.**
pub fn generate(cfg: &PairedAttestationConfig) -> anyhow::Result<()> {
    if cfg.subject_label.trim().is_empty() {
        bail!("subject_label must not be empty");
    }

    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist or is not accessible")?;

    let guard_paths = [
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/attestation_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ];
    for p in &guard_paths {
        if p.exists() {
            bail!(
                "output file already exists: {:?}\n\
                 Use a fresh, empty directory to avoid accidental overwrites.",
                p
            );
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create out_dir/src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create out_dir/tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(&cfg.out_dir, &cfg.subject_label)?;
    write_smoke_test(&cfg.out_dir)?;
    write_readme(&cfg.out_dir, &cfg.subject_label)?;

    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let kcp_pa = ws.join("crates/kcp-paired-attestation");
    let kcp_common = ws.join("crates/kcp-common");
    let content = format!(
        r#"[package]
name = "my-paired-attestation"
version = "0.1.0"
edition = "2021"
# Generated by `kcp scaffold paired-attestation` — pre-production, unaudited, testnet-only.
# kcp-paired-attestation is not yet on crates.io. Use --workspace-path until v0.2 publishes.
# WARNING: path deps below are absolute paths on the generating machine.
publish = false

[workspace]

[dependencies]
kcp-paired-attestation = {{ path = {kcp_pa:?} }}
kcp-common             = {{ path = {kcp_common:?} }}
hex = "0.4"
"#
    );
    std::fs::write(out.join("Cargo.toml"), content).context("write Cargo.toml")?;
    Ok(())
}

fn write_main_rs(out: &Path, subject_label: &str) -> anyhow::Result<()> {
    let content = format!(
        r#"//! Generated by `kcp scaffold paired-attestation` — pre-production, unaudited, testnet-only.
//!
//! Paired-attestation demo: `{subject_label}`.
//! Demonstrates two-party mate-proof flow using `kcp-paired-attestation`'s
//! pure off-chain functions.
//!
//! Runs entirely offline. No CSFS opcode or live node required.
//!
//! TODO: to publish attestations on-chain with consensus enforcement, integrate
//! with `kcp-paired-attestation::onchain` (two_datasig_redeem_script + datasig)
//! and submit a wRPC transaction to testnet-10.
//! See `crates/kcp-paired-attestation/README.md` and `docs/EVIDENCE.md` [KCP-PA-002].

use kcp_paired_attestation::{{
    mate::{{build_mate_proof, negotiate_blind, verify_mate}},
    record::{{attestation_id, commit, AttestationRecord}},
}};

// Synthetic counterparty data — replace with real values before use.
// TODO: replace SUBJECT_BYTES/TERMS_HASH_BYTES with real document / contract hashes.
const SUBJECT_BYTES: [u8; 32]    = [0x01u8; 32]; // opaque subject id (e.g. document hash)
const TERMS_HASH_BYTES: [u8; 32] = [0x02u8; 32]; // opaque terms hash (e.g. contract SHA-256)

// Synthetic blind shares — 32-byte secrets from each party's CSPRNG.
// TODO: replace with cryptographically secure random bytes in production.
const SHARE_A: [u8; 32] = [0x11u8; 32]; // Party A's random share (kept secret until disclosure)
const SHARE_B: [u8; 32] = [0x22u8; 32]; // Party B's random share (kept secret until disclosure)

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    println!("{subject_label} — paired-attestation mate-proof demo (offline)");

    // [1/5] Create the shared attestation record.
    // Both parties agree on subject, terms_hash, and nonce out-of-band before
    // committing. Nonce distinguishes separate attestation sessions over the
    // same subject and terms.
    let record = AttestationRecord::new(SUBJECT_BYTES, TERMS_HASH_BYTES, 1);
    let aid = attestation_id(&record)?;
    println!("  attestation_id: {{}}", hex::encode(aid));

    // [2/5] Negotiate the combined blind (XOR of both shares).
    // Symmetric: negotiate_blind(A, B) == negotiate_blind(B, A).
    // At least one share must be CSPRNG-derived so neither party can
    // unilaterally predict the combined blind.
    let negotiated_blind = negotiate_blind(SHARE_A, SHARE_B);
    println!("  negotiated_blind: {{}}", hex::encode(negotiated_blind));

    // [3/5] Each party independently computes their commitment.
    // In v0, each party commits under their OWN blind (not the XOR blind).
    // The negotiated_blind is a documented reference design for future protocol
    // versions. See kcp-paired-attestation/src/mate.rs for the rationale.
    let commit_a = commit(&record, &SHARE_A)?;
    let commit_b = commit(&record, &SHARE_B)?;
    println!("  commit_a: {{}}", hex::encode(commit_a));
    println!("  commit_b: {{}}", hex::encode(commit_b));

    // [4/5] Build the mate proof (after both parties disclose blinds off-band).
    // The proof bundles: canonical record bytes + both blinds + both commitments.
    // Privacy note: building the proof discloses the record to the verifier.
    let proof = build_mate_proof(&record, SHARE_A, SHARE_B, commit_a, commit_b)?;

    // [5/5] Verify the mate proof.
    // Checks: attestation_id matches record_bytes hash; commit_a and commit_b
    // both match SHA-256(record_bytes || respective_blind).
    verify_mate(&proof)?;
    println!(
        "✓ PASSED — mate proof verified: both parties committed to the same {subject_label} record"
    );
    Ok(())
}}
"#,
        subject_label = subject_label,
    );
    std::fs::write(out.join("src/main.rs"), content).context("write src/main.rs")?;
    Ok(())
}

fn write_smoke_test(out: &Path) -> anyhow::Result<()> {
    let content = r#"// Generated by `kcp scaffold paired-attestation` — pre-production, unaudited, testnet-only.

use kcp_paired_attestation::{
    mate::{build_mate_proof, negotiate_blind, verify_mate},
    record::{attestation_id, commit, AttestationRecord},
};

const SUBJECT: [u8; 32]     = [0x01u8; 32];
const TERMS: [u8; 32]       = [0x02u8; 32];
const SHARE_A: [u8; 32]     = [0x11u8; 32];
const SHARE_B: [u8; 32]     = [0x22u8; 32];

fn make_proof() -> kcp_paired_attestation::mate::MateProof {
    let record = AttestationRecord::new(SUBJECT, TERMS, 1);
    let c_a = commit(&record, &SHARE_A).unwrap();
    let c_b = commit(&record, &SHARE_B).unwrap();
    build_mate_proof(&record, SHARE_A, SHARE_B, c_a, c_b).unwrap()
}

#[test]
fn valid_proof_verifies() {
    verify_mate(&make_proof()).unwrap();
}

#[test]
fn negotiate_blind_is_symmetric() {
    assert_eq!(
        negotiate_blind(SHARE_A, SHARE_B),
        negotiate_blind(SHARE_B, SHARE_A),
        "negotiate_blind must be symmetric (XOR)"
    );
}

#[test]
fn proof_with_wrong_commit_a_fails() {
    let mut proof = make_proof();
    proof.commit_a = [0xffu8; 32]; // tampered
    assert!(
        verify_mate(&proof).is_err(),
        "tampered commit_a must fail verification"
    );
}

#[test]
fn proof_with_wrong_commit_b_fails() {
    let mut proof = make_proof();
    proof.commit_b = [0xffu8; 32]; // tampered
    assert!(
        verify_mate(&proof).is_err(),
        "tampered commit_b must fail verification"
    );
}

#[test]
fn attestation_id_deterministic() {
    let record = AttestationRecord::new(SUBJECT, TERMS, 1);
    let id1 = attestation_id(&record).unwrap();
    let id2 = attestation_id(&record).unwrap();
    assert_eq!(id1, id2, "attestation_id must be deterministic");
}

#[test]
fn different_nonce_different_id() {
    let r1 = AttestationRecord::new(SUBJECT, TERMS, 1);
    let r2 = AttestationRecord::new(SUBJECT, TERMS, 2);
    let id1 = attestation_id(&r1).unwrap();
    let id2 = attestation_id(&r2).unwrap();
    assert_ne!(id1, id2, "different nonces must produce different attestation_ids");
}
"#;
    std::fs::write(out.join("tests/attestation_smoke.rs"), content)
        .context("write tests/attestation_smoke.rs")?;
    Ok(())
}

fn write_readme(out: &Path, subject_label: &str) -> anyhow::Result<()> {
    let content = format!(
        r#"# my-paired-attestation

**Generated by `kcp scaffold paired-attestation` — pre-production, unaudited, testnet-only.**

A paired-attestation demo: **{subject_label}**.

Demonstrates the two-party mutual attestation (mate-proof) flow using
`kcp-paired-attestation`'s pure off-chain functions. Runs entirely offline.

## Run the demo

```sh
cargo run
cargo test
```

## Mate-proof protocol (v0 off-chain)

1. Both parties agree on an `AttestationRecord` (subject + terms_hash + nonce) off-band.
2. Each party generates a 32-byte random blind share from a CSPRNG.
3. Both shares are exchanged off-band; the combined blind is `share_a XOR share_b`.
4. Each party commits: `commitment = SHA-256(canonical_json(record) || own_blind)`.
5. After both parties disclose blinds, a `MateProof` is built and verified.

`verify_mate` checks that both commitments are consistent with the disclosed
record and blinds — proving both parties committed to the **same** record.

## Privacy note

Building the `MateProof` discloses the record to the verifier. Suitable for
bilateral dispute resolution where both parties consent to disclosure.

## On-chain enforcement (v1 — out of scope for this scaffold)

`kcp-paired-attestation::onchain` provides `two_datasig_redeem_script` and
`datasig` for consensus-enforced two-datasig (`OP_CHECKSIGFROMSTACK`) on
testnet-10. See `docs/EVIDENCE.md [KCP-PA-002]` for live evidence.

## Next steps

- Replace synthetic blind shares with CSPRNG-derived bytes (`OsRng` or equivalent).
- Replace synthetic subject/terms_hash with real document and contract hashes.
- Integrate with `kcp-paired-attestation::onchain` for on-chain CSFS enforcement.
- See `crates/kcp-paired-attestation/README.md` for the full pattern spec.
- Stichting Kii Foundation — MIT licence — pre-production, unaudited.
"#,
        subject_label = subject_label,
    );
    std::fs::write(out.join("README.md"), content).context("write README.md")?;
    Ok(())
}
