//! PQ anchor scaffold — KIP-16 tag-0x21 script assembly demo.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

pub struct PqAnchorConfig {
    pub out_dir: PathBuf,
    pub workspace_path: PathBuf,
}

pub fn generate(cfg: &PqAnchorConfig) -> anyhow::Result<()> {
    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist")?;

    for p in &[
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/pq_anchor_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ] {
        if p.exists() {
            bail!("output file already exists: {:?}", p);
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(&cfg.out_dir)?;
    write_smoke_test(&cfg.out_dir)?;
    write_readme(&cfg.out_dir)?;
    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let dep = ws.join("crates/kcp-pq-anchor");
    std::fs::write(
        out.join("Cargo.toml"),
        format!(
            r#"[package]
name = "my-pq-anchor"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[[bin]]
name = "my-pq-anchor"
path = "src/main.rs"

[dependencies]
kcp-pq-anchor = {{ path = "{}" }}
hex = "0.4"
"#,
            dep.display()
        ),
    )?;
    Ok(())
}

fn write_main_rs(out: &Path) -> anyhow::Result<()> {
    std::fs::write(
        out.join("src/main.rs"),
        r#"//! PQ anchor scaffold — pre-production, unaudited, testnet-only.
//! Generated by `kcp scaffold pq-anchor`.
//!
//! Demonstrates KIP-16 tag-0x21 script assembly. This crate assembles the
//! redeem script only — proof generation requires RISC Zero v3.0.5.

use kcp_pq_anchor::{
    anchor_script::{build_pq_anchor_redeem, PqAnchorScriptFields},
    journal_spec::JournalSpec,
    sigop::sigop_count_for_pq_verify,
};

fn main() {
    // Synthetic proof fields — replace with real RISC Zero guest output.
    let fields = PqAnchorScriptFields {
        claim: vec![0x01u8; 32],
        control_index: 0,
        control_digests: vec![0x02u8; 64], // two 32-byte path digests
        seal: vec![0x03u8; 128],           // real seal is ~222 KB
        journal: JournalSpec::PairedAttestation {
            attestation_id: [0x04u8; 32],
            spend_outpoint: [0x05u8; 36],
        }.journal_hash(),
        image_id: [0x06u8; 32],
        control_id: [0x07u8; 32],
    };

    let script = build_pq_anchor_redeem(&fields)
        .expect("script assembly must succeed");

    println!("=== PQ Anchor scaffold ===");
    println!("    script length : {} bytes", script.len());
    println!("    script (hex)  : {}", hex::encode(&script));
    println!("    sigOpCount    : {} (set this on the spending tx)", sigop_count_for_pq_verify());
    println!();
    println!("NOTE: This scaffold assembles the KIP-16 tag-0x21 redeem script only.");
    println!("      Proof generation requires RISC Zero v3.0.5 + your guest program.");
    println!("Pre-production, unaudited, testnet-only.");
}
"#,
    )?;
    Ok(())
}

fn write_smoke_test(out: &Path) -> anyhow::Result<()> {
    std::fs::write(
        out.join("tests/pq_anchor_smoke.rs"),
        r#"use kcp_pq_anchor::{
    anchor_script::{build_pq_anchor_redeem, PqAnchorScriptFields},
    journal_spec::JournalSpec,
    sigop::sigop_count_for_pq_verify,
};

fn fields() -> PqAnchorScriptFields {
    PqAnchorScriptFields {
        claim: vec![0x01u8; 32],
        control_index: 0,
        control_digests: vec![0x02u8; 64],
        seal: vec![0x03u8; 128],
        journal: [0x04u8; 32],
        image_id: [0x05u8; 32],
        control_id: [0x06u8; 32],
    }
}

#[test]
fn script_assembles_successfully() {
    let script = build_pq_anchor_redeem(&fields()).unwrap();
    assert!(!script.is_empty());
    // Must end with OpZkPrecompile (0xa6) — the in-consensus verifier (NOT OP_0).
    assert_eq!(*script.last().unwrap(), 0xa6);
    // hashfn (Poseidon2 = 1) is a 1-byte DATA push (0x01 0x01), not OP_1.
    assert!(script.windows(2).any(|w| w == [0x01, 0x01]));
}

#[test]
fn sigop_count_is_255() {
    assert_eq!(sigop_count_for_pq_verify(), 255u8);
}

#[test]
fn journal_spec_deterministic() {
    let j1 = JournalSpec::Custom([0xAAu8; 32]).journal_hash();
    let j2 = JournalSpec::Custom([0xAAu8; 32]).journal_hash();
    assert_eq!(j1, j2);
}
"#,
    )?;
    Ok(())
}

fn write_readme(out: &Path) -> anyhow::Result<()> {
    std::fs::write(
        out.join("README.md"),
        r#"# PQ Anchor scaffold

> **Pre-production, unaudited, testnet-only.**

Generated by `kcp scaffold pq-anchor`. Demonstrates KIP-16 tag-0x21
post-quantum credential anchor script assembly.

## Run

```sh
cargo run    # assembles the redeem script from synthetic proof fields
cargo test   # verifies script assembly + sigOpCount + journal determinism
```

## What this does NOT do

This scaffold assembles the redeem script. It does NOT generate a real RISC Zero
proof. Proof generation requires RISC Zero v3.0.5 running your own guest program.

## Before live use

- Replace all synthetic `[0xNNu8; 32]` fields with real RISC Zero guest output.
- The real `seal` is ~222 KB — the 128-byte seal here is for demonstration only.
- Set `sigOpCount = 255` on the spending transaction.
- Use `JournalSpec` matching your pattern: `PairedAttestation`, `SealedLineage`,
  `TransferableRecord`, or `Custom`.
"#,
    )?;
    Ok(())
}
