//! Sealed-lineage scaffold generator — produces a compilable Cargo project
//! demonstrating the genesis → append → validate-chain flow.
//!
//! Runs entirely offline — no UTXO encoding or live node required.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

/// Configuration for a generated sealed-lineage scaffold.
pub struct SealedLineageConfig {
    /// Lineage subject label used in generated comments.
    pub subject: String,
    /// Output directory for the generated project.
    pub out_dir: PathBuf,
    /// Absolute path to the kaspa-compliance-patterns workspace root.
    pub workspace_path: PathBuf,
}

/// Generate a sealed-lineage scaffold project at `cfg.out_dir`.
///
/// Creates `Cargo.toml`, `src/main.rs`, `tests/lineage_smoke.rs`, and `README.md`.
///
/// Fails if any output file already exists.
///
/// **Pre-production, unaudited, testnet-only.**
pub fn generate(cfg: &SealedLineageConfig) -> anyhow::Result<()> {
    if cfg.subject.trim().is_empty() {
        bail!("subject must not be empty");
    }

    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist or is not accessible")?;

    let guard_paths = [
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/lineage_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ];
    for p in &guard_paths {
        if p.exists() {
            bail!(
                "output file already exists: {:?}\n\
                 Use a fresh, empty directory to avoid accidental overwrites.",
                p
            );
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create out_dir/src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create out_dir/tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(&cfg.out_dir, &cfg.subject)?;
    write_smoke_test(&cfg.out_dir)?;
    write_readme(&cfg.out_dir, &cfg.subject)?;

    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let kcp_sl = ws.join("crates/kcp-sealed-lineage");
    let kcp_common = ws.join("crates/kcp-common");
    let content = format!(
        r#"[package]
name = "my-sealed-lineage"
version = "0.1.0"
edition = "2021"
# Generated by `kcp scaffold sealed-lineage` — pre-production, unaudited, testnet-only.
# kcp-sealed-lineage is not yet on crates.io. Use --workspace-path until v0.2 publishes.
# WARNING: path deps below are absolute paths on the generating machine.
publish = false

[workspace]

[dependencies]
kcp-sealed-lineage = {{ path = {kcp_sl:?} }}
kcp-common         = {{ path = {kcp_common:?} }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
hex = "0.4"
"#
    );
    std::fs::write(out.join("Cargo.toml"), content).context("write Cargo.toml")?;
    Ok(())
}

fn write_main_rs(out: &Path, subject: &str) -> anyhow::Result<()> {
    let content = format!(
        r#"//! Generated by `kcp scaffold sealed-lineage` — pre-production, unaudited, testnet-only.
//!
//! Sealed-lineage demo: `{subject}`.
//! Demonstrates genesis → append → validate-chain using
//! `kcp-sealed-lineage`'s pure off-chain functions.
//!
//! Runs entirely offline. No UTXO encoding or live node required.
//!
//! TODO: to commit state on-chain, integrate with `kcp-sealed-lineage::tx`
//! and submit a wRPC transaction to testnet-10.
//! See `crates/kcp-sealed-lineage/README.md` and `docs/EVIDENCE.md` [KCP-SL-003].

use serde::{{Deserialize, Serialize}};
use kcp_sealed_lineage::{{
    invariants::{{validate_chain, APPEND, GENESIS}},
    payload::Payload,
    record::{{lineage_id, commitment}},
}};

/// The identity body for this lineage. Must be stable — changing it changes
/// the `lineage_id` and breaks any on-chain commitments.
///
/// TODO: add domain-specific fields for your use-case.
#[derive(Serialize, Deserialize)]
struct GenesisBody {{
    subject: &'static str,
    version: u8,
}}

/// An evidence record body. Contents are hidden behind a sealed commitment
/// on-chain; only the commitment hash is published.
///
/// TODO: replace with your real evidence schema.
#[derive(Serialize, Deserialize)]
struct EvidenceRecord {{
    event: &'static str,
    value: u64,
}}

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    println!("{subject} — sealed-lineage demo (offline)");

    // [1/4] Establish the lineage_id from the genesis identity body.
    // This id is the SHA-256 of the canonical JSON of the genesis body.
    // Changing the body changes the id — treat it as immutable after genesis.
    let genesis_body = GenesisBody {{ subject: "{subject}", version: 1 }};
    let lid = lineage_id(&genesis_body)?;
    println!("  lineage_id: {{}}",  hex::encode(lid));

    // Synthetic blind values — 32-byte random secrets kept off-chain.
    // TODO: replace with cryptographically secure random bytes in production.
    let blind_genesis: [u8; 32] = [0x01u8; 32];
    let blind_append1: [u8; 32] = [0x02u8; 32];

    // [2/4] Genesis payload — seq = 0, event_class = GENESIS.
    let genesis_record = EvidenceRecord {{ event: "genesis", value: 0 }};
    let c0 = commitment(&genesis_record, &blind_genesis)?;
    let p0 = Payload {{ lineage_id: lid, seq: 0, event_class: GENESIS, t_bucket: 1_000, commitment: c0 }};
    println!("  genesis payload (seq=0): commitment={{}}", hex::encode(c0));

    // [3/4] Append payload — seq = 1, event_class = APPEND.
    let append_record = EvidenceRecord {{ event: "first-append", value: 42 }};
    let c1 = commitment(&append_record, &blind_append1)?;
    let p1 = Payload {{ lineage_id: lid, seq: 1, event_class: APPEND, t_bucket: 2_000, commitment: c1 }};
    println!("  append payload  (seq=1): commitment={{}}", hex::encode(c1));

    // [4/4] Validate the chain (L-1 through L-4 invariants).
    validate_chain(&[p0, p1])?;
    println!(
        "✓ PASSED — sealed-lineage chain [genesis, append] validates all L-1..L-4 invariants"
    );
    Ok(())
}}
"#,
        subject = subject,
    );
    std::fs::write(out.join("src/main.rs"), content).context("write src/main.rs")?;
    Ok(())
}

fn write_smoke_test(out: &Path) -> anyhow::Result<()> {
    let content = r#"// Generated by `kcp scaffold sealed-lineage` — pre-production, unaudited, testnet-only.

use serde::{Deserialize, Serialize};
use kcp_sealed_lineage::{
    invariants::{validate_chain, APPEND, CLOSE, GENESIS},
    payload::Payload,
    record::{lineage_id, commitment},
};

#[derive(Serialize, Deserialize)]
struct GenesisBody { subject: &'static str }

#[derive(Serialize, Deserialize)]
struct EvidenceRecord { event: &'static str, value: u64 }

fn make_chain() -> Vec<Payload> {
    let lid = lineage_id(&GenesisBody { subject: "test" }).unwrap();
    let c0 = commitment(&EvidenceRecord { event: "genesis", value: 0 }, &[0x01u8; 32]).unwrap();
    let c1 = commitment(&EvidenceRecord { event: "append",  value: 1 }, &[0x02u8; 32]).unwrap();
    vec![
        Payload { lineage_id: lid, seq: 0, event_class: GENESIS, t_bucket: 1_000, commitment: c0 },
        Payload { lineage_id: lid, seq: 1, event_class: APPEND,  t_bucket: 2_000, commitment: c1 },
    ]
}

#[test]
fn valid_chain_passes() {
    validate_chain(&make_chain()).unwrap();
}

#[test]
fn chain_with_wrong_seq_rejected() {
    let mut chain = make_chain();
    // Skip seq=1 — gap in sequence must be rejected (L-1).
    chain[1].seq = 2;
    assert!(
        validate_chain(&chain).is_err(),
        "chain with seq gap must fail L-1 monotone-sequence invariant"
    );
}

#[test]
fn chain_with_mismatched_lineage_id_rejected() {
    let mut chain = make_chain();
    chain[1].lineage_id = [0xffu8; 32]; // wrong lineage_id
    assert!(
        validate_chain(&chain).is_err(),
        "chain with mismatched lineage_id must fail L-2 lineage-identity invariant"
    );
}

#[test]
fn payload_encode_decode_round_trip() {
    let chain = make_chain();
    for payload in &chain {
        let encoded = payload.encode();
        let decoded = kcp_sealed_lineage::payload::Payload::decode(&encoded).unwrap();
        assert_eq!(*payload, decoded);
    }
}

#[test]
fn closed_chain_rejects_append() {
    let mut chain = make_chain();
    let lid = chain[0].lineage_id;
    let c2 = [0x03u8; 32];
    // Append a Close event, then try to append after it.
    chain.push(Payload { lineage_id: lid, seq: 2, event_class: CLOSE, t_bucket: 3_000, commitment: c2 });
    chain.push(Payload { lineage_id: lid, seq: 3, event_class: APPEND, t_bucket: 4_000, commitment: [0x04u8; 32] });
    assert!(
        validate_chain(&chain).is_err(),
        "append after Close must fail L-3 event-class invariant"
    );
}
"#;
    std::fs::write(out.join("tests/lineage_smoke.rs"), content)
        .context("write tests/lineage_smoke.rs")?;
    Ok(())
}

fn write_readme(out: &Path, subject: &str) -> anyhow::Result<()> {
    let content = format!(
        r#"# my-sealed-lineage

**Generated by `kcp scaffold sealed-lineage` — pre-production, unaudited, testnet-only.**

A sealed-lineage demo: **{subject}**.

Demonstrates `genesis → append → validate-chain` using `kcp-sealed-lineage`'s
pure off-chain functions. Runs entirely offline.

## Run the demo

```sh
cargo run
cargo test
```

## Chain invariants (L-1 through L-4)

- **L-1** monotone sequence: `seq` starts at 0 and increments by exactly 1.
- **L-2** lineage identity: every event carries the same `lineage_id`.
- **L-3** event-class rules: Genesis only at seq=0; Close is terminal.
- **L-4** temporal envelope: `t_bucket` values non-decreasing, ≤ 90-day step.

## Sealed commitments

Each event commits to an off-chain record body via:
```
commitment = SHA-256(canonical_json(record_body) || blind)
```
The `blind` is a 32-byte secret kept off-chain. Without it, observers
cannot determine the record body from the on-chain commitment alone.

## Next steps

- Replace synthetic blinds with secure random bytes (`OsRng` or equivalent).
- Add UTXO encoding (`kcp-sealed-lineage::tx`) to commit payloads on testnet-10.
- See `crates/kcp-sealed-lineage/README.md` for the full pattern spec.
- See `docs/EVIDENCE.md` for live evidence (`[KCP-SL-003]`).
- Stichting Kii Foundation — MIT licence — pre-production, unaudited.
"#,
        subject = subject,
    );
    std::fs::write(out.join("README.md"), content).context("write README.md")?;
    Ok(())
}
