//! Timelock scaffold generator — produces a compilable Cargo project for a
//! single-key P2SH timelock covenant using DAA-score (`TimelockHeight`).
//!
//! The generated main.rs demonstrates the correct CLTV spend pattern:
//! transaction `lock_time ≥ deadline` AND input `sequence ≠ 0xffffffffffffffff`.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

/// Configuration for a generated timelock scaffold.
pub struct TimelockConfig {
    /// DAA height at or after which the controller may spend.
    pub deadline: u64,
    /// Directory to write the generated project into.
    pub out_dir: PathBuf,
    /// Absolute path to the kaspa-compliance-patterns workspace root.
    /// Used to write path dependencies until crates.io publication.
    pub workspace_path: PathBuf,
}

/// Generate a timelock scaffold project at `cfg.out_dir`.
///
/// Creates `Cargo.toml`, `src/main.rs`, `tests/timelock_smoke.rs`, and
/// `README.md`. Uses `SpendCondition::TimelockHeight` with a single controller
/// key and demonstrates the correct CLTV transaction fields (`lock_time` and
/// `sequence`) required for the engine to accept the spend.
///
/// Fails if any output file already exists — use a fresh directory.
///
/// **Pre-production, unaudited, testnet-only.** Generated code uses a
/// synthetic test keypair and a hard-coded UTXO that never exists on any
/// network.
pub fn generate(cfg: &TimelockConfig) -> anyhow::Result<()> {
    if cfg.deadline == 0 {
        bail!("deadline must be > 0 (a zero deadline is already past and structurally degenerate)");
    }

    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist or is not accessible")?;

    let guard_paths = [
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/timelock_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ];
    for p in &guard_paths {
        if p.exists() {
            bail!(
                "output file already exists: {:?}\n\
                 Use a fresh, empty directory to avoid accidental overwrites.",
                p
            );
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create out_dir/src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create out_dir/tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(&cfg.out_dir, cfg.deadline)?;
    write_smoke_test(&cfg.out_dir, cfg.deadline)?;
    write_readme(&cfg.out_dir, cfg.deadline)?;

    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let kcp_common = ws.join("crates/kcp-common");
    let kcp_vault = ws.join("crates/kcp-vault");
    let content = format!(
        r#"[package]
name = "my-timelock"
version = "0.1.0"
edition = "2021"
# Generated by `kcp scaffold timelock` — pre-production, unaudited, testnet-only.
# kcp-vault is not yet on crates.io. Use --workspace-path until v0.2 publishes.
# Replace path deps with: kcp-vault = {{ version = "0.2" }} once published.
# WARNING: path deps below are absolute paths on the generating machine.
# If you move the kaspa-compliance-patterns workspace, regenerate with kcp scaffold.
publish = false

# Prevents Cargo from merging this project into any parent workspace.
[workspace]

[dependencies]
kcp-common = {{ path = {kcp_common:?}, features = ["wrpc"] }}
kcp-vault   = {{ path = {kcp_vault:?},   features = ["wrpc"] }}
kaspa-consensus-core = {{ git = "https://github.com/kaspanet/rusty-kaspa", tag = "v2.0.0" }}
kaspa-bip32          = {{ git = "https://github.com/kaspanet/rusty-kaspa", tag = "v2.0.0" }}
"#
    );
    std::fs::write(out.join("Cargo.toml"), content).context("write Cargo.toml")?;
    Ok(())
}

fn write_main_rs(out: &Path, deadline: u64) -> anyhow::Result<()> {
    let content = format!(
        r#"//! Generated by `kcp scaffold timelock` — pre-production, unaudited, testnet-only.
//!
//! Single-key P2SH DAA-height timelock covenant demo.
//! Spendable after DAA height {deadline} by the controller key.
//! Runs entirely offline — no live node, no funds, no network.
//! Uses the real rusty-kaspa v2.0.0 script engine.
//!
//! TODO: replace test_keypair(0xA1) with your real controller keypair.
//! See README.md and crates/kcp-vault/README.md for next steps.
//!
//! ## CLTV spend requirements
//!
//! `OP_CHECKLOCKTIMEVERIFY` requires TWO conditions on the spending transaction:
//!   1. `tx.lock_time >= deadline` (height-based: lock_time < 500_000_000_000)
//!   2. `input.sequence != 0xffffffffffffffff` (input must not be finalised)
//!
//! This demo satisfies both: lock_time = {deadline}, sequence = 0.

use kaspa_bip32::secp256k1::{{Keypair, SECP256K1}};
use kaspa_consensus_core::{{
    mass::SigopCount,
    subnets::SUBNETWORK_ID_NATIVE,
    tx::{{
        ComputeCommit, ScriptPublicKey, ScriptVec, Transaction, TransactionId,
        TransactionInput, TransactionOutpoint, TransactionOutput, UtxoEntry,
    }},
}};
use kcp_common::{{
    p2sh::{{
        build_p2sh_signature_script, p2sh_input_sighash, p2sh_lock_script,
        p2sh_redeem_sigop_count, schnorr_satisfier_sig, verify_p2sh_spend_offline,
    }},
    tx::CARRIER_FEE_SOMPI,
}};
// IMPORTANT: use compile_condition_p2sh, NOT compile_condition.
// Kaspa's OP_CHECKLOCKTIMEVERIFY *pops* the deadline (unlike Bitcoin where
// CLTV peeks). compile_condition emits an OP_DROP after CLTV which removes
// the signature instead of the deadline. compile_condition_p2sh omits OP_DROP.
use kcp_vault::{{condition::SpendCondition, onchain::compile_condition_p2sh}};

const LOCK_VALUE_SOMPI: u64 = 200_000_000;

fn test_keypair(byte: u8) -> Keypair {{
    // SYNTHETIC KEY — never use in production. Replace with your real keypair.
    Keypair::from_seckey_slice(SECP256K1, &[byte; 32])
        .expect("32 repeated bytes is a valid secp256k1 secret key")
}}

fn op_true_spk() -> ScriptPublicKey {{
    ScriptPublicKey::new(0, ScriptVec::from_slice(&[0x51]))
}}

fn build_cltv_spend_tx(redeem: &[u8], amount: u64, lock_time: u64) -> (Transaction, UtxoEntry) {{
    let p2sh_spk = p2sh_lock_script(redeem);
    let prev = TransactionOutpoint::new(TransactionId::from_slice(&[0xabu8; 32]), 0);
    // sequence = 0: input must NOT be finalised (0xffffffffffffffff) for CLTV to work.
    let input = TransactionInput::new(prev, vec![], 0, 0);
    let output = TransactionOutput::new(amount - CARRIER_FEE_SOMPI, op_true_spk());
    let mut tx = Transaction::new(
        0,
        vec![input],
        vec![output],
        lock_time, // tx.lock_time must be >= the CLTV deadline
        SUBNETWORK_ID_NATIVE,
        0,
        vec![],
    );
    let sigops = p2sh_redeem_sigop_count(redeem);
    let commit: ComputeCommit = SigopCount(sigops).into();
    for inp in tx.inputs.iter_mut() {{
        inp.compute_commit = commit;
    }}
    let entry = UtxoEntry::new(amount, p2sh_spk, 0, false, None);
    (tx, entry)
}}

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    println!(
        "Generated timelock — single-key CLTV covenant, deadline DAA height {deadline} (offline demo)"
    );

    // [1/5] Build controller keypair (TODO: replace with real key)
    let kp = test_keypair(0xA1);
    let controller_xonly = kp.x_only_public_key().0.serialize();

    let condition = SpendCondition::TimelockHeight {{
        deadline: {deadline},
        controller_xonly,
    }};

    // [2/5] Compile to a P2SH-correct Kaspa redeem script
    let redeem = compile_condition_p2sh(&condition)?;

    // [3/5] Build synthetic spend tx with lock_time = deadline (satisfies CLTV)
    let (mut tx, entry) = build_cltv_spend_tx(&redeem, LOCK_VALUE_SOMPI, {deadline});

    // [4/5] Sign with the controller key
    let sighash = p2sh_input_sighash(&tx, std::slice::from_ref(&entry), 0);
    let sig = schnorr_satisfier_sig(&sighash, &kp);
    tx.inputs[0].signature_script = build_p2sh_signature_script(&[sig], &redeem)?;

    // [5/5] Run through the real rusty-kaspa script engine
    verify_p2sh_spend_offline(&tx, 0, &entry, false)?;
    println!("✓ PASSED — real rusty-kaspa engine accepted the CLTV spend at height {deadline}");
    Ok(())
}}
"#,
        deadline = deadline,
    );
    std::fs::write(out.join("src/main.rs"), content).context("write src/main.rs")?;
    Ok(())
}

fn write_smoke_test(out: &Path, deadline: u64) -> anyhow::Result<()> {
    let content = format!(
        r#"// Generated by `kcp scaffold timelock` — pre-production, unaudited, testnet-only.
//
// Run: cargo test --manifest-path <out_dir>/Cargo.toml
// (fetches rusty-kaspa git dep on first run — requires network)

use kaspa_bip32::secp256k1::{{Keypair, SECP256K1}};
use kaspa_consensus_core::{{
    mass::SigopCount,
    subnets::SUBNETWORK_ID_NATIVE,
    tx::{{
        ComputeCommit, ScriptPublicKey, ScriptVec, Transaction, TransactionId,
        TransactionInput, TransactionOutpoint, TransactionOutput, UtxoEntry,
    }},
}};
use kcp_common::{{
    p2sh::{{
        build_p2sh_signature_script, p2sh_input_sighash, p2sh_lock_script,
        p2sh_redeem_sigop_count, schnorr_satisfier_sig, verify_p2sh_spend_offline,
    }},
    tx::CARRIER_FEE_SOMPI,
}};
// IMPORTANT: use compile_condition_p2sh — Kaspa CLTV pops the deadline.
// See src/main.rs for the full explanation.
use kcp_vault::{{condition::SpendCondition, onchain::compile_condition_p2sh}};

fn test_keypair(byte: u8) -> Keypair {{
    // SYNTHETIC KEY — never use in production.
    Keypair::from_seckey_slice(SECP256K1, &[byte; 32]).unwrap()
}}

fn op_true_spk() -> ScriptPublicKey {{
    ScriptPublicKey::new(0, ScriptVec::from_slice(&[0x51]))
}}

#[test]
fn timelock_height_{deadline}_offline_smoke() {{
    let kp = test_keypair(0xA1);
    let controller_xonly = kp.x_only_public_key().0.serialize();

    let condition = SpendCondition::TimelockHeight {{
        deadline: {deadline},
        controller_xonly,
    }};
    let redeem = compile_condition_p2sh(&condition).unwrap();
    let p2sh_spk = p2sh_lock_script(&redeem);

    let prev = kaspa_consensus_core::tx::TransactionOutpoint::new(
        TransactionId::from_slice(&[0xabu8; 32]), 0,
    );
    // sequence = 0: must not be finalised for CLTV to pass.
    let input = TransactionInput::new(prev, vec![], 0, 0);
    let output = TransactionOutput::new(200_000_000 - CARRIER_FEE_SOMPI, op_true_spk());
    let mut tx = Transaction::new(
        0,
        vec![input],
        vec![output],
        {deadline}, // tx.lock_time >= deadline is required for CLTV
        SUBNETWORK_ID_NATIVE,
        0,
        vec![],
    );
    let sigops = p2sh_redeem_sigop_count(&redeem);
    let commit: ComputeCommit = SigopCount(sigops).into();
    for inp in tx.inputs.iter_mut() {{
        inp.compute_commit = commit;
    }}
    let entry = UtxoEntry::new(200_000_000, p2sh_spk, 0, false, None);
    let sighash = p2sh_input_sighash(&tx, std::slice::from_ref(&entry), 0);
    let sig = schnorr_satisfier_sig(&sighash, &kp);
    tx.inputs[0].signature_script =
        build_p2sh_signature_script(&[sig], &redeem).unwrap();
    verify_p2sh_spend_offline(&tx, 0, &entry, false)
        .expect("engine must accept the CLTV spend at height {deadline}");
}}

#[test]
fn timelock_rejected_before_deadline() {{
    // Spending with lock_time < deadline must be rejected by the engine.
    let kp = test_keypair(0xA1);
    let controller_xonly = kp.x_only_public_key().0.serialize();

    let condition = SpendCondition::TimelockHeight {{
        deadline: {deadline},
        controller_xonly,
    }};
    let redeem = compile_condition_p2sh(&condition).unwrap();
    let p2sh_spk = p2sh_lock_script(&redeem);

    let prev = kaspa_consensus_core::tx::TransactionOutpoint::new(
        TransactionId::from_slice(&[0xabu8; 32]), 0,
    );
    let input = TransactionInput::new(prev, vec![], 0, 0);
    let output = TransactionOutput::new(200_000_000 - CARRIER_FEE_SOMPI, op_true_spk());
    // lock_time = deadline - 1: spend must be rejected.
    let early_lock_time = {deadline}.saturating_sub(1);
    let mut tx = Transaction::new(
        0,
        vec![input],
        vec![output],
        early_lock_time,
        SUBNETWORK_ID_NATIVE,
        0,
        vec![],
    );
    let sigops = p2sh_redeem_sigop_count(&redeem);
    let commit: ComputeCommit = SigopCount(sigops).into();
    for inp in tx.inputs.iter_mut() {{
        inp.compute_commit = commit;
    }}
    let entry = UtxoEntry::new(200_000_000, p2sh_spk, 0, false, None);
    let sighash = p2sh_input_sighash(&tx, std::slice::from_ref(&entry), 0);
    let sig = schnorr_satisfier_sig(&sighash, &kp);
    tx.inputs[0].signature_script =
        build_p2sh_signature_script(&[sig], &redeem).unwrap();
    assert!(
        verify_p2sh_spend_offline(&tx, 0, &entry, false).is_err(),
        "engine must reject CLTV spend before deadline"
    );
}}
"#,
        deadline = deadline,
    );
    std::fs::write(out.join("tests/timelock_smoke.rs"), content)
        .context("write tests/timelock_smoke.rs")?;
    Ok(())
}

fn write_readme(out: &Path, deadline: u64) -> anyhow::Result<()> {
    let content = format!(
        r#"# my-timelock

**Pre-production, unaudited, testnet-only.**
Generated by `kcp scaffold timelock` from the
[kaspa-compliance-patterns](https://github.com/kii-foundation/kaspa-compliance-patterns) library.

## What this is

A single-key P2SH DAA-height timelock covenant scaffold. The controller key
may spend the UTXO only after the chain reaches DAA height **{deadline}**.

The generated `src/main.rs` and `tests/timelock_smoke.rs` run entirely offline
using the real rusty-kaspa v2.0.0 script engine — no live node, no funds, no
network.

## CLTV spend requirements

`OP_CHECKLOCKTIMEVERIFY` needs both:
1. `tx.lock_time >= {deadline}` and `lock_time < 500_000_000_000` (height-based)
2. `input.sequence != 0xffffffffffffffff` (input must not be finalised)

The generated code satisfies both. If you set `lock_time < {deadline}` the engine
rejects the spend — the negative test in `tests/timelock_smoke.rs` verifies this.

## Before you use this

1. **Replace synthetic key.** `test_keypair(0xA1)` is a known test vector.
   Replace it with your real secp256k1 controller keypair.
2. **Network on first run.** The first `cargo test` fetches the `rusty-kaspa`
   git dependency (tag v2.0.0). Subsequent runs use the cache.
3. **Path dependencies are absolute.** Regenerate if you move the workspace.

## Running

```sh
cargo run     # offline demo
cargo test    # offline tests (positive + negative CLTV cases)
```

## Next steps

- `crates/kcp-vault/README.md` — composite conditions (Timelock + MultiSig)
- `crates/kcp-common/src/security.rs` — `TimelockController` EVM equivalent
- `examples/hello-vault/` — the canonical 2-of-2 multisig reference

## Licence

MIT — Stichting Kii Foundation (non-profit, incorporated 2026-06-21).
"#,
        deadline = deadline,
    );
    std::fs::write(out.join("README.md"), content).context("write README.md")?;
    Ok(())
}
