//! Transferable-record scaffold generator — produces a compilable Cargo project
//! demonstrating the genesis → transfer → validate-chain flow.
//!
//! Runs entirely offline — no UTXO encoding or live node required.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

/// Configuration for a generated transferable-record scaffold.
pub struct TransferableRecordConfig {
    /// Record type label used in generated comments.
    pub record_type: String,
    /// Output directory for the generated project.
    pub out_dir: PathBuf,
    /// Absolute path to the kaspa-compliance-patterns workspace root.
    pub workspace_path: PathBuf,
}

/// Generate a transferable-record scaffold project at `cfg.out_dir`.
///
/// Creates `Cargo.toml`, `src/main.rs`, `tests/record_smoke.rs`, and `README.md`.
///
/// Fails if any output file already exists.
///
/// **Pre-production, unaudited, testnet-only.**
pub fn generate(cfg: &TransferableRecordConfig) -> anyhow::Result<()> {
    if cfg.record_type.trim().is_empty() {
        bail!("record_type must not be empty");
    }

    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist or is not accessible")?;

    let guard_paths = [
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/record_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ];
    for p in &guard_paths {
        if p.exists() {
            bail!(
                "output file already exists: {:?}\n\
                 Use a fresh, empty directory to avoid accidental overwrites.",
                p
            );
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create out_dir/src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create out_dir/tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(&cfg.out_dir, &cfg.record_type)?;
    write_smoke_test(&cfg.out_dir)?;
    write_readme(&cfg.out_dir, &cfg.record_type)?;

    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let kcp_tr = ws.join("crates/kcp-transferable-record");
    let kcp_common = ws.join("crates/kcp-common");
    let content = format!(
        r#"[package]
name = "my-transferable-record"
version = "0.1.0"
edition = "2021"
# Generated by `kcp scaffold transferable-record` — pre-production, unaudited, testnet-only.
# kcp-transferable-record is not yet on crates.io. Use --workspace-path until v0.2 publishes.
# WARNING: path deps below are absolute paths on the generating machine.
publish = false

[workspace]

[dependencies]
kcp-transferable-record = {{ path = {kcp_tr:?} }}
kcp-common              = {{ path = {kcp_common:?} }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
hex = "0.4"
"#
    );
    std::fs::write(out.join("Cargo.toml"), content).context("write Cargo.toml")?;
    Ok(())
}

fn write_main_rs(out: &Path, record_type: &str) -> anyhow::Result<()> {
    let content = format!(
        r#"//! Generated by `kcp scaffold transferable-record` — pre-production, unaudited, testnet-only.
//!
//! Transferable-record demo: `{record_type}`.
//! Demonstrates genesis → two transfers → validate-chain using
//! `kcp-transferable-record`'s pure off-chain functions.
//!
//! Runs entirely offline. No UTXO encoding or live node required.
//!
//! TODO: to commit transfers on-chain, integrate with `kcp-transferable-record::tx`
//! and submit wRPC transactions to testnet-10.
//! See `crates/kcp-transferable-record/README.md` and `docs/EVIDENCE.md` [KCP-TR-003].

use serde::{{Deserialize, Serialize}};
use kcp_transferable_record::{{
    lineage::{{validate_chain, TransferEvent}},
    record::{{commitment, record_id}},
}};

// Synthetic x-only public keys — 32-byte controller identifiers.
// TODO: replace with real Schnorr public keys before use.
const GENESIS_CONTROLLER: [u8; 32] = [0xC0u8; 32]; // initial owner
const OWNER_A: [u8; 32]           = [0x01u8; 32]; // first transferee
const OWNER_B: [u8; 32]           = [0x02u8; 32]; // second transferee

/// The genesis body for this record. Its SHA-256 hash becomes the `record_id`.
/// Must be stable — changing it changes the `record_id`.
///
/// TODO: add domain-specific fields for your use-case.
#[derive(Serialize, Deserialize)]
struct GenesisBody {{
    record_type: &'static str,
    issuer: &'static str,
}}

/// An event body committed to in each transfer.
/// Contents are kept off-chain; only the SHA-256 commitment is on-chain.
///
/// TODO: replace with your real event schema.
#[derive(Serialize, Deserialize)]
struct EventBody {{
    action: &'static str,
    notes: &'static str,
}}

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    println!("{record_type} — transferable-record demo (offline)");

    // [1/4] Compute the record_id from the genesis body.
    // This id is the SHA-256 of the canonical JSON of the genesis body.
    // It is stable across all transfers — treat it as immutable after genesis.
    let genesis_body = GenesisBody {{ record_type: "{record_type}", issuer: "Kii-demo" }};
    let rid = record_id(&genesis_body)?;
    println!("  record_id:  {{}}", hex::encode(rid));

    // [2/4] Genesis → OWNER_A (seq=1): first transfer event.
    let body1 = EventBody {{ action: "issue", notes: "initial assignment" }};
    let c1 = commitment(&body1)?;
    let ev1 = TransferEvent {{ seq: 1, record_id: rid, controller_xonly: OWNER_A, commitment: c1 }};
    println!("  transfer 1 (→ OWNER_A): commitment={{}}", hex::encode(c1));

    // [3/4] OWNER_A → OWNER_B (seq=2): second transfer event.
    let body2 = EventBody {{ action: "transfer", notes: "on-sale reassignment" }};
    let c2 = commitment(&body2)?;
    let ev2 = TransferEvent {{ seq: 2, record_id: rid, controller_xonly: OWNER_B, commitment: c2 }};
    println!("  transfer 2 (→ OWNER_B): commitment={{}}", hex::encode(c2));

    // [4/4] Validate the chain (TR-1 through TR-3 invariants).
    validate_chain(&GENESIS_CONTROLLER, &[ev1, ev2])?;
    println!(
        "✓ PASSED — transfer chain [issue, transfer] validates all TR-1..TR-3 invariants"
    );
    Ok(())
}}
"#,
        record_type = record_type,
    );
    std::fs::write(out.join("src/main.rs"), content).context("write src/main.rs")?;
    Ok(())
}

fn write_smoke_test(out: &Path) -> anyhow::Result<()> {
    let content = r#"// Generated by `kcp scaffold transferable-record` — pre-production, unaudited, testnet-only.

use serde::{Deserialize, Serialize};
use kcp_transferable_record::{
    lineage::{validate_chain, TransferEvent},
    record::{commitment, record_id},
};

const GENESIS_CONTROLLER: [u8; 32] = [0xC0u8; 32];
const OWNER_A: [u8; 32] = [0x01u8; 32];
const OWNER_B: [u8; 32] = [0x02u8; 32];

#[derive(Serialize, Deserialize)]
struct GenesisBody {
    record_type: &'static str,
}

#[derive(Serialize, Deserialize)]
struct EventBody {
    action: &'static str,
}

fn make_chain() -> (Vec<TransferEvent>, [u8; 32]) {
    let rid = record_id(&GenesisBody { record_type: "test" }).unwrap();
    let c1 = commitment(&EventBody { action: "issue" }).unwrap();
    let c2 = commitment(&EventBody { action: "transfer" }).unwrap();
    let events = vec![
        TransferEvent { seq: 1, record_id: rid, controller_xonly: OWNER_A, commitment: c1 },
        TransferEvent { seq: 2, record_id: rid, controller_xonly: OWNER_B, commitment: c2 },
    ];
    (events, rid)
}

#[test]
fn valid_chain_passes() {
    let (events, _) = make_chain();
    validate_chain(&GENESIS_CONTROLLER, &events).unwrap();
}

#[test]
fn empty_chain_passes() {
    // A record that has never been transferred is valid.
    validate_chain(&GENESIS_CONTROLLER, &[]).unwrap();
}

#[test]
fn chain_with_seq_gap_rejected() {
    let (mut events, _) = make_chain();
    // Skip seq=1 by setting seq=2 on the first event — must fail TR-1.
    events[0].seq = 2;
    assert!(
        validate_chain(&GENESIS_CONTROLLER, &events).is_err(),
        "seq gap must fail TR-1 monotone-sequence invariant"
    );
}

#[test]
fn chain_with_mismatched_record_id_rejected() {
    let (mut events, _) = make_chain();
    events[1].record_id = [0xffu8; 32]; // wrong record_id
    assert!(
        validate_chain(&GENESIS_CONTROLLER, &events).is_err(),
        "mismatched record_id must fail TR-2 record-identity invariant"
    );
}

#[test]
fn chain_with_zero_commitment_rejected() {
    let (mut events, _) = make_chain();
    events[0].commitment = [0u8; 32]; // all-zero commitment rejected
    assert!(
        validate_chain(&GENESIS_CONTROLLER, &events).is_err(),
        "all-zero commitment must fail TR-3 structural sanity check"
    );
}

#[test]
fn payload_encode_decode_round_trip() {
    let (events, rid) = make_chain();
    for ev in &events {
        let payload = kcp_transferable_record::payload::Payload {
            record_id: rid,
            seq: ev.seq,
            commitment: ev.commitment,
        };
        let encoded = payload.encode();
        let decoded = kcp_transferable_record::payload::Payload::decode(&encoded).unwrap();
        assert_eq!(payload, decoded);
    }
}
"#;
    std::fs::write(out.join("tests/record_smoke.rs"), content)
        .context("write tests/record_smoke.rs")?;
    Ok(())
}

fn write_readme(out: &Path, record_type: &str) -> anyhow::Result<()> {
    let content = format!(
        r#"# my-transferable-record

**Generated by `kcp scaffold transferable-record` — pre-production, unaudited, testnet-only.**

A transferable-record demo: **{record_type}**.

Demonstrates `genesis → transfer → validate-chain` using `kcp-transferable-record`'s
pure off-chain functions. Runs entirely offline.

## Run the demo

```sh
cargo run
cargo test
```

## Chain invariants (TR-1 through TR-3)

- **TR-1** monotone sequence: first transfer has `seq = 1`, increments by exactly 1.
- **TR-2** record identity: every transfer event carries the same `record_id`.
- **TR-3** payload consistency: `commitment` must be non-zero (structural sanity).

## Record identity

The `record_id` is `SHA-256(canonical_json(genesis_body))`. It is immutable after
genesis — changing the genesis body changes the id and invalidates the chain.

## Next steps

- Replace synthetic controller keys with real Schnorr public keys.
- Add UTXO encoding (`kcp-transferable-record::tx`) to commit transfers on testnet-10.
- See `crates/kcp-transferable-record/README.md` for the full pattern spec.
- See `docs/EVIDENCE.md` for live evidence (`[KCP-TR-003]`).
- Stichting Kii Foundation — MIT licence — pre-production, unaudited.
"#,
        record_type = record_type,
    );
    std::fs::write(out.join("README.md"), content).context("write README.md")?;
    Ok(())
}
