//! Vault scaffold generator — produces a compilable Cargo project for a
//! P2SH multisig vault covenant.
//!
//! Generated projects mirror the `hello-vault` example and depend on
//! `kcp-vault` + `kcp-common` via path dependencies (pre-crates.io) or
//! git/registry refs (post-v0.2).

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

/// Configuration for a generated vault scaffold.
pub struct VaultConfig {
    /// k-of-n threshold (≥ 1, ≤ keys.len()).
    pub threshold: u8,
    /// Key labels (used as comments in generated code; not real pubkeys in v0).
    pub keys: Vec<String>,
    /// Directory to write the generated project into.
    pub out_dir: PathBuf,
    /// Absolute path to the kaspa-compliance-patterns workspace root.
    /// Used to write path dependencies until crates.io publication.
    pub workspace_path: PathBuf,
}

/// Generate a vault scaffold project at `cfg.out_dir`.
///
/// Creates `Cargo.toml`, `src/main.rs`, `tests/vault_smoke.rs`, and
/// `README.md`. The generated project compiles with `cargo check` (or
/// `cargo test`) using path deps to the local library workspace.
///
/// Fails if any output file already exists — use a fresh directory to prevent
/// accidental overwrites.
///
/// **Pre-production, unaudited, testnet-only.** Generated code uses synthetic
/// test keypairs and a hard-coded UTXO that never exists on any network.
pub fn generate(cfg: &VaultConfig) -> anyhow::Result<()> {
    let n = cfg.keys.len();
    let t = cfg.threshold as usize;
    if n == 0 {
        bail!("vault scaffold requires at least one key label");
    }
    if t == 0 || t > n {
        bail!("threshold {t} must be ≥ 1 and ≤ keys count {n}");
    }

    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist or is not accessible")?;

    // Guard: refuse to overwrite existing files.
    let guard_paths = [
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/vault_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ];
    for p in &guard_paths {
        if p.exists() {
            bail!(
                "output file already exists: {:?}\n\
                 Use a fresh, empty directory to avoid accidental overwrites.",
                p
            );
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create out_dir/src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create out_dir/tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(&cfg.out_dir, cfg.threshold, &cfg.keys)?;
    write_smoke_test(&cfg.out_dir, cfg.threshold, n)?;
    write_readme(&cfg.out_dir, cfg.threshold, n)?;

    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let kcp_common = ws.join("crates/kcp-common");
    let kcp_vault = ws.join("crates/kcp-vault");
    let content = format!(
        r#"[package]
name = "my-vault"
version = "0.1.0"
edition = "2021"
# Generated by `kcp scaffold vault` — pre-production, unaudited, testnet-only.
# kcp-vault is not yet on crates.io. Use --workspace-path until v0.2 publishes.
# Replace path deps with: kcp-vault = {{ version = "0.2" }} once published.
# WARNING: path deps below are absolute paths on the generating machine.
# If you move the kaspa-compliance-patterns workspace, regenerate with kcp scaffold.
publish = false

# Prevents Cargo from merging this project into any parent workspace.
[workspace]

[dependencies]
kcp-common = {{ path = {kcp_common:?}, features = ["wrpc"] }}
kcp-vault   = {{ path = {kcp_vault:?},   features = ["wrpc"] }}
kaspa-consensus-core = {{ git = "https://github.com/kaspanet/rusty-kaspa", tag = "v2.0.0" }}
kaspa-bip32          = {{ git = "https://github.com/kaspanet/rusty-kaspa", tag = "v2.0.0" }}
"#
    );
    std::fs::write(out.join("Cargo.toml"), content).context("write Cargo.toml")?;
    Ok(())
}

fn write_main_rs(out: &Path, threshold: u8, keys: &[String]) -> anyhow::Result<()> {
    let n = keys.len();
    let t = threshold as usize;
    // Key-label comment block
    let key_comments: String = keys
        .iter()
        .enumerate()
        .map(|(i, k)| {
            format!(
                "// Key {i1}: {k} → test_keypair(0x{byte:02x})\n",
                i1 = i + 1,
                byte = 0xA0u8 + (i as u8 + 1)
            )
        })
        .collect();
    // All n keypairs declared (needed to extract public keys for the SpendCondition).
    let kp_decls: String = (0..n)
        .map(|i| {
            format!(
                "    let kp{i1} = test_keypair(0x{byte:02x});\n",
                i1 = i + 1,
                byte = 0xA0u8 + (i as u8 + 1)
            )
        })
        .collect();
    // Public key extractions — all n are in the script.
    let pk_decls: String = (0..n)
        .map(|i| {
            format!(
                "    let pk{i1} = kp{i1}.x_only_public_key().0.serialize();\n",
                i1 = i + 1
            )
        })
        .collect();
    // xonly_keys vec — all n public keys lock the script.
    let pk_vec: String = (0..n)
        .map(|i| format!("pk{}", i + 1))
        .collect::<Vec<_>>()
        .join(", ");
    // Signature declarations — only the first `threshold` signers are needed at spend time.
    // Keys [threshold+1..n] are additional recovery signers; you do not need them all.
    let sig_decls: String = (0..t)
        .map(|i| {
            format!(
                "    let sig{i1} = schnorr_satisfier_sig(&sighash, &kp{i1});\n",
                i1 = i + 1
            )
        })
        .collect();
    let sigs_vec: String = (0..t)
        .map(|i| format!("sig{}", i + 1))
        .collect::<Vec<_>>()
        .join(", ");

    let content = format!(
        r#"//! Generated by `kcp scaffold vault` — pre-production, unaudited, testnet-only.
//!
//! {threshold}-of-{n} multisig P2SH vault demo.
//! Runs entirely offline — no live node, no funds, no network.
//! Uses the real rusty-kaspa v2.0.0 script engine.
//!
{key_comments}//
//! TODO: replace test_keypair(0xNN) with your real keys before production use.
//! See README.md and crates/kcp-vault/README.md for next steps.

use kaspa_bip32::secp256k1::{{Keypair, SECP256K1}};
use kaspa_consensus_core::{{
    mass::SigopCount,
    subnets::SUBNETWORK_ID_NATIVE,
    tx::{{
        ComputeCommit, ScriptPublicKey, ScriptVec, Transaction, TransactionId,
        TransactionInput, TransactionOutpoint, TransactionOutput, UtxoEntry,
    }},
}};
use kcp_common::{{
    p2sh::{{
        build_p2sh_signature_script, p2sh_input_sighash, p2sh_lock_script,
        p2sh_redeem_sigop_count, schnorr_satisfier_sig, verify_p2sh_spend_offline,
    }},
    tx::CARRIER_FEE_SOMPI,
}};
use kcp_vault::{{condition::SpendCondition, script::compile_condition}};

const LOCK_VALUE_SOMPI: u64 = 200_000_000;

fn test_keypair(byte: u8) -> Keypair {{
    // SYNTHETIC KEY — never use in production. Replace with your real keypair.
    Keypair::from_seckey_slice(SECP256K1, &[byte; 32])
        .expect("32 repeated bytes is a valid secp256k1 secret key")
}}

fn op_true_spk() -> ScriptPublicKey {{
    ScriptPublicKey::new(0, ScriptVec::from_slice(&[0x51]))
}}

fn build_spend_tx(redeem: &[u8], amount: u64) -> (Transaction, UtxoEntry) {{
    let p2sh_spk = p2sh_lock_script(redeem);
    let prev = TransactionOutpoint::new(TransactionId::from_slice(&[0xabu8; 32]), 0);
    let input = TransactionInput::new(prev, vec![], 0, 0);
    let output = TransactionOutput::new(amount - CARRIER_FEE_SOMPI, op_true_spk());
    let mut tx = Transaction::new(0, vec![input], vec![output], 0, SUBNETWORK_ID_NATIVE, 0, vec![]);
    let sigops = p2sh_redeem_sigop_count(redeem);
    let commit: ComputeCommit = SigopCount(sigops).into();
    for inp in tx.inputs.iter_mut() {{
        inp.compute_commit = commit;
    }}
    let entry = UtxoEntry::new(amount, p2sh_spk, 0, false, None);
    (tx, entry)
}}

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    println!("Generated vault — {threshold}-of-{n} multisig P2SH covenant (offline demo)");

    // [1/5] Build keypairs (TODO: replace with real keys)
{kp_decls}
    // Extract x-only public keys for the lock script.
    // All {n} public keys are embedded in the P2SH redeem script.
{pk_decls}    let condition = SpendCondition::MultiSig {{
        threshold: {threshold},
        xonly_keys: vec![{pk_vec}],
    }};

    // [2/5] Compile to a real Kaspa redeem script
    let redeem = compile_condition(&condition)?;

    // [3/5] Build synthetic spend tx + P2SH-locked UTXO
    let (mut tx, entry) = build_spend_tx(&redeem, LOCK_VALUE_SOMPI);

    // [4/5] Sign with the first {threshold} key(s) — any {threshold}-of-{n} subset suffices.
    //       Keys [{threshold_plus_one}..{n}] are additional recovery signers; not required here.
    let sighash = p2sh_input_sighash(&tx, std::slice::from_ref(&entry), 0);
{sig_decls}    tx.inputs[0].signature_script = build_p2sh_signature_script(&[{sigs_vec}], &redeem)?;

    // [5/5] Run through the real rusty-kaspa script engine
    verify_p2sh_spend_offline(&tx, 0, &entry, false)?;
    println!("✓ PASSED — real rusty-kaspa engine accepted the {threshold}-of-{n} spend");
    Ok(())
}}
"#,
        threshold = threshold,
        n = n,
        key_comments = key_comments,
        kp_decls = kp_decls,
        pk_decls = pk_decls,
        pk_vec = pk_vec,
        sig_decls = sig_decls,
        sigs_vec = sigs_vec,
        threshold_plus_one = t + 1,
    );
    std::fs::write(out.join("src/main.rs"), content).context("write src/main.rs")?;
    Ok(())
}

fn write_smoke_test(out: &Path, threshold: u8, n: usize) -> anyhow::Result<()> {
    let t = threshold as usize;
    let kp_decls: String = (0..n)
        .map(|i| {
            let i1 = i + 1;
            let byte = 0xA0u8 + (i as u8 + 1);
            format!("    let kp{i1} = test_keypair(0x{byte:02x});\n")
        })
        .collect();
    let pk_decls: String = (0..n)
        .map(|i| {
            format!(
                "    let pk{i1} = kp{i1}.x_only_public_key().0.serialize();\n",
                i1 = i + 1
            )
        })
        .collect();
    let pk_vec: String = (0..n)
        .map(|i| format!("pk{}", i + 1))
        .collect::<Vec<_>>()
        .join(", ");
    // Only threshold signatures at spend time.
    let sig_decls: String = (0..t)
        .map(|i| {
            format!(
                "    let sig{i1} = schnorr_satisfier_sig(&sighash, &kp{i1});\n",
                i1 = i + 1
            )
        })
        .collect();
    let sigs_vec: String = (0..t)
        .map(|i| format!("sig{}", i + 1))
        .collect::<Vec<_>>()
        .join(", ");

    let content = format!(
        r#"// Generated by `kcp scaffold vault` — pre-production, unaudited, testnet-only.
//
// Run: cargo test --manifest-path <out_dir>/Cargo.toml
// (fetches rusty-kaspa git dep on first run — requires network)

use kaspa_bip32::secp256k1::{{Keypair, SECP256K1}};
use kaspa_consensus_core::{{
    mass::SigopCount,
    subnets::SUBNETWORK_ID_NATIVE,
    tx::{{
        ComputeCommit, ScriptPublicKey, ScriptVec, Transaction, TransactionId,
        TransactionInput, TransactionOutpoint, TransactionOutput, UtxoEntry,
    }},
}};
use kcp_common::{{
    p2sh::{{
        build_p2sh_signature_script, p2sh_input_sighash, p2sh_lock_script,
        p2sh_redeem_sigop_count, schnorr_satisfier_sig, verify_p2sh_spend_offline,
    }},
    tx::CARRIER_FEE_SOMPI,
}};
use kcp_vault::{{condition::SpendCondition, script::compile_condition}};

fn test_keypair(byte: u8) -> Keypair {{
    // SYNTHETIC KEY — never use in production.
    Keypair::from_seckey_slice(SECP256K1, &[byte; 32]).unwrap()
}}

fn op_true_spk() -> ScriptPublicKey {{
    ScriptPublicKey::new(0, ScriptVec::from_slice(&[0x51]))
}}

#[test]
fn vault_{threshold}of{n}_offline_smoke() {{
    // All {n} keypairs defined — their public keys lock the script.
{kp_decls}{pk_decls}
    let condition = SpendCondition::MultiSig {{
        threshold: {threshold},
        xonly_keys: vec![{pk_vec}],
    }};
    let redeem = compile_condition(&condition).unwrap();
    let p2sh_spk = p2sh_lock_script(&redeem);
    let prev = kaspa_consensus_core::tx::TransactionOutpoint::new(
        TransactionId::from_slice(&[0xabu8; 32]), 0,
    );
    let input = TransactionInput::new(prev, vec![], 0, 0);
    let output = TransactionOutput::new(200_000_000 - CARRIER_FEE_SOMPI, op_true_spk());
    let mut tx = Transaction::new(0, vec![input], vec![output], 0, SUBNETWORK_ID_NATIVE, 0, vec![]);
    let sigops = p2sh_redeem_sigop_count(&redeem);
    let commit: ComputeCommit = SigopCount(sigops).into();
    for inp in tx.inputs.iter_mut() {{
        inp.compute_commit = commit;
    }}
    let entry = UtxoEntry::new(200_000_000, p2sh_spk, 0, false, None);
    let sighash = p2sh_input_sighash(&tx, std::slice::from_ref(&entry), 0);
    // Only {threshold} signatures needed — first {threshold} key(s) used here.
{sig_decls}
    tx.inputs[0].signature_script =
        build_p2sh_signature_script(&[{sigs_vec}], &redeem).unwrap();
    verify_p2sh_spend_offline(&tx, 0, &entry, false)
        .expect("engine must accept the {threshold}-of-{n} spend");
}}
"#,
        threshold = threshold,
        n = n,
        kp_decls = kp_decls,
        pk_decls = pk_decls,
        pk_vec = pk_vec,
        sig_decls = sig_decls,
        sigs_vec = sigs_vec,
    );
    std::fs::write(out.join("tests/vault_smoke.rs"), content)
        .context("write tests/vault_smoke.rs")?;
    Ok(())
}

fn write_readme(out: &Path, threshold: u8, n: usize) -> anyhow::Result<()> {
    let content = format!(
        r#"# my-vault

**Pre-production, unaudited, testnet-only.**
Generated by `kcp scaffold vault` from the
[kaspa-compliance-patterns](https://github.com/kii-foundation/kaspa-compliance-patterns) library.

## What this is

A {threshold}-of-{n} multisig P2SH vault covenant scaffold. The generated
`src/main.rs` and `tests/vault_smoke.rs` run entirely offline using the real
rusty-kaspa v2.0.0 script engine — no live node, no funds, no network.

## Before you use this

1. **Replace synthetic keys.** Every `test_keypair(0xNN)` call uses a hardcoded
   test vector. Replace these with your real secp256k1 keypairs before any
   mainnet or testnet use.

2. **Network on first run.** The first `cargo test` fetches the `rusty-kaspa`
   git dependency (tag v2.0.0). Subsequent runs use the cache.

3. **Path dependencies are absolute.** The `Cargo.toml` path deps point to the
   `kaspa-compliance-patterns` workspace at the path it was on the generating
   machine. If you move the workspace, regenerate with `kcp scaffold vault`.

## Running

```sh
# offline demo (no network after git dep is cached)
cargo run

# offline test
cargo test
```

## Next steps

- `crates/kcp-vault/README.md` — full MultiSig / Timelock / Composite patterns
- `crates/kcp-common/README.md` — access, security, and cryptography primitives
- `examples/hello-vault/` — the canonical 2-of-2 reference example

## Licence

MIT — Stichting Kii Foundation (non-profit, incorporated 2026-06-21).
"#,
        threshold = threshold,
        n = n,
    );
    std::fs::write(out.join("README.md"), content).context("write README.md")?;
    Ok(())
}
