//! Vesting scaffold — VestingSchedule linear release demo.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

pub struct VestingConfig {
    pub start: u64,
    pub duration: u64,
    pub total_amount: u64,
    pub out_dir: PathBuf,
    pub workspace_path: PathBuf,
}

pub fn generate(cfg: &VestingConfig) -> anyhow::Result<()> {
    if cfg.duration == 0 {
        bail!("duration must be > 0");
    }
    if cfg.total_amount == 0 {
        bail!("total_amount must be > 0");
    }

    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist")?;

    for p in &[
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/vesting_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ] {
        if p.exists() {
            bail!("output file already exists: {:?}", p);
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(&cfg.out_dir, cfg.start, cfg.duration, cfg.total_amount)?;
    write_smoke_test(&cfg.out_dir, cfg.start, cfg.duration, cfg.total_amount)?;
    write_readme(&cfg.out_dir, cfg.start, cfg.duration, cfg.total_amount)?;
    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let dep = ws.join("crates/kcp-vesting");
    std::fs::write(
        out.join("Cargo.toml"),
        format!(
            r#"[package]
name = "my-vesting"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[[bin]]
name = "my-vesting"
path = "src/main.rs"

[dependencies]
kcp-vesting = {{ path = "{}" }}
"#,
            dep.display()
        ),
    )?;
    Ok(())
}

fn write_main_rs(out: &Path, start: u64, duration: u64, total_amount: u64) -> anyhow::Result<()> {
    let halfway = start + duration / 2;
    let end = start + duration;
    std::fs::write(
        out.join("src/main.rs"),
        format!(
            r#"//! Vesting scaffold — pre-production, unaudited, testnet-only.
//! Generated by `kcp scaffold vesting`.

use kcp_vesting::schedule::VestingSchedule;

fn main() {{
    // Synthetic beneficiary key — replace with a real Schnorr x-only public key.
    let beneficiary = [0x01u8; 32];

    let schedule = VestingSchedule::new(beneficiary, {start}, {duration}, {total_amount})
        .expect("valid schedule");

    println!("=== Vesting schedule ===");
    println!("    start     : DAA height {start}");
    println!("    end       : DAA height {end}");
    println!("    total     : {total_amount} sompi");

    // Before start — nothing releasable
    println!("    releasable at {start}: {{}}", schedule.releasable({start}));

    // Halfway through vesting
    let (s2, released) = schedule.release({halfway}).expect("something to release");
    println!("    released at {halfway}: {{released}} sompi");

    // After full vest
    let (_, final_release) = s2.release({end} + 1).expect("remainder");
    println!("    released at {end}+1: {{final_release}} sompi");
    println!("Pre-production, unaudited, testnet-only.");
}}
"#,
            start = start,
            duration = duration,
            total_amount = total_amount,
            halfway = halfway,
            end = end
        ),
    )?;
    Ok(())
}

fn write_smoke_test(
    out: &Path,
    start: u64,
    duration: u64,
    total_amount: u64,
) -> anyhow::Result<()> {
    let end = start + duration;
    std::fs::write(
        out.join("tests/vesting_smoke.rs"),
        format!(
            r#"use kcp_vesting::schedule::VestingSchedule;

fn beneficiary() -> [u8; 32] {{ [0x01u8; 32] }}

#[test]
fn nothing_before_start() {{
    let s = VestingSchedule::new(beneficiary(), {start}, {duration}, {total_amount}).unwrap();
    assert_eq!(s.releasable({start}), 0);
}}

#[test]
fn fully_releasable_after_end() {{
    let s = VestingSchedule::new(beneficiary(), {start}, {duration}, {total_amount}).unwrap();
    assert_eq!(s.releasable({end} + 1), {total_amount});
}}

#[test]
fn release_decrements_remaining() {{
    let s = VestingSchedule::new(beneficiary(), 0, {duration}, {total_amount}).unwrap();
    let (s2, _) = s.release({duration}).unwrap();
    assert!(s2.release({duration}).is_err());
}}
"#,
            start = start,
            duration = duration,
            total_amount = total_amount,
            end = end
        ),
    )?;
    Ok(())
}

fn write_readme(out: &Path, start: u64, duration: u64, total_amount: u64) -> anyhow::Result<()> {
    std::fs::write(
        out.join("README.md"),
        format!(
            r#"# Vesting scaffold

> **Pre-production, unaudited, testnet-only.**

Generated by `kcp scaffold vesting`. Demonstrates linear DAA-height vesting:
{total_amount} sompi over {duration} DAA units starting at height {start}.

## Run

```sh
cargo run
cargo test
```

## Before live use

- Replace `[0x01u8; 32]` with a real Schnorr x-only public key.
- Use real DAA heights from a connected `kaspad` node.
- Persist `VestingSchedule` after each `release()` call.
"#,
            total_amount = total_amount,
            duration = duration,
            start = start
        ),
    )?;
    Ok(())
}
