//! Yield vault scaffold — YieldVaultProfile shares/assets accounting demo.

use anyhow::{bail, Context};
use std::path::{Path, PathBuf};

pub struct YieldVaultConfig {
    pub initial_deposit: u64,
    pub yield_amount: u64,
    pub out_dir: PathBuf,
    pub workspace_path: PathBuf,
}

pub fn generate(cfg: &YieldVaultConfig) -> anyhow::Result<()> {
    if cfg.initial_deposit == 0 {
        bail!("initial_deposit must be > 0");
    }

    let ws = cfg
        .workspace_path
        .canonicalize()
        .context("workspace_path does not exist")?;

    for p in &[
        cfg.out_dir.join("Cargo.toml"),
        cfg.out_dir.join("src/main.rs"),
        cfg.out_dir.join("tests/yield_vault_smoke.rs"),
        cfg.out_dir.join("README.md"),
    ] {
        if p.exists() {
            bail!("output file already exists: {:?}", p);
        }
    }

    std::fs::create_dir_all(cfg.out_dir.join("src")).context("create src")?;
    std::fs::create_dir_all(cfg.out_dir.join("tests")).context("create tests")?;

    write_cargo_toml(&cfg.out_dir, &ws)?;
    write_main_rs(&cfg.out_dir, cfg.initial_deposit, cfg.yield_amount)?;
    write_smoke_test(&cfg.out_dir, cfg.initial_deposit, cfg.yield_amount)?;
    write_readme(&cfg.out_dir, cfg.initial_deposit, cfg.yield_amount)?;
    Ok(())
}

fn write_cargo_toml(out: &Path, ws: &Path) -> anyhow::Result<()> {
    let dep = ws.join("crates/kcp-yield-vault");
    std::fs::write(
        out.join("Cargo.toml"),
        format!(
            r#"[package]
name = "my-yield-vault"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[[bin]]
name = "my-yield-vault"
path = "src/main.rs"

[dependencies]
kcp-yield-vault = {{ path = "{}" }}
"#,
            dep.display()
        ),
    )?;
    Ok(())
}

fn write_main_rs(out: &Path, initial_deposit: u64, yield_amount: u64) -> anyhow::Result<()> {
    std::fs::write(
        out.join("src/main.rs"),
        format!(
            r#"//! Yield vault scaffold — pre-production, unaudited, testnet-only.
//! Generated by `kcp scaffold yield-vault`.

use kcp_yield_vault::profile::YieldVaultProfile;

fn main() {{
    let vault = YieldVaultProfile::new();

    // [1] First deposit — 1:1 initialisation
    let (vault, shares_a) = vault.deposit({initial_deposit}).expect("deposit");
    println!("=== Yield Vault scaffold ===");
    println!("    deposited : {initial_deposit} sompi → {{shares_a}} shares");

    // [2] Yield accrues
    let vault = vault.accrue({yield_amount});
    println!("    accrued   : {yield_amount} sompi yield");
    println!("    rate      : 1 share = {{:.4}} assets",
        vault.total_assets as f64 / vault.total_shares as f64);

    // [3] Second deposit — gets fewer shares
    let preview = vault.preview_deposit({initial_deposit});
    let (vault, shares_b) = vault.deposit({initial_deposit}).expect("deposit");
    println!("    deposited : {initial_deposit} sompi → {{shares_b}} shares (preview: {{preview}})");

    // [4] First depositor redeems
    let assets_preview = vault.preview_redeem(shares_a);
    let (vault, assets_out) = vault.redeem(shares_a).expect("redeem");
    println!("    redeemed  : {{shares_a}} shares → {{assets_out}} sompi (preview: {{assets_preview}})");

    println!("    remaining : {{}} assets / {{}} shares", vault.total_assets, vault.total_shares);
    println!("Pre-production, unaudited, testnet-only.");
    let _ = shares_b;
}}
"#,
            initial_deposit = initial_deposit,
            yield_amount = yield_amount
        ),
    )?;
    Ok(())
}

fn write_smoke_test(out: &Path, initial_deposit: u64, yield_amount: u64) -> anyhow::Result<()> {
    std::fs::write(
        out.join("tests/yield_vault_smoke.rs"),
        format!(
            r#"use kcp_yield_vault::profile::YieldVaultProfile;

#[test]
fn first_deposit_one_to_one() {{
    let vault = YieldVaultProfile::new();
    let (v2, shares) = vault.deposit({initial_deposit}).unwrap();
    assert_eq!(shares, {initial_deposit});
    assert_eq!(v2.total_assets, {initial_deposit});
}}

#[test]
fn yield_increases_rate() {{
    let vault = YieldVaultProfile::new();
    let (v2, _) = vault.deposit({initial_deposit}).unwrap();
    let v3 = v2.accrue({yield_amount});
    assert!(v3.total_assets > v3.total_shares);
}}

#[test]
fn redeem_returns_assets() {{
    let vault = YieldVaultProfile::new();
    let (v2, shares) = vault.deposit({initial_deposit}).unwrap();
    let (_, returned) = v2.redeem(shares).unwrap();
    assert_eq!(returned, {initial_deposit});
}}
"#,
            initial_deposit = initial_deposit,
            yield_amount = yield_amount
        ),
    )?;
    Ok(())
}

fn write_readme(out: &Path, initial_deposit: u64, yield_amount: u64) -> anyhow::Result<()> {
    std::fs::write(
        out.join("README.md"),
        format!(
            r#"# Yield vault scaffold

> **Pre-production, unaudited, testnet-only.**

Generated by `kcp scaffold yield-vault`. Demonstrates ERC4626-equivalent
shares/assets accounting: {initial_deposit} sompi initial deposit,
{yield_amount} sompi yield accrual, redemption at improved rate.

## Run

```sh
cargo run
cargo test
```

## Before live use

- Pair with `kcp-ktt-token` to represent shares as on-chain transferable tokens.
- Lock underlying assets in a `kcp-vault` P2SH covenant.
- Never expose `total_assets` / `total_shares` without verifying against on-chain state.
"#,
            initial_deposit = initial_deposit,
            yield_amount = yield_amount
        ),
    )?;
    Ok(())
}
