#![no_main]
//! CSCI vProg guest for `ComplianceToken` — generated by portrait-atelier (M2).
//! new_state_hash is derived from the portrait body Return expression (M2).
//! Fields not referenced by the return expr are carried forward unchanged.
//! Journal: covenant_id[32] || new_state_hash[32] || rule_hash[32] || seq[8 LE]
risc0_zkvm::guest::entry!(main);

use risc0_zkvm::guest::env;
use sha2::{Digest, Sha256};

/// Auto-derived KovId: sha256(silverc compiled script bytes).
const COV_ID: [u8; 32] = [0xf1, 0xce, 0x2f, 0x9b, 0x04, 0xd8, 0x21, 0x89, 0x5b, 0x3f, 0xcb, 0x00, 0x92, 0xb9, 0xcb, 0xc5, 0xd9, 0x4e, 0xe5, 0xbe, 0xe2, 0xaf, 0xa8, 0xac, 0x59, 0xe3, 0x30, 0x1e, 0x68, 0x0e, 0xce, 0x2f];

fn sha256_bytes(data: &[u8]) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update(data);
    h.finalize().into()
}

fn encode_state(balance: i64) -> Vec<u8> {
    let mut out: Vec<u8> = Vec::new();
    out.extend_from_slice(&balance.to_le_bytes());
    out
}

/// Verify the `verify_compliance` VProg transition and return the 104-byte CSCI journal.
fn verify_compliance(covenant_id: [u8; 32], prev_seq: u64, balance: i64) -> [u8; 104] {
    let amount: i64 = env::read();
    let new_balance = balance - amount;
    let new_state_bytes = encode_state(new_balance);
    let new_state_hash = sha256_bytes(&new_state_bytes);
    let rule_hash = sha256_bytes(b"verify_compliance"); // rule = entry point name
    let new_seq = prev_seq.checked_add(1).expect("seq overflow");

    let mut journal = [0u8; 104];
    journal[..32].copy_from_slice(&covenant_id);
    journal[32..64].copy_from_slice(&new_state_hash);
    journal[64..96].copy_from_slice(&rule_hash);
    journal[96..].copy_from_slice(&new_seq.to_le_bytes());
    journal
}

fn main() {
    let covenant_id = COV_ID; // auto-derived KovId
    let prev_seq: u64 = env::read();
    let balance: i64 = env::read();
    let journal = verify_compliance(covenant_id, prev_seq, balance);
    env::commit_slice(&journal);
}
