//! Blind negotiation and mate-proof construction for two-party attestation.
//!
//! ## Blind negotiation
//!
//! Each counterparty independently generates a 32-byte random share. The two
//! shares are exchanged **off-band** (outside this library). The combined
//! blinding factor is their XOR:
//!
//! ```text
//! blind = share_a XOR share_b
//! ```
//!
//! This is symmetric: `negotiate_blind(a, b) == negotiate_blind(b, a)`. The
//! result is uniformly random provided at least one share is drawn from a
//! cryptographically secure RNG (CSPRNG), which prevents either party from
//! unilaterally choosing a blind that enables later equivocation.
//!
//! In v0, each party commits to the shared record under their *own* blind
//! (not the XOR). The XOR serves as a documented reference design for how the
//! negotiated blind would be used in a future protocol version where both
//! parties commit to the same blind.
//!
//! ## Mate proof
//!
//! A [`MateProof`] carries everything needed to verify that both parties
//! committed to the **same** attestation record under their respective blinds:
//!
//! - the canonical JSON bytes of the shared record,
//! - party A's blind and claimed commitment,
//! - party B's blind and claimed commitment.
//!
//! [`verify_mate`] recomputes both commitments from the disclosed record bytes
//! and blinds, then constant-time-compares them to the claimed values. Both
//! comparisons must pass. This is the "equality under disclosed blinds" proof
//! (analogous to `DisclosedProof` in the Kii PLA donor).
//!
//! **Privacy:** the canonical record bytes and both blinds are disclosed to
//! the verifier. Suitable for bilateral dispute resolution where both parties
//! consent to disclosure.
//!
//! ## SHA-256 vs. Poseidon divergence
//!
//! The Kii PLA donor uses a BN254 Poseidon commitment (ZK-friendly). v0 here
//! uses SHA-256 — same documented divergence as `kcp-sealed-lineage`. The
//! Poseidon upgrade is tied to KIP-16-era ZK work; it is out of scope for v0.
//!
//! ## Status
//!
//! **v0 — unaudited.** Mating is verified off-chain only.

use sha2::{Digest, Sha256};

use crate::error::{Error, Result};
use crate::record::canonical_bytes;

/// XOR two 32-byte shares into a negotiated blinding factor.
///
/// Shares must be exchanged off-band before calling this function. The
/// operation is symmetric: `negotiate_blind(a, b) == negotiate_blind(b, a)`.
/// The result is uniformly random provided at least one share was generated by
/// a CSPRNG.
pub fn negotiate_blind(share_a: [u8; 32], share_b: [u8; 32]) -> [u8; 32] {
    let mut out = [0u8; 32];
    for i in 0..32 {
        out[i] = share_a[i] ^ share_b[i];
    }
    out
}

/// A mate proof demonstrating that both counterparties committed to the same
/// attestation record under their respective disclosed blinds.
///
/// Construct this after both parties have disclosed their blinds off-band, then
/// pass it to [`verify_mate`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MateProof {
    /// The `attestation_id` that this proof is bound to (SHA-256 of the record
    /// canonical JSON; must equal [`crate::record::attestation_id`] of the
    /// record encoded in `record_bytes`).
    pub attestation_id: [u8; 32],
    /// Canonical JSON bytes of the shared attestation record.
    ///
    /// These are the exact bytes used as the pre-image for both commitments.
    /// Disclosing them reveals the record to the verifier.
    pub record_bytes: Vec<u8>,
    /// Party A's 32-byte blinding factor (disclosed).
    pub blind_a: [u8; 32],
    /// Party B's 32-byte blinding factor (disclosed).
    pub blind_b: [u8; 32],
    /// Party A's claimed commitment (`SHA-256(record_bytes || blind_a)`).
    pub commit_a: [u8; 32],
    /// Party B's claimed commitment (`SHA-256(record_bytes || blind_b)`).
    pub commit_b: [u8; 32],
}

/// Recompute a SHA-256 commitment from raw record bytes and a blind.
///
/// `commitment = SHA-256(record_bytes || blind)`
pub(crate) fn recompute_commit(record_bytes: &[u8], blind: &[u8; 32]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(record_bytes);
    hasher.update(blind);
    let digest = hasher.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&digest);
    out
}

/// Constant-time equality of two 32-byte arrays.
///
/// Prevents timing side-channels when comparing commitments. All 32 bytes
/// are always compared regardless of the first divergence.
fn ct_eq_32(a: &[u8; 32], b: &[u8; 32]) -> bool {
    let mut diff = 0u8;
    for i in 0..32 {
        diff |= a[i] ^ b[i];
    }
    diff == 0
}

/// Verify a [`MateProof`].
///
/// Checks (in order):
///
/// 1. The `attestation_id` in the proof matches `SHA-256(record_bytes)`.
/// 2. Recomputes `commit_a' = SHA-256(record_bytes || blind_a)` and
///    constant-time-compares to `proof.commit_a`.
/// 3. Recomputes `commit_b' = SHA-256(record_bytes || blind_b)` and
///    constant-time-compares to `proof.commit_b`.
///
/// All three checks must pass. Steps 2 and 3 together prove that both parties
/// committed to the **same** record (equality-under-disclosed-blinds).
///
/// # Errors
///
/// - [`Error::MateAttestationIdMismatch`] if the `attestation_id` in the proof
///   does not match the hash of `record_bytes`.
/// - [`Error::MateCommitAMismatch`] if `commit_a` does not match.
/// - [`Error::MateCommitBMismatch`] if `commit_b` does not match.
pub fn verify_mate(proof: &MateProof) -> Result<()> {
    // 1. Verify the attestation_id is consistent with the disclosed record.
    let mut id_hasher = Sha256::new();
    id_hasher.update(&proof.record_bytes);
    let id_digest = id_hasher.finalize();
    let mut recomputed_id = [0u8; 32];
    recomputed_id.copy_from_slice(&id_digest);
    if !ct_eq_32(&recomputed_id, &proof.attestation_id) {
        return Err(Error::MateAttestationIdMismatch);
    }

    // 2. Verify Party A's commitment.
    let recomputed_a = recompute_commit(&proof.record_bytes, &proof.blind_a);
    if !ct_eq_32(&recomputed_a, &proof.commit_a) {
        return Err(Error::MateCommitAMismatch);
    }

    // 3. Verify Party B's commitment.
    let recomputed_b = recompute_commit(&proof.record_bytes, &proof.blind_b);
    if !ct_eq_32(&recomputed_b, &proof.commit_b) {
        return Err(Error::MateCommitBMismatch);
    }

    Ok(())
}

/// Build a [`MateProof`] from an attestation record, both parties' blinds,
/// and both parties' claimed commitments.
///
/// The `record` value is serialised to canonical JSON bytes internally (using
/// [`crate::record::canonical_bytes`]). The `attestation_id` is derived as
/// `SHA-256(canonical_json(record))` — note this is the unblinded hash of the
/// record, not a commitment.
///
/// # Errors
///
/// Returns [`Error::Canonical`] if `record` cannot be serialised to JSON.
pub fn build_mate_proof<T: serde::Serialize>(
    record: &T,
    blind_a: [u8; 32],
    blind_b: [u8; 32],
    commit_a: [u8; 32],
    commit_b: [u8; 32],
) -> Result<MateProof> {
    let record_bytes = canonical_bytes(record)?;
    let mut id_hasher = Sha256::new();
    id_hasher.update(&record_bytes);
    let id_digest = id_hasher.finalize();
    let mut aid = [0u8; 32];
    aid.copy_from_slice(&id_digest);
    Ok(MateProof {
        attestation_id: aid,
        record_bytes,
        blind_a,
        blind_b,
        commit_a,
        commit_b,
    })
}

/// Test-only re-export of the internal `recompute_commit` helper so that the
/// `invariants` test module can build proofs without duplicating the SHA-256
/// logic.
#[cfg(test)]
pub(crate) fn recompute_commit_for_test(record_bytes: &[u8], blind: &[u8; 32]) -> [u8; 32] {
    recompute_commit(record_bytes, blind)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    const BLIND_A: [u8; 32] = [0x11u8; 32];
    const BLIND_B: [u8; 32] = [0x22u8; 32];

    fn make_proof() -> MateProof {
        let record = json!({"subject": "aabb", "terms_hash": "ccdd", "nonce": 1});
        let record_bytes = canonical_bytes(&record).unwrap();
        let commit_a = recompute_commit(&record_bytes, &BLIND_A);
        let commit_b = recompute_commit(&record_bytes, &BLIND_B);
        build_mate_proof(&record, BLIND_A, BLIND_B, commit_a, commit_b).unwrap()
    }

    // ---- negotiate_blind ----

    #[test]
    fn negotiate_blind_symmetric() {
        let a = [0xaau8; 32];
        let b = [0x55u8; 32];
        assert_eq!(negotiate_blind(a, b), negotiate_blind(b, a));
    }

    #[test]
    fn negotiate_blind_xor_cancels() {
        let a = [0x33u8; 32];
        assert_eq!(negotiate_blind(a, a), [0u8; 32]);
    }

    #[test]
    fn negotiate_blind_known_vector() {
        let a = [0xaau8; 32];
        let b = [0xbbu8; 32];
        // aa XOR bb = 0x11
        assert_eq!(negotiate_blind(a, b), [0x11u8; 32]);
    }

    // ---- verify_mate — positive ----

    #[test]
    fn verify_mate_accepts_valid_proof() {
        let proof = make_proof();
        verify_mate(&proof).unwrap();
    }

    #[test]
    fn verify_mate_accepts_same_blind_for_both_parties() {
        let record = json!({"nonce": 99});
        let record_bytes = canonical_bytes(&record).unwrap();
        let blind = [0xdeu8; 32];
        let commit = recompute_commit(&record_bytes, &blind);
        let proof = build_mate_proof(&record, blind, blind, commit, commit).unwrap();
        verify_mate(&proof).unwrap();
    }

    // ---- verify_mate — wrong blind ----

    #[test]
    fn verify_mate_rejects_wrong_blind_a() {
        let mut proof = make_proof();
        proof.blind_a = [0xffu8; 32]; // wrong blind_a
        let err = verify_mate(&proof).unwrap_err();
        assert!(
            matches!(err, Error::MateCommitAMismatch),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn verify_mate_rejects_wrong_blind_b() {
        let mut proof = make_proof();
        proof.blind_b = [0xffu8; 32]; // wrong blind_b
        let err = verify_mate(&proof).unwrap_err();
        assert!(
            matches!(err, Error::MateCommitBMismatch),
            "unexpected error: {err}"
        );
    }

    // ---- verify_mate — wrong record ----

    #[test]
    fn verify_mate_rejects_wrong_record() {
        let mut proof = make_proof();
        // Corrupt a byte in record_bytes — ID check fires first.
        proof.record_bytes[0] ^= 0xff;
        let err = verify_mate(&proof).unwrap_err();
        assert!(
            matches!(
                err,
                Error::MateAttestationIdMismatch | Error::MateCommitAMismatch
            ),
            "unexpected error: {err}"
        );
    }

    // ---- verify_mate — mismatched commit ----

    #[test]
    fn verify_mate_rejects_mismatched_commit_a() {
        let mut proof = make_proof();
        proof.commit_a = [0xffu8; 32]; // wrong claimed commit_a
        let err = verify_mate(&proof).unwrap_err();
        assert!(
            matches!(err, Error::MateCommitAMismatch),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn verify_mate_rejects_mismatched_commit_b() {
        let mut proof = make_proof();
        proof.commit_b = [0xffu8; 32]; // wrong claimed commit_b
        let err = verify_mate(&proof).unwrap_err();
        assert!(
            matches!(err, Error::MateCommitBMismatch),
            "unexpected error: {err}"
        );
    }

    // ---- attestation_id check ----

    #[test]
    fn verify_mate_rejects_wrong_attestation_id() {
        let mut proof = make_proof();
        proof.attestation_id = [0xffu8; 32]; // tampered id
        let err = verify_mate(&proof).unwrap_err();
        assert!(
            matches!(err, Error::MateAttestationIdMismatch),
            "unexpected error: {err}"
        );
    }
}
